### ISSUE TITLE
Delete and Send message from web plugin is not getting sync to device

### ISSUE THREAD

**Issue by priyadarshi** [AppLozic/Applozic-Android-SDK#109]
Login to web plugin and device with same user.
Delete and Send message from web plugin is not getting sync to device

**Comment by devashishmamgain** [comment]
@priyadarshi pls test

**Comment by priyadarshi** [comment]
Verified.

**Comment by priyadarshi** [comment]
Open the chat list of a user and run app in background. Send messages from web plugin. Open the app, messages won't sync to device.

**Comment by devashishmamgain** [comment]
@rathanbpoojary

**Comment by devashishmamgain** [comment]
@priyadarshi changes completed, please test

**Comment by priyadarshi** [comment]
@devashishmamgain 
1)Activate airplane mode on device and delete message from web plugin. Off airplane mode but deleted message won't sync to device.

2)Login to device and web plugin with user1. Activate airplane mode on device. Send messages from web plugin to user2. Off airplane mode on device, all messages will sync up. Now login with user2 in different browser and read all messages, web plugin will show double and device will show single tick.

**Comment by devashishmamgain** [comment]
above both things require changes on server side.

**Comment by priyadarshi** [comment]
Closing the issue as above issues are dependent on https://github.com/AppLozic/Applozic-Server/issues/318
