### ISSUE TITLE
Messages not showing up on conversation list for both sender and receiver

### ISSUE THREAD

**Issue by amanpwl92** [AppLozic/Applozic-Android-SDK#11]

**Comment by devashishmamgain** [comment]
In which specific case?

**Comment by amanpwl92** [comment]
I have installed Applozic sample app on two devices. When i send message, a notification comes on receiver's side but on click of it, nothing comes.On sender's side, message is displayed with double tick(some times twice - one with double tick and other with clock). When we go back and again open the conversation, nothing is coming.

**Comment by priyadarshi** [comment]
Hi Aman,
Please verify the issue with latest build.

**Comment by priyadarshi** [comment]
Verified.
