### ISSUE TITLE
Multiple photo selection in android

### ISSUE THREAD

**Issue by adarshmishra** [AppLozic/Applozic-Android-SDK#112]

**Comment by priyadarshi** [comment]
- [ ] Cancel button spelling is wrong.
- [ ] There is no separator between cancel and send button.

**Comment by priyadarshi** [comment]
- [ ] New Attachment is not after adding few files

**Comment by priyadarshi** [comment]
- [ ] Attached files and delete all selected files. Click on send button shouldn't allow to send message.

**Comment by priyadarshi** [comment]
- [ ] click on Attached file and wait for few minutes then select file, it won't navigate to main screen.

**Comment by adarshmishra** [comment]
@priyadarshi 
Please check.

**Comment by priyadarshi** [comment]
Verified.
