### ISSUE TITLE
 Notification is not getting cleared if chat list is open and click on group to read message

### ISSUE THREAD

**Issue by priyadarshi** [AppLozic/Applozic-Android-SDK#117]
Notification is not getting clean if chat list is open and click on group to read message

**Comment by devashishmamgain** [comment]
@priyadarshi

**Comment by priyadarshi** [comment]
- [ ] Open group chat and run it in background. Send message from other user. Without click on notification, open the app and read the message of group but notification won't clean up.

**Comment by priyadarshi** [comment]
Verified.
