### ISSUE TITLE
Automatic message between users with a custom layout

### ISSUE THREAD

**Issue by devashishmamgain** [AppLozic/Applozic-Android-SDK#125]
Send a custom message from user A to user B, the message shouldn't look as if the user have sent. There will be a custom layout for the message.

**Comment by devashishmamgain** [comment]
Documentation: 
Send an automated custom message to connect 2 users. The message UI will look for both users so that it doesn't look like a sent message.

How to send an automated users:
  Message message = new Message("contact@applozic.com", "hey! here's a match <3");
        new MobiComMessageService(this, MessageIntentService.class).sendCustomMessage(message);


Customize the background color for the custom message:
 ApplozicSetting.getInstance(this).setColor(ApplozicSetting.CUSTOM_MESSAGE_BACKGROUND_COLOR, Color.parseColor("#FFB3E5FC"));

**Comment by devashishmamgain** [comment]
@priyadarshi

**Comment by priyadarshi** [comment]
Verified.
