### ISSUE TITLE
Hide online status in the main conversation list if user is blocked

### ISSUE THREAD

**Issue by devashishmamgain** [AppLozic/Applozic-Android-SDK#130]
Hide online status in the main conversation list if user is blocked

**Comment by devashishmamgain** [comment]
@priyadarshi

**Comment by priyadarshi** [comment]
- [ ] After unblock user still not showing online status 
      Steps to reproduce -
      1) user1 and user2 both unblock for each other
      2) Activate airplane mode for user1 and from user2 block user1
      3) Deactivate airplane mode for user1 , online status will be disappeared for user2 from user1
      4) Now unblock user1 from user2, online status will be appeared for user2 from user1 but when
          we open user2 chat from user1 online will disappeared.

**Comment by priyadarshi** [comment]
Verified.
