### ISSUE TITLE
Unable to send recorded video after retrying recording multiple times

### ISSUE THREAD

**Issue by priyadarshi** [AppLozic/Applozic-Android-SDK#131]
Unable to send recorded video after retrying recording multiple times.

Log Detail:
03-28 13:37:02.203  19860-19860/com.mobicomkit.sample.debug I/GMPM﹕ To enable debug logging run: adb shell setprop log.tag.GMPM VERBOSE
03-28 13:37:02.217  19860-19860/com.mobicomkit.sample.debug E/GMPM﹕ GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.
03-28 13:37:02.217  19860-19860/com.mobicomkit.sample.debug E/GMPM﹕ Scheduler not set. Not logging error/warn.
03-28 13:37:02.242  19860-19875/com.mobicomkit.sample.debug E/GMPM﹕ Uploading is not possible. App measurement disabled
03-28 13:37:02.393  19860-19885/com.mobicomkit.sample.debug I/HttpRequestUtils﹕ Calling url: https://apps.applozic.com/rest/ws/user/status?lastSeenAt=1459152309630
03-28 13:37:02.393  19860-19886/com.mobicomkit.sample.debug I/HttpRequestUtils﹕ Calling url: https://apps.applozic.com/rest/ws/user/blocked/sync?lastSyncTime=1459152309637
03-28 13:37:02.575  19860-19860/com.mobicomkit.sample.debug W/System.err﹕ java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.applozic.mobicommons.people.contact.Contact.getContactIds()' on a null object reference
03-28 13:37:02.576  19860-19860/com.mobicomkit.sample.debug W/System.err﹕ at com.applozic.mobicomkit.uiwidgets.conversation.fragment.MobiComConversationFragment.sendMessage(MobiComConversationFragment.java:1070)
03-28 13:37:02.576  19860-19860/com.mobicomkit.sample.debug W/System.err﹕ at com.applozic.mobicomkit.uiwidgets.conversation.fragment.MobiComConversationFragment.sendMessage(MobiComConversationFragment.java:1151)
03-28 13:37:02.576  19860-19860/com.mobicomkit.sample.debug W/System.err﹕ at com.applozic.mobicomkit.uiwidgets.conversation.ConversationUIService.onActivityResult(ConversationUIService.java:177)
03-28 13:37:02.576  19860-19860/com.mobicomkit.sample.debug W/System.err﹕ at com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity.onActivityResult(ConversationActivity.java:314)
03-28 13:37:02.576  19860-19860/com.mobicomkit.sample.debug W/System.err﹕ at android.app.Activity.dispatchActivityResult(Activity.java:6456)
03-28 13:37:02.576  19860-19860/com.mobicomkit.sample.debug W/System.err﹕ at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
03-28 13:37:02.577  19860-19860/com.mobicomkit.sample.debug W/System.err﹕ at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3089)
03-28 13:37:02.577  19860-19860/com.mobicomkit.sample.debug W/System.err﹕ at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
03-28 13:37:02.577  19860-19860/com.mobicomkit.sample.debug W/System.err﹕ at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
03-28 13:37:02.577  19860-19860/com.mobicomkit.sample.debug W/System.err﹕ at android.app.ActivityThread.-wrap11(ActivityThread.java)
03-28 13:37:02.577  19860-19860/com.mobicomkit.sample.debug W/System.err﹕ at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
03-28 13:37:02.577  19860-19860/com.mobicomkit.sample.debug W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
03-28 13:37:02.577  19860-19860/com.mobicomkit.sample.debug W/System.err﹕ at android.os.Looper.loop(Looper.java:148)
03-28 13:37:02.577  19860-19860/com.mobicomkit.sample.debug W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5417)
03-28 13:37:02.577  19860-19860/com.mobicomkit.sample.debug W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
03-28 13:37:02.577  19860-19860/com.mobicomkit.sample.debug W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-28 13:37:02.577  19860-19860/com.mobicomkit.sample.debug W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-28 13:37:02.595  19860-19889/com.mobicomkit.sample.debug D/OpenGLRenderer﹕ Use EGL_SWAP_BEHAVIOR_PRESERVED: true
03-28 13:37:02.695  19860-19889/com.mobicomkit.sample.debug I/Adreno-EGL﹕ <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
03-28 13:37:02.699  19860-19889/com.mobicomkit.sample.debug I/OpenGLRenderer﹕ Initialized EGL, version 1.4
03-28 13:37:02.752  19860-19860/com.mobicomkit.sample.debug I/MTBroadcastReceiver﹕ Received broadcast, action: INSTRUCTION, message: null
03-28 13:37:03.159  19860-19866/com.mobicomkit.sample.debug W/art﹕ Suspending all threads took: 18.390ms
03-28 13:37:03.197  19860-19890/com.mobicomkit.sample.debug I/ApplozicMqttService﹕ Connecting to mqtt...
03-28 13:37:03.695  19860-19885/com.mobicomkit.sample.debug I/MessageClientService﹕ Sync UserDetails response is:{"status":"success","generatedAt":1459152423829,"response":[]}
03-28 13:37:03.749  19860-19890/com.mobicomkit.sample.debug I/ApplozicMqttService﹕ UserKeyString, status:agpzfmFwcGxvemljchMLEgZTdVVzZXIYgICAgMK46gsM, 1
03-28 13:37:03.750  19860-19890/com.mobicomkit.sample.debug I/ApplozicMqttService﹕ Subscribing to conversation topic.
03-28 13:37:04.589  19860-19890/com.mobicomkit.sample.debug I/ApplozicMqttService﹕ Subscribed to topic: typing-applozic-sample-app-ranjeet

**Comment by adarshmishra** [comment]
@priyadarshi Not able to reproduce on my device. Looks like  it is specific to device. Plese test it with some other devices.

**Comment by priyadarshi** [comment]
For other devices, it is working fine. It is happening for my device only, so closing the ticket.

**Comment by devashishmamgain** [comment]
@priyadarshi @adarshmishra @Sunilkumarr lets use Ranjeet's device to reproduce it. If it can happen on Ranjeet's device, it can happen on customer's device as well.

**Comment by adarshmishra** [comment]
@priyadarshi  please test and close.

**Comment by priyadarshi** [comment]
Verified.
