### ISSUE TITLE
Open main app's activity on tap of toolbar in individual conversation

### ISSUE THREAD

**Issue by devashishmamgain** [AppLozic/Applozic-Android-SDK#144]
From the individual conversation, on tap of toolbar, open the configured activity by the calling app and pass userId as intent.

**Comment by devashishmamgain** [comment]
@priyadarshi for testing

@adarshmishra @Sunilkumarr 
Added meta data for opening app's activity in case of tap on toolbar of individual chat thread. If the following meta data is added, then the activity mentioned in the meta data will be opened with the intent as "userId"
  
  <meta-data
             android:name="com.applozic.mobicomkit.uiwidgets.toolbar.tap.activity"
             android:value="com.applozic.mobicomkit.sample.MainActivity" />

**Comment by priyadarshi** [comment]
Verified.
