### ISSUE TITLE
Invite Contact show/hide option

### ISSUE THREAD

**Issue by devashishmamgain** [AppLozic/Applozic-Android-SDK#147]
Invite Contact/Group show/hide option in People's activity where contact and group are displayed.

**Comment by devashishmamgain** [comment]
@priyadarshi In contacts and groups, if there are no contacts and groups available, "Invite Friends" was coming, made it hidden by default and removed it from group.
For displaying the invite friends button, the following setting is required:
                    ApplozicSetting.getInstance(context).showInviteFriendsButton();

**Comment by priyadarshi** [comment]
Verified.
