### ISSUE TITLE
users image uploading problem

### ISSUE THREAD

**Issue by martinnlora** [AppLozic/Applozic-Android-SDK#165]
only my image is loaded other users shows with default icon

**Comment by adarshmishra** [comment]
@reytum ,
Please test if issue still exists. This has been fixed in version 3.33.

**Comment by reytum** [comment]
@martinnlora We tested it with our sample project and its working fine.

Please make sure you are setting the image while user registration:

    User user = new User();
            user.setUserId(userId);
            user.setEmail(email);
            user.setDisplayName(displayName);
            user.setImageLink("http://cdn.arstechnica.net/wp-content/uploads/2016/02/5718897981_10faa45ac3_b-640x624.jpg");

For the contact list you need to set the image before adding the contact to the list:

 Contact contact8 = new Contact();
            contact8.setUserId("heather");
            contact8.setFullName("Heather");
            contact8.setImageURL("http://cdn.arstechnica.net/wp-content/uploads/2016/02/5718897981_10faa45ac3_b-640x624.jpg");
            contactList.add(contact8);

            new AppContactService(context).addAll(contactList);

**Comment by martinnlora** [comment]
my image is loading but other users images cannot load it shows default icon .i am sending user image url dynamically but drawables

**Comment by devashishmamgain** [comment]
@martinnlora What is the url you are using for the imagelink?
