### ISSUE TITLE
Populate all registered userId on contact list screen

### ISSUE THREAD

**Issue by adarshmishra** [AppLozic/Applozic-Android-SDK#166]

**Comment by adarshmishra** [comment]
**CONTACT LIST URL**:  Base_Url/rest/ws/user/filter

**Method Type**: GET



**Parameters**: 



| Parameter  | Required | Default  | Description |
| ------------- | ------------- | ------------- | ------------- |
| pageSize  | No  | 500  | user list to be returned |
| startTime  | No  | current time  | time used in retrieving users list   |

**Comment by adarshmishra** [comment]
@reytum,

Please add a preference for this to enable.

**Comment by sunip123** [comment]
#Verified

**Comment by adarshmishra** [comment]
@sunip123 ,please close this ticket if this is verified.
