### ISSUE TITLE
Change Primary Color of the Chat Screen when Library(AAR) using Gradle.

### ISSUE THREAD

**Issue by vipulasri** [AppLozic/Applozic-Android-SDK#170]
These features when library(AAR) is included using Gradle : 

1. Library should automatically get the Primary Color, Primary Dark Color and Accent Color of App(in which the Library is integrated) or there should be an option to do the same dynamically.

2. It should have an option to set the a specified account to be conversed with, like in sample app but should be able to implement it. (Note: Using AAR only not included all the 3 Library modules.)

**Comment by Sunilkumarr** [comment]
@vipulasri for changing the theme you can refer documentation link  https://www.applozic.com/docs/android-chat-sdk.html#theme-customization
