### ISSUE TITLE
File path too long on Windows, keep below 240 characters

### ISSUE THREAD

**Issue by vanjavanjavanja** [AppLozic/Applozic-Android-SDK#171]
![File path too long on Windows, keep below 240 characters](https://i.gyazo.com/f81e0a0818f55fc3ab65c9d1e37d7824.png)

Error:Error: File path too long on Windows, keep below 240 characters : **D:\Development\Android\Tolkovo\chat\Applozic-Android-SDK-master\Applozic-Android-SDK-master\mobicommons\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.1.1\res\drawable-xhdpi\abc_textfield_search_default_mtrl_alpha.9.png**

**Comment by vanjavanjavanja** [comment]
:)

**Comment by devashishmamgain** [comment]
@vanjavanjavanja let us know if your issue is resolved :)

**Comment by vanjavanjavanja** [comment]
yeap, of course, i've just moved the project folder up a little bit :) my fault, have to have some sleep perhaps

**Comment by devashishmamgain** [comment]
👍
