### ISSUE TITLE
Custom message views depending on the payload

### ISSUE THREAD

**Issue by vanjavanjavanja** [AppLozic/Applozic-Android-SDK#172]
Hi guys!

I would like to check with you how to do it right, not to invent the solution which would be absolutely incorrect in the end.

**Following requirements:**
I created a user - "moderator". With this user I'm going to send messages to a large number of different chat rooms via the web API.

In the mobile app (Android) I need to display messages from that user in a special way. For example, if he sent:

```
{
"type": "apple",
"message": "some A-message"
}
```

I want to show the image of an apple; when:

```
{
"type": "banana",
"message": "some B-message"
}
```

there should be a banana.

Which is the correct way to implement it:
1. How can I **"intercept" the message** in the chat to inflate an appropriate view instead of a default text once it arrives to the user's device?
2. With the help of what method can I check that the message was **sent from an exact user**? (I named him "moderator" in this post)
3. Is there any possibility for a **"hidden" payload** inside the message body? The way similar to push-notifications, when the json is packed inside and it is only available for the app to parse but not visible on the screen?

**Comment by devashishmamgain** [comment]
@vanjavanjavanja that's an amazing idea. We are actually working on something similar which is scheduled for the next week's release. Same solution will work for you.
All messages will now have a Meta-data which will be key value pair, and you can pass any number of key values in that. Depending on meta data you can trigger your actions.

**Comment by vanjavanjavanja** [comment]
@devashishmamgain just perfect! Thanks for the info. Could you suggest the way I can access the message body before it is actually shown to the user so that I can pre-process the data and trigger respective action? Or should I revisit this issue after release, when there'll be some info on how to work with Meta-data?

**Comment by glenswift** [comment]
+1

**Comment by devashishmamgain** [comment]
@vanjavanjavanja we will update the info in the same thread here after the release.

**Comment by vanjavanjavanja** [comment]
@devashishmamgain hi there! Could you please advise when some info may appear potentially? Need to know just for planning purposes. thanx

**Comment by devashishmamgain** [comment]
@vanjavanjavanja we have added a Map<String, String> metadata in Message, you can send key value pair in message.

https://github.com/AppLozic/Applozic-Android-SDK/blob/082efa19975ba32f7487ec0c5c0570674e2d61da/mobicomkit/src/main/java/com/applozic/mobicomkit/api/conversation/Message.java

Now, in DetailedConversationAdapter.java you can read the values from message.getMetaData and render the UI accordingly.

**Comment by bharathmanvas** [comment]
can you provide a sample
