### ISSUE TITLE
Starting chat in a Fragment

### ISSUE THREAD

**Issue by vanjavanjavanja** [AppLozic/Applozic-Android-SDK#173]
Hey
There is an example in the docs for [starting the messaging activity](https://www.applozic.com/docs/android-chat-sdk.html#step-6-for-starting-the-messaging-activity). 

I need to start an individual [group chat screen](https://www.applozic.com/resources/1078/images/real-time-update.png) in a `Fragment` that is nested in some `Activity` that extends `AppCompatActivity`:

![xxx](https://cloud.githubusercontent.com/assets/13190732/16102365/5e4d5422-3377-11e6-94e7-28329e79c2bf.png)

As far as I've researched the example app - [chat screen](https://www.applozic.com/resources/1009/images/real-time-update.png) is always being instantiated on a base of `ConversationActivity` that is being added to the back stack. That's not suitable for my requirements I guess.

Could you please elaborate on this? Might be also helpful for other developers if you copy it to `Get Started` docs :) :+1:

**Comment by multivoltage** [comment]
You want ConversationActivity list in your custom fragment? if yes, you cannot. Only method to see contact list and single user windows chat is to run ConversationActivity for example. Only ..XActivity from Applozic SDK

**Comment by vanjavanjavanja** [comment]
I want to put this screen https://www.applozic.com/resources/1078/images/real-time-update.png to a fragment.

**Comment by multivoltage** [comment]
What is Apploxic fragment? I cannto read anything about that in documentation

**Comment by vanjavanjavanja** [comment]
There is no special Applozic fragment. By Fragment I mean: https://developer.android.com/guide/components/fragments.html and I need to put Applozic conversation window (https://www.applozic.com/resources/1078/images/real-time-update.png) inside a Frament nested in some Activity.

**Comment by multivoltage** [comment]
SHORT: you cannot. because like said before, Applozic control all aspects with ConversationActivity...which is encapsulated inside library.

LONG: I had to translate some words. So instead import Applozic with gradle, i use module import function. I did edit some values. If you like code you can edit what you want. Using ConversationActivity my experience say me that list of contacts and single chat are two separate fragment. So you can use same fragment where you want.....MAYBE

**Comment by multivoltage** [comment]
Yes I ca conform. There are fragments.

**Comment by vanjavanjavanja** [comment]
@devashishmamgain, Devashish, maybe you can help on how to put ConversationFragment to an Activity that is not actually an instance of ConversationActivity?

**Comment by devashishmamgain** [comment]
@vanjavanjavanja its possible but need lot of work, we are simplifying it, accordingly will update the documentation, might take 3-4 days.

**Comment by vanjavanjavanja** [comment]
@devashishmamgain wow, perfect, as usual - great support! will be waiting for, thank you!

**Comment by vanjavanjavanja** [comment]
HI @devashishmamgain, are there any updates already? Thank you.

**Comment by stanislav-grin** [comment]
+1

**Comment by vanjavanjavanja** [comment]
Hi @Sunilkumarr, kindly suggest when approximately we could expect the updates on using chat in fragments, thank you!

**Comment by Sunilkumarr** [comment]
@vanjavanjavanja Hi, will be sending you the documentation by end of the day tomorrow.

**Comment by vanjavanjavanja** [comment]
Guys, any news?

**Comment by vanjavanjavanja** [comment]
@Sunilkumarr , sorry for disturbing, but are there any news?

**Comment by Sunilkumarr** [comment]
@vanjavanjavanja sorry for late reply,We have created a sample project for that . You can connect us at support

**Comment by gustavofc1997** [comment]
someone has tried to convert conversationactivity to fragment ? i need put the chat in a tabview
