### ISSUE TITLE
Callback for logout

### ISSUE THREAD

**Issue by multivoltage** [AppLozic/Applozic-Android-SDK#175]
Sdk provide a simple callback for login. 
But sometimes I have a simple button in my app used for "do logout" from the app. So user maybe call logout api for facebook or twitter etc... With your:
`new UserClientService(this).logout(); `
We don't know when sdk finished the logout procedure. I use to put a finish() in my app when user want to logout. In this calling `new UserClientService(this).logout(); ` and then `finish()` doesn' t work and I have to user a workaround with a simple countdown timer and cal `new UserClientService(this).logout(); ` into "onFinish()"

**Comment by devashishmamgain** [comment]
@multivoltage Merged changes from https://github.com/AppLozic/Applozic-Android-SDK/pull/178
