### ISSUE TITLE
Support of Emoji

### ISSUE THREAD

**Issue by vanjavanjavanja** [AppLozic/Applozic-Android-SDK#183]
We've found some commented code for :bowtie:emoji:bowtie: like here:
https://github.com/AppLozic/Applozic-Android-SDK/blob/master/mobicomkitui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java#L467

Wondering whether you are going to add them in some short period of time? Will it look like in all popular messengers?
![wpyjjkyij_0](https://cloud.githubusercontent.com/assets/13190732/16856879/47b423e8-4a25-11e6-8956-b19ea11c1a1d.jpg)

Thank you!

**Comment by devashishmamgain** [comment]
Emoji support is available but it increases the size of the sdk, also in android version, emoticons comes in the keyboard, thats the reason it is not added to the main sdk. We will send you the patch file for adding emoticons library.

**Comment by devashishmamgain** [comment]
Attached changes, see if this helps.
[modified.txt](https://github.com/AppLozic/Applozic-Android-SDK/files/365220/modified.txt)

**Comment by vanjavanjavanja** [comment]
That worked, thank you!
