### ISSUE TITLE
Sending unsolicited spam

### ISSUE THREAD

**Issue by ojame** [AppLozic/Applozic-Android-SDK#184]
> Hi James,
> 
> We have developed MQTT based chat SDK's for you. With our native SDK's you dont have to host any server, just the gradle dependency is enough to get you started with real time multi device synced chat.
> 
> Please check out our Git repo and Documentation. We would appreciate your feedback and suggestions, it would help us build a robust communication platform. We intend to bring IP messaging across all devices and all platforms with utmost simplicity.
> 
> Thanks in advance
>
> Pravin Singh
> Applozic, Inc

And then a few days later:

> Hi James,
> 
> Did you get a chance to look into my previous email? We are a bunch of developers just like you and your efforts would mean a lot to us. Please review our repo and documentation and let us know if you have any suggestions that could potentially help fellow developers. 
> 
> Here are some use cases of our platform:
> https://play.google.com/store/apps/details?id=com.cartrade.car&hl=en
> https://play.google.com/store/apps/details?id=com.timesgroup.magicbricks&hl=en
> http://www.eezyrent.com
> 
> ------------------
> Pravin Singh
> Applozic, Inc.

I'm not sure about everyone else, but I don't appreciate this approach to open source. I'm raising this here - in hopes to let others who are contributing know, that this company is spamming to better their products.

**Comment by vanjavanjavanja** [comment]
@ojame, that's a commercial company open sourced their client libraries (great move by the way). Making their business while offering you free support & consultancy - what's wrong?

p.s. I'm just an ordinary Applozic customer.

**Comment by adarshmishra** [comment]
Closing as not related to android code repo.
