### ISSUE TITLE
Filtering messages list

### ISSUE THREAD

**Issue by vanjavanjavanja** [AppLozic/Applozic-Android-SDK#185]
I would like to add filtering options to the Chat. For example, I need to filter the message list and show only messages containing a specific string like: 
```
List<Message> filteredMessageList = new ArrayList<Message>();
            for (Message message : nextMessageList) {
                if (message.getMessage().contains("Привет, индусы!")) {
                    filteredMessageList.add(message);
                }
            }
            nextMessageList.clear();
            nextMessageList = filteredMessageList;
```
Kindly suggest the most optimal place in SDK classes to put this code to. Thanks!

**Comment by adarshmishra** [comment]
@vanjavanjavanja , You can add conditions in sql row query itself.  Please see below method mention in MessageDataBaseService.java,
```
public List<Message> getMessages(Long startTime, Long endTime, Contact contact, Channel channel,Integer conversationId)

```
You can add one more argument and add predicate to queries.

**Comment by vanjavanjavanja** [comment]
Got it, will be playing with, thanks!
