### ISSUE TITLE
No resource found @color/common_action_bar_splitter', after updating android studio and google libraries

### ISSUE THREAD

**Issue by anirudha-banerjee** [AppLozic/Applozic-Android-SDK#186]
Error:(64, 29) No resource found that matches the given name (at 'background' with value '@color/common_action_bar_splitter').

Getting this error on building my code. The error is in file activity_applozic_location.xml
I got this error after i updated android studio and the google libraries to the latest. I updated mobicomkit dependency in my gradle.build to com.applozic.communication.uiwidget:mobicomkitui:4.53, but the error is still there. I have also done Invalidate Caches and Restart, clean project, rebuild project but the error is not fixed. 

Please can you tell me where i may be going wrong.

**Comment by devashishmamgain** [comment]
4.53 version is using a color code from the google play service 9.0.2
This is getting fixed in 4.54, will be available on monday night.

**Comment by anirudha-banerjee** [comment]
Thank you.
I reverted back to 9.0.2 and voila, error gone. Thank you.

**Comment by Sunilkumarr** [comment]
@anirudha-banerjee Hi  this is fixed in latest version 4.55
