### ISSUE TITLE
ImageCropActivity Conflict

### ISSUE THREAD

**Issue by monishagarwal215** [AppLozic/Applozic-Android-SDK#188]
Hi,

I have used one of the library with ImageCropView, and it is conflicting with you code.

Error:(92) Attribute "cropImageStyle" has already been defined
Error:(345) Attribute "highlightColor" has already been defined
Error:(345) Attribute "showThirds" has already been defined
Error:(345) Attribute "showCircle" has already been defined
Error:(345) Attribute "showHandles" has already been defined
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/monish/Library/Android/sdk/build-tools/23.0.2/aapt'' finished with non-zero exit value 1

**Comment by Sunilkumarr** [comment]
@monishagarwal215 if possible can you send us your app build.gradle file?

**Comment by monishagarwal215** [comment]
Due to same library integration conflict.
Now what i done to resolve is to remove my own library integration.
