### ISSUE TITLE
Customize Toolbar

### ISSUE THREAD

**Issue by amitg767** [AppLozic/Applozic-Android-SDK#190]
Remove the toolbar & some places we want the change the color of toolbar.
and also we want to change the color of applozic project(theme)..

**Comment by Sunilkumarr** [comment]
@amitg767 please check the documentation link  [customize theme](https://www.applozic.com/docs/android-chat-sdk.html#theme-customization )

**Comment by amitg767** [comment]
hi.. 
i want to add the user in Multiple Group in same time.. 

ApplozicChannelAddMemberTask.ChannelAddMemberListener channelAddMemberListener =  new ApplozicChannelAddMemberTask.ChannelAddMemberListener() {
            @Override
            public void onSuccess(String response, Context context) {
                //Response will be "success" if user is added successfully
                Log.i("ApplozicChannelMember","Add Response:" + response);

            }

            @Override
            public void onFailure(String response, Exception e, Context context) {

            }
        };

        ApplozicChannelAddMemberTask applozicChannelAddMemberTask =  new ApplozicChannelAddMemberTask(context,**channelKey**,userId,channelAddMemberListener);//pass channel key and userId whom you want to add to channel
        applozicChannelAddMemberTask.execute((Void)null);

**Comment by devashishmamgain** [comment]
@amitg767 can you please file separate issue for group as the current issue is for toolbar.
