### ISSUE TITLE
Issue with arabic Language selection in main app while using applozic android source code.

### ISSUE THREAD

**Issue by Luckyrana001** [AppLozic/Applozic-Android-SDK#191]
All text getting hidden , when i am going to Conversation Actity after setting my app language to arabic programatically.

below is english lang snap shot
https://www.dropbox.com/s/xezg2y72py4qn45/english%20text.png?dl=0

below is arabic lang snapshot:
https://www.dropbox.com/s/qul76b5u8no0k4p/arabic%20listing.png?dl=0

**Comment by neuronpool** [comment]
Hi, I'm having this same exact issue. Has there been any update on this? This post is almost a year old

**Comment by Sunilkumarr** [comment]
@neuronpool RTL has been added to the  repo https://github.com/AppLozic/Applozic-Android-SDK  you can try out the sample from here and which github link project are you referring to ?
