### ISSUE TITLE
issue while adding the user in  multiple Group

### ISSUE THREAD

**Issue by amitg767** [AppLozic/Applozic-Android-SDK#194]
hi.. 
i want to add the user in Multiple Group in same time..
in place of channelKey it is not accepting the multiple Group id

ApplozicChannelAddMemberTask.ChannelAddMemberListener channelAddMemberListener = new ApplozicChannelAddMemberTask.ChannelAddMemberListener() {
@Override
public void onSuccess(String response, Context context) {
//Response will be "success" if user is added successfully
Log.i("ApplozicChannelMember","Add Response:" + response);

        }

        @Override
        public void onFailure(String response, Exception e, Context context) {

        }
    };

    ApplozicChannelAddMemberTask applozicChannelAddMemberTask =  new ApplozicChannelAddMemberTask(context,**channelKey**,userId,channelAddMemberListener);//pass channel key and userId whom you want to add to channel
    applozicChannelAddMemberTask.execute((Void)null);

**Comment by Sunilkumarr** [comment]
@amitg767 
Use this method to add user to multiple groups
pass the channeKey 

  ```
         Set<Integer> channelKeys = new HashSet<>();
                    channelKeys.add(1234);
                    channelKeys.add(3444);
                   String response = ChannelService.getInstance(context).addMemberToMultipleChannelsProcessByChannelKeys(channelKeys, MobiComUserPreference.getInstance(context).getUserId());
``` //blocker method use thread or async task for adding user 

if response is success then user is added to groups else not

**Comment by amitg767** [comment]
hi sunil,

Response will be null.. 


![multiple grup](https://cloud.githubusercontent.com/assets/17022756/18339487/629cefd2-75bd-11e6-806c-a2947e456551.PNG)

![channelkey](https://cloud.githubusercontent.com/assets/17022756/18339490/697ff1a0-75bd-11e6-95d5-63af5864e6b4.PNG)

**Comment by devashishmamgain** [comment]
@amitg767 its a network call and you are running the network call in main thread.
please read about how to make network call in android, here is stackoverflow link to help you:
http://stackoverflow.com/questions/6343166/how-to-fix-android-os-networkonmainthreadexception

**Comment by amitg767** [comment]
Set<Integer> channelKeys = new HashSet<>();
                    channelKeys.add(1234);
                    channelKeys.add(3444);
                   String response = ChannelService.getInstance(context).addMemberToMultipleChannelsProcessByChannelKeys(channelKeys, MobiComUserPreference.getInstance(context).getUserId());
``` //blocker method use thread or async task for adding user 

if response is success then user is added to groups else not 

where i put this code..
