### ISSUE TITLE
removing applozic in chat list

### ISSUE THREAD

**Issue by gkathir15** [AppLozic/Applozic-Android-SDK#195]
The SDk provided shows Applozic as user in chat list,and also few users who are not associated with my account,is there any way to remove it.
Happy to hear from you.

**Comment by devashishmamgain** [comment]
@gkathir15 it is not the sdk but the sample app built for demo purpose, you can remove it by removing the code of "    private void buildContactData() {" from https://github.com/AppLozic/Applozic-Android-SDK/blob/master/app/src/main/java/com/applozic/mobicomkit/sample/LoginActivity.java

**Comment by gkathir15** [comment]
yeah thanks @devashishmamgain,i got it,yeah its not a SDK,since the repo is named as Android SDK,i just referred it,anyway thanks a lot.

**Comment by devashishmamgain** [comment]
@gkathir15 modules "mobicomkit", "mobicomkitui" and "mobicommons" are part of SDK and "app" is a sample demo app built using the sdk modules.

**Comment by gkathir15** [comment]
thanks a lot @devashishmamgain ,it was so kind of you.am done with the problem
