### ISSUE TITLE
enabling Chat balloons as in face book messenger.

### ISSUE THREAD

**Issue by gkathir15** [AppLozic/Applozic-Android-SDK#196]
The default SDK for android provided has a way to show balloon notification,but its not working on my lollipop,only i receive a notification.
revert me the steps to enable it

**Comment by Sunilkumarr** [comment]
@gkathir15 Hi,This chat heads notification is not available in current sdk.

**Comment by gkathir15** [comment]
are chat bubbles not chat heads?
https://www.applozic.com/docs/android-chat-sdk.html#chat-bubble
do you have any possible way to integrate Chat heads from external sources,please do instruct me.
Thanks for the response...
