### ISSUE TITLE
create group chat with type set to 'OPEN' returns null ID 

### ISSUE THREAD

**Issue by madibalive** [AppLozic/Applozic-Android-SDK#200]
Hi , am been using your sdk for a project am currently , but face some issues with creating a group set type OPEN for everyone for any one to join 

```
  ChannelInfo channelInfo  = new ChannelInfo(titl,channelMembersList);
        channelInfo.setType(Channel.GroupType.OPEN.getValue().intValue()); //group type
//        channelInfo.setChannelMetadata(channelMetadata); //Optional option for setting group meta data
         Channel channel = ChannelService.getInstance(getContext()).createChannel(channelInfo);
```

now when i try to get the object id 

```
channel.getClientGroupId() // return null 
``
```

**Comment by Sunilkumarr** [comment]
@madibalive  Hello you have to  use the create a group method in Thread or async task
    
            Channel channel = ChannelService.getInstance(getContext()).createChannel(channelInfo); //Thread or Async task
            if(channel != null){
                Log.i("Channel","channelKey"+channel.getKey());
            }

**Comment by madibalive** [comment]
Hi m, thanks for the quick reply , but am currently unable to start a group chat directly from code to chat screen 
```
  Intent intent = new Intent(MainActivity.this, ConversationActivity.class);
                                intent.putExtra(ConversationUIService.GROUP_ID, gossip.getString("chat_id"));      //Pass group id here.
                                startActivity(intent);

``` 

create chat group -- > enter chat directly   

as of now it navigates me to the conversationList screen 
create chat group -- > conversationList

**Comment by devashishmamgain** [comment]
@madibalive can you print the value of gossip.getString("chat_id") in logs?

**Comment by Sunilkumarr** [comment]
@madibalive

Hi you need pass  channel.getKey(); it's a group id 

For opening group chat directly pass channel.getKey() in intent then it will launch the group chat 

Intent intent = new Intent(MainActivity.this, ConversationActivity.class);              intent.putExtra(ConversationUIService.GROUP_ID, channel.getKey());    //pass the integer channel.getKey()
  startActivity(intent);
