### ISSUE TITLE
Initiate chat app users(Job Seekers) to Website users(Employer)

### ISSUE THREAD

**Issue by IOException722** [AppLozic/Applozic-Android-SDK#205]
Hey I can get message from website users to app users and also able to send. But not able to initiate the chat from app user to website user.

I tried the following code
Intent intent = new Intent(this, ConversationActivity.class);            
intent.putExtra(ConversationUIService.USER_ID, jobDetails.getJobId());             
intent.putExtra(ConversationUIService.DISPLAY_NAME, jobDetails.getCompanyName()); //put it for displaying the title.             
startActivity(intent);         

Output: Showing only a blank page with conversation title on action bar (No type box to write or send message at button)
Any help will be greatly appreciated.  Thanks

**Comment by Sunilkumarr** [comment]
@IOException722  can you send me the logs when you launch the chat and If possible can I have a debug apk for this send us at support@applozic.com

**Comment by IOException722** [comment]
Sure

**Comment by IOException722** [comment]
Hey I fixed the issue of sending and receiving the message. But its not showing details in chat bar.
I have send you email regarding this. Please check.
Thanks
Regards,
Abhay Kumar
