### ISSUE TITLE
Push notifications do not appear when application is closed

### ISSUE THREAD

**Issue by rizabudi** [AppLozic/Applozic-Android-SDK#206]
Hi I try a sample application in this project. Push notifications run correctly when the application is open. But after I close this application, push notifications will no longer appear. Push notifications will appear again when I re-open the application.

Are there any additional configuration for push notifications can appear when the application is not open?

**Comment by adarshmishra** [comment]
Yes, GCM/FCM need to configured on device and key need to be uploaded to our dashboard. You can go through, documentaion here:
https://www.applozic.com/docs/android-chat-sdk.html#step-5-push-notification-setup

**Comment by rizabudi** [comment]
@adarshmishra thanks, it works 👍
