### ISSUE TITLE
Crash on opening ConversationActivity

### ISSUE THREAD

**Issue by puneetgupta1808** [AppLozic/Applozic-Android-SDK#207]
java.lang.NoClassDefFoundError: com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity

I am opening the activity like this 

Intent intent = new Intent(getActivity(), ConversationActivity.class); intent.putExtra(ConversationUIService.USER_ID, "devashish@applozic.com");
intent.putExtra(ConversationUIService.DISPLAY_NAME, "Devashish Mamgain"); //put it for displaying the title.
startActivity(intent);

I have also added in AndroidManifest.xml

 <activity android:name="com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity"
                  android:configChanges="keyboardHidden|orientation|screenSize"
                  android:label="@string/app_name"
                  android:parentActivityName="com.pkg.p2o2.activity.MainActivity"
                  android:theme="@style/ApplozicTheme"
                  android:launchMode="singleTask" >
            
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value="com.pkg.p2o2.activity.MainActivity" />
        </activity>

**Comment by devashishmamgain** [comment]
can you share your build.gradle and androidmanifest.xml file, if possible, share it here else you can send it to us at support@applozic.com mentioning this same issue link.

**Comment by puneetgupta1808** [comment]
emailed you on support@applozic.com

**Comment by devashishmamgain** [comment]
thanks, we will check and update you soon.

**Comment by puneetgupta1808** [comment]
Hello Guys,

There was an issue with multidex enabling, now it's working.

**Comment by tinOfBeans** [comment]
How did you solve this issue?

**Comment by Sunilkumarr** [comment]
@tinOfBeans  You need to enable Multidex to your app from the below doc link https://developer.android.com/studio/build/multidex.html

**Comment by tinOfBeans** [comment]
Still didn't work for me, although I'm getting the following error:

java.lang.NoClassDefFoundError: Lcom/google/android/gms/location/internal/zzb;
...
...
at com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity.onCreate(ConversationActivity.java:350)

**Comment by Sunilkumarr** [comment]
@tinOfBeans can you paste your app build.gradle file

**Comment by tinOfBeans** [comment]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.0"
    defaultConfig {
        applicationId "xx.xx.xx"
        minSdkVersion 21
        targetSdkVersion 25
        multiDexEnabled true
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/ECLIPSE_.SF'
        exclude 'META-INF/ECLIPSE_.RSA'
    }
    dexOptions {
        preDexLibraries = false
    }
}

afterEvaluate {
    tasks.matching {
        it.name.startsWith('dex')
    }.each { dx ->
        if (dx.additionalParameters == null) {
            dx.additionalParameters = ['--multi-dex']
        } else {
            dx.additionalParameters += '--multi-dex'
        }
    }
}

repositories {
    mavenCentral()
}


dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile fileTree(dir: 'libs', include: ['*.jar'])
    ...
    compile 'com.android.support:multidex:1.0.1'
    testCompile 'junit:junit:4.12'
}

apply plugin: 'com.google.gms.google-services'

**Comment by Sunilkumarr** [comment]
@tinOfBeans and project level build.gardle file also needed

**Comment by tinOfBeans** [comment]
@Sunilkumarr 

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

ext.googlePlayServicesVersion = '9.0.2'
ext.supportLibraryVersion = '25.0.0'

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.google.gms:google-services:3.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://s3.amazonaws.com/repo.commonsware.com" }
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by Sunilkumarr** [comment]
@tinOfBeans in your app build.gardle file which version of google play service are you using?

**Comment by tinOfBeans** [comment]
@Sunilkumarr It works now! The problem was I had forgotten to add the play services to the app. Thank you for the help
