### ISSUE TITLE
How to configure with server url..

### ISSUE THREAD

**Issue by karthick229** [AppLozic/Applozic-Android-SDK#208]
App is running good.How i have to configure with my server url to integrate all the page to store that database in my server..

**Comment by devashishmamgain** [comment]
All chat data will be stored on our servers, you can configure webhook url to forward the chat data to your server.
https://www.applozic.com/docs/configuration.html#webhooks

**Comment by karthick229** [comment]
First of all ,thanks for the quick reply..I had another question,I don't want to share my chat details to be save on applozic server.My data must save on my own server only.What can i do for that?

**Comment by devashishmamgain** [comment]
You can go with the enterprise plan for this, get in touch with us at support@applozic.com to discuss
