### ISSUE TITLE
Audio/Video Support 

### ISSUE THREAD

**Issue by adarshmishra** [AppLozic/Applozic-Android-SDK#211]

**Comment by RiteshAdulkar** [comment]
@adarshmishra Hey is audio/video call is working in your sample app after adding audio/video dependencies as  mentioned in doc..?

**Comment by Sunilkumarr** [comment]
@RiteshAdulkar You need to add dependencies and audio-video call activity entries  in  android manifest and settings for enabling the audio video call 

This are links you can follow :
https://docs.applozic.com/docs/android-chat-sdk#section-gradle-dependency

Android manifest entries and settings to be added for audio-video call :
https://docs.applozic.com/docs/android-video-chat-and-audio-call-api

 You check the audio video sample project  from this GitHub link :
https://github.com/AppLozic/Applozic-Android-Chat-Sample/tree/master/Applozic-Android-AV-Sample

Reopen  this if does  not work after following above steps
