### ISSUE TITLE
 login to applozic app without registration

### ISSUE THREAD

**Issue by ramy1992** [AppLozic/Applozic-Android-SDK#217]
Applozic creates a new user if the user doesn't exist If it is a new user, a new user account will get created else existing user will be logged in to the application.
But I want to make a activity for login  without registration.
how do if existing user will be logged in to the application else it is a new user , Error message showing the user does not exist

**Comment by adarshmishra** [comment]
Hello @ramy1992,

Are you integrating chat within your app or this is your stand alone application only based on our chat backend? 
One way is to check if user exist or not is, call user detail api with admin credentials. If you get user detail in response, user is present in system or else not.

https://www.applozic.com/docs/platform-api-chat.html#user-details
More on admin credetials: 

https://www.applozic.com/docs/platform-api-chat.html#application-admin

**Comment by ramy1992** [comment]
Hello Mr

only based on our chat backend?I just logged on, such as in the application
of Messenger Facebook But in your app if userid not existe in server  app
do singup , What do I do to make them just login without registering a new
user.
Sorry about the prolongation, thanks for helping me and I promise to do my
posting taking with my friends، thanks.
