### ISSUE TITLE
issue while adding fragment in TabView layout

### ISSUE THREAD

**Issue by Amit08071992** [AppLozic/Applozic-Android-SDK#218]
https://docs.google.com/document/d/1-TbJWCUEIzwWGD8mBkV6y2PLrNAIWTmTI6jJuzgC7c4/edit

in this link.

3) Open the ConversationUIService.java classs and
**add this MobiComQuickConversationFragment fragment object** 

but ConversationUIService file is locked i cant edit this file..

**Comment by Sunilkumarr** [comment]
@Amit08071992 Download chat modules from  here https://github.com/AppLozic/Applozic-Android-SDK and import the **mobicomkitui** folder from the downloaded  project then add    `compile project(':mobicomkitui')` in app build.gradle under dependencies and remove the applozic gradle dependency` compile 'com.applozic.communication.uiwidget:mobicomkitui:*.**'` then you can able to edit files

**Comment by gustavofc1997** [comment]
someone has tried to convert conversationactivity to fragment ? i need put the chat in a tabview

**Comment by Sunilkumarr** [comment]
@gustavofc1997  You can follow this doc link [https://docs.google.com/document/d/1-TbJWCUEIzwWGD8mBkV6y2PLrNAIWTmTI6jJuzgC7c4/edit ](https://docs.google.com/document/d/1-TbJWCUEIzwWGD8mBkV6y2PLrNAIWTmTI6jJuzgC7c4/edit  ) for adding the fragment into the tabview activity

**Comment by gustavofc1997** [comment]
ok thanks but i need  a Specific chat in a fragment, so for example a i have an activty and has a tab with three fragments i mean this fragments contains a chat of specific channel. could you help me?

**Comment by pravingaikwad123** [comment]
@Sunilkumarr thanks for the link it worked. But now I am facing one more issue. In my CHATS tabbed fragment I have one Floating action Button that opens MembersList from App Lozic but when I click on any member chat screen doesn't getting opened. Instead that screen disappears and I am redirected back to CHATS tabbed fragment screen.

**Comment by Sunilkumarr** [comment]
@pravingaikwad123 
1)Once you click on button you need to start the activity with result 

  ```
 Intent intentContact = new Intent(this, MobiComKitPeopleActivity.class);
   startActivityForResult(intentContact, ConversationUIService.REQUEST_CODE_CONTACT_GROUP_SELECTION);

```
   2)Paste the code inside the onActivityResult of your activity to handle the click event result 
```

   @Override
   protected void onActivityResult(int requestCode, int resultCode, Intent data) {
       super.onActivityResult(requestCode, resultCode, data);

       if (requestCode == ConversationUIService.REQUEST_CODE_CONTACT_GROUP_SELECTION && resultCode == RESULT_OK) {
           String userId = data.getStringExtra(ConversationUIService.USER_ID);
           Integer groupId = data.getIntExtra(ConversationUIService.GROUP_ID, -1);

           Intent intent = new Intent(this, ConversationActivity.class);
           if (!TextUtils.isEmpty(userId)) {
               intent.putExtra(ConversationUIService.USER_ID, userId);
           }

           if (groupId != null  && groupId != -1) {
               intent.putExtra(ConversationUIService.GROUP_ID, groupId);
           }
           intent.putExtra(ConversationUIService.TAKE_ORDER, true);
           startActivity(intent);
       }
   }
```

Let me know if you face any issue in this

**Comment by pravingaikwad123** [comment]
@Sunilkumarr thanks alot. It worked. Applozic's support is really very good. Thanks alot. Efforts appreciated. :)
