### ISSUE TITLE
Can't delete a contact from the list without it coming back after re-logging in?

### ISSUE THREAD

**Issue by RyanElliott94** [AppLozic/Applozic-Android-SDK#219]
Right for the past couple days I've been trying to get my code to work but nothings working! I'll try to explain the best i can!

The idea of it is to delete a specific contact from the contacts list, now the code i have so far does remove the contact from the list but it doesn't seem to remove that contact from the logged in user and I'm not sure why.

Knowing me I've missed some important bits of code but here's what I've got: 

                             ` final Cursor cursor = mAdapter.getCursor();
                               cursor.moveToPosition(position);
                               contact = contactDatabase.getContact(cursor, "_id");
                               try {
                                   contactService.deleteContact(contact);
                               } catch (Exception e) {
                                   e.printStackTrace();
                               }
                               String sucDel = "Deleted Successfully";
                               Toast toast = Toast.makeText(getActivity(), sucDel, Toast.LENGTH_SHORT);
                               toast.setGravity(Gravity.CENTER, 0, 0);
                               toast.show();
                               getLoaderManager().restartLoader(
                                ContactSelectionFragment.ContactsQuery.QUERY_ID, null,AppContactFragment.this);`

So what am i doing wrong?

**Comment by adarshmishra** [comment]
@SimplisticApps Above code will just remove contacts from local storage of device. It won't sync at other devices. Is it coming again on same logged-in device?

**Comment by SimplisticApps** [comment]
Thought so and yeah it does, so by the sounds of it i need to know how to sync it

**Comment by SimplisticApps** [comment]
I really need to know how to do it because i can't release the app till the feature works

**Comment by adarshmishra** [comment]
@SimplisticApps, You can manage contact population from your end. 
1. Enable setting to show only filtered contacts (contacts from your side) 
```
ApplozicClient.getInstance(LoginActivity.this).enableShowMyContacts();

```
2. Fetch your own contacts and add it via SDK methods. 

inserting contact 
```
AppContactService appContactService = new AppContactService(context);
Contact contact = new Contact();
contact.setUserId("user123");
contact.setFullName("User");
contact.setImageURL("https://raw.githubusercontent.com/AppLozic/Applozic-Android-SDK/master/img/android.png");
contact.setContactType(Short.valueOf("1"));//set this type to 1
contactList.add(contact);

appContactService.addAll(contactList);
```
3. Once contact is deleted by your code mentioned, simply delete it's all conversation of that user.
```
 new DeleteConversationAsyncTask(new MobiComConversationService(context), contact, channel,currentConversationId, context).execute();

```

**Comment by SimplisticApps** [comment]
The code mentions `contactList.add(contact)` but which list am i looking for? an SDK list or my own one?

**Comment by adarshmishra** [comment]
This is your own list, this is just for example to build a list of contacts and add it via SDK methods.

```
appContactService.addAll(contactList);

```

**Comment by SimplisticApps** [comment]
Sorry about these stupid questions but i want to ideally avoid recreating my own list so is there anyway i can use the SDK one? because i can add a contact to the SDK list but it disappears after you log out and log back in again?
