### ISSUE TITLE
Notification when apps in background or not running

### ISSUE THREAD

**Issue by rizabudi** [AppLozic/Applozic-Android-SDK#228]
Hi, i have an issue when my apps not running (it was killed or user swipe it from task manager) push notification will not show. It will show again after i reopen the apps and click refresh from context menu. My device os is android 5.1. 

I think it Firebase Issues. I was check it on internet and another people have similar problem with me. Firebase Cloud Message will not show if application not running.

My question is. Is applozic server (push server service) was handle push notification when apps not running (in background state or killed).  I was check on stackoverflow that there are different fcm payload that must be send to handle different application state. You can check this link.

http://stackoverflow.com/questions/37876257/push-notification-works-incorrectly-when-app-is-on-background-or-not-running/37876727#37876727

**Comment by adarshmishra** [comment]
Hello Riza,

Push notification should work if app is in background or killed. Can you please check what response you are getting on our [notification test page](https://www.applozic.com/docs/push-notification-test.html)?

**Comment by rizabudi** [comment]
hi @adarshmishra, when i test in your notification test page. It show success.
But, is this sample sdk was successfully test on android os 5 and newer ?

if application running, notification will show. But if i killed the apps (i swipe from system tray), push notification will not show.

**Comment by rizabudi** [comment]
HI @adarshmishra, did you read FCM article on this link ?
https://firebase.google.com/docs/cloud-messaging/concept-options

In this sample, application only handle push notification when show in foreground. If application in foreground state, push notification will trigger onMessageReceived in FCMListenerService class. But if application in background or was killed, onMessageReceived method will not trigger anymore.

The solution is, the FCM payload must contain notification tag beside data tag. I just debug this sample apps, with some modification in onMessageReceived like code bellow : 

    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {

        Log.i(TAG,"Message data:"+remoteMessage.getData());

        if(remoteMessage.getData().size()>0){
            if (MobiComPushReceiver.isMobiComPushNotification(remoteMessage.getData())) {
                Log.i(TAG, "Applozic notification processing...");
                MobiComPushReceiver.processMessageAsync(this, remoteMessage.getData());
                //                return;
            }
        }

        // Check if message contains a notification payload.
        if (remoteMessage.getNotification() != null) {
            Log.d(TAG, "Message Notification Body: " + remoteMessage.getNotification());
        }else{
            Log.d(TAG, "Message Notification Body: NULL");
        }

     }

and the log show that notification payload is NULL

04-03 02:46:18.616 6388-6787/com.applozic.mobicomkit.sample I/ApplozicGcmListener: Message data:{APPLOZIC_01=}
04-03 02:46:18.626 6388-6787/com.applozic.mobicomkit.sample I/ApplozicGcmListener: Applozic notification processing...
04-03 02:46:18.636 6388-6787/com.applozic.mobicomkit.sample D/ApplozicGcmListener: Message Notification Body: NULL

So, can you add notification data on FCM payload in your applozic server and update this sample source ? 
For your information, i was have applozic licence and now have 200+ running user. Most of them complaint to me because not receive notification when apps is not running and must reopen apps again.

Thanks before.

**Comment by rizabudi** [comment]
@adarshmishra you can also check this link
http://stackoverflow.com/questions/37554274/open-app-on-firebase-notification-received-fcm

**Comment by adarshmishra** [comment]
@rizabudi ,
FCM Notification messages are used when you want, FCM to show notification automatically. In our case, SDK build notification based on data payload receive,so notification tag is not required. 

Quote from FCM documentation:
 
Notification message : **_FCM automatically displays the message to end-user devices on behalf of the client app. Notification messages have a predefined set of user-visible keys._**

If you are a paid customer, please ping us on premium support chat to check with your notification configuration issue.

-Thanks

**Comment by rizabudi** [comment]
"If you are a paid customer, please ping us on premium support chat to check with your notification configuration issue." i already chat to  "Applozic Premium Support" but is slow respond.

Ok, but why when i run my apps, notification will not show if i kill my apps (i swipe away) like this issue in firebase github ?
https://github.com/firebase/quickstart-android/issues/41

In that issue, some user resolve by add notification payload.

**Comment by rizabudi** [comment]
@adarshmishra you can check, some users resolve this issue with add notification payload like this link https://github.com/firebase/quickstart-android/issues/41#issuecomment-229156196

**Comment by adarshmishra** [comment]
@rizabudi, Notification payload is not required here. Can you please send me Your AndroidManifest over chat? You might have missed meta-data/broadcast entry required for notification to appear.

[Step 2: AndroidManifest changes](https://www.applozic.com/docs/android-chat-sdk.html#step-2-androidmanifest
)

You can check with two entries.
```
 <meta-data android:name="com.package.name" 
           android:value="${applicationId}" /> <!-- NOTE: Do NOT change this, it should remain same i.e 'com.package.name' -->
```
Receiver:
```
<receiver android:name="com.applozic.mobicomkit.uiwidgets.notification.MTNotificationBroadcastReceiver">
         <intent-filter>            
             <action android:name="${applicationId}.send.notification"/>                    
        </intent-filter>           
</receiver>
```

**Comment by rizabudi** [comment]
@adarshmishra, i'm using AndroidManifest.xml on this repo and i'm just running the sample apps from this repo too. Any section on AndroidManifest.xml that should i change ?

https://github.com/AppLozic/Applozic-Android-SDK/blob/master/app/src/main/AndroidManifest.xml

**Comment by hborisov1** [comment]
I have the same problem as @rizabudi but I am using GCM instead of firebase. 
I have configured AndroidManifest properly and the [notifications test page](https://www.applozic.com/docs/push-notification-test.html) shows 'success' status but I still can't receive notifications while the app is killed or swiped out from task manager.

Did you manage to solve the problem?

**Comment by Widiyanto** [comment]
I have the same problem as @rizabudi and @hborisov1, notification not show after kill app

**Comment by razmaimon** [comment]
we have it as well. is there a fix for this?

**Comment by reytum** [comment]
@razmaimon which device are you testing this. If its a device that does not have AOSP, then there would be setting as Autostart for appslications. Enable autostart for your application and test. This is when you have not missed out on anything from Applozic's Push notification setup docs.

**Comment by osama-taha** [comment]
We tested it against:
- Huawei Mate 9 , p10+ 
- Samsung s7, s8
All of the above devices have this issue...

Can you please elaborate, what is the autostart? I can't find this option in our testing devices..

**Comment by ranasadam** [comment]
Got Same issue in my application.

**Comment by reytum** [comment]
@rizabudi @hborisov1 @Widiyanto @razmaimon @osama-taha @ranasadam Please check in the latest version - 5.8.
Here are the release notes: https://github.com/AppLozic/Applozic-Android-SDK/releases/tag/5.8

**Comment by AniruddhaKulk** [comment]
The sample app still has the same issue. Is SDK version updated in sample app?

**Comment by reytum** [comment]
@AniruddhaKulk Are you facing this issue on some specific devices or all devices? If you are facing the issue on all the devices then please check if you haven't changes the applicationID in our sample app.
If you are facing the issue on specific devices please share the devices list.

**Comment by AniruddhaKulk** [comment]
@reytum Happening on all the devices. Did not change the applicationID. If I had changed then I would not have received the notification when app is in the foreground. Correct?
Could you please help me solve this ASAP?

**Comment by reytum** [comment]
@AniruddhaKulk If it happens on all devices it means the push notification setup is not correct. When the app is in foreground the notifications are delivered through MQTT, thats why you receive notifications when the app is in foreground. Please share the userId you are testing with.

**Comment by AniruddhaKulk** [comment]
@reytum the user ids' are 1, sk28, 2. Do you need app id as well?

**Comment by reytum** [comment]
@AniruddhaKulk Yes please share your AppId as well and also the login credentials for the userIds.
Now this is what I was trying to specify earlier, if you have used your App id in the sample app, then you need to do the setup for your Id for push notification. Please refer to this doc for more details : https://docs.applozic.com/docs/android-push-notification

**Comment by apurcaroiu** [comment]
@reytum 
Hi,

I am testing using two Hwaei devices (Oreo) and I did the troubleshooting steps as well.
For me notifications are working fine both when device is in foreground and background, as well after closing the application from task manager.

But it is not working when device goes to standby or doze mode. I am not receiving the notifications and audio video calls. The firebase notification does not seem to trigger in this case.
Are the firebase notifications sent with high priority to handle doze mode and app standby ?

Thanks
Adrian

**Comment by reytum** [comment]
@apurcaroiu The fcm notifications in applozic are sent with high priority. The notifications should also work in doze mode. Could you simulate the doze mode and check if you still face the issue. This will make it clear if there is some other issue or not. Check this commit for more details: https://github.com/AppLozic/Applozic-Android-SDK/commit/8e24917bc3d6f48134c7ad9c7676c4f16084b845#diff-ab5f4ea2fd6f983aebd0df2dd78df21b

**Comment by apurcaroiu** [comment]
@reytum I simulated doze mode by:
          a) adb shell dumpsys deviceidle force-idle
          b) adb shell dumpsys deviceidle enable
          c) adb shell dumpsys battery unplug
Checking with adb shell dumpsys deviceidle get deep returned idle.

So it does not seem to be an issue with the doze mode if my steps were correct.

However not sure what else could cause the issue. Mostly I can reproduce this after couple of hours of inactivity on that particular device. The notification call seems to be delivered in the end to the receiver but after I open the screen, it does not acquire the wake lock right away as it should.

Any thoughts what could cause this and what else I can try ?

Thanks

**Comment by apurcaroiu** [comment]
Just to clarify previous answer, it did work as expected in doze mode.
