### ISSUE TITLE
Getmessages return 0 messages

### ISSUE THREAD

**Issue by klaszlo8207** [AppLozic/Applozic-Android-SDK#229]
```
        String userid = Preferences.INSTANCE.get("id", "");

        Calendar c = Calendar.getInstance();
        c.add(Calendar.DAY_OF_MONTH, -20);

        Long starttime = c.getTimeInMillis();
        Long endtime = System.currentTimeMillis();

        Logger.E("times", starttime, "..",  endtime, "..", userid);

        List<Message> messages = new MobiComConversationService(this).getMessages(userid, starttime, endtime);

        int cnt = messages.size();

        Logger.E("msg cnt",cnt );
```
I need to get all my messages from the server from the last 20 days.
here is my code, I get only "0" :(

**Comment by klaszlo8207** [comment]
it looks like "getLatestMessagesGroupByPeople" is the same

**Comment by Sunilkumarr** [comment]
@klaszlo8207   Your using the method for getting  the receiver user/contact messages  :   
 
To get logged in user latest messages by startTime and endTime use the below method 

`List<Message> messages = new MobiComConversationService(context).getMessages(starttime, endtime, null, null, null);`

To get the logged in users all latest messages  with out startTime and  endTime use below method 

`List<Message> messages = new MobiComConversationService(context).getLatestMessagesGroupByPeople();`

Note : This methods are server calls

**Comment by klaszlo8207** [comment]
Thanks, Any roobust way to get only the last three messages?

**Comment by klaszlo8207** [comment]
sorry, it is wlorking when I eait same seconds before call it.

2000ms maybe
