### ISSUE TITLE
Get user picture or user picture url, or userid from message

### ISSUE THREAD

**Issue by klaszlo8207** [AppLozic/Applozic-Android-SDK#230]
How it is possible?

I can do this:

msg1.getContactIds()

but this is MY userid always.

how can I get the userid who created that message?

OR:

get the user picture url WHO created that message

thanks

**Comment by Sunilkumarr** [comment]
@klaszlo8207   Hi  message.getContactIds(); it will be always returns receiver userId to who your sending a message or from who you received the message 

1)For Getting the image url in chat list Screen : 

          AppContactService appContactService = new AppContactService(context);
            Contact contact =  appContactService.getContactById(message.getContactIds());
           
       if(contact != null ){
                Log.i("contact","Image url "+contact.getImageURL());
            }

2)For Getting the image url in individual chat Screen :

  ```
 AppContactService appContactService = new AppContactService(context);
 if (message.isTypeOutbox()) {
                Contact senderContact = appContactService.getContactById(MobiComUserPreference.getInstance(context).getUserId());
                Log.i("SenderUser","Image url"+senderContact.getImageURL());
            }else {
                Contact receiverContact = appContactService.getContactById(message.getContactIds());
                Log.i("ReceiverContact","Image url"+receiverContact.getImageURL());
   }
```

**Comment by klaszlo8207** [comment]
Thanks, now it is working like a charm!
