### ISSUE TITLE
PLEASE properly format/indent code!

### ISSUE THREAD

**Issue by ivanviragine** [AppLozic/Applozic-Android-SDK#233]
Please, the least you could do is format and indent code properly.
If a developer wants to customize the project, and serious ones will do, it's a nightmare to keep code updated if it's not formatted/indented...

Take MobiComConversationFragment for instance... the code is enormous and very badly formatted...

**Comment by Sunilkumarr** [comment]
Closing this is done in v4.84 https://github.com/AppLozic/Applozic-Android-SDK/commit/c46c455946977ab78697bb8db4cfa69bfa4ff113
