### ISSUE TITLE
Compilation error on 4.83 master

### ISSUE THREAD

**Issue by ivanviragine** [AppLozic/Applozic-Android-SDK#234]
On AppContactFragment class, line 461: 

`holder.contactIcon = (TextView) itemLayout.findViewById(R.id.contactIcon);`

**R.id.contactIcon** doesn't exists.

If you search on github itself for "contactIcon", you'll find only this line of code, but nothing on xml, where it should be declared

https://github.com/AppLozic/Applozic-Android-SDK/search?utf8=%E2%9C%93&q=contactIcon&type=

**Comment by Sunilkumarr** [comment]
@ivanviragine Thank you updated that file

**Comment by ivanviragine** [comment]
Thanks for the quick reply! Got it working now!
