### ISSUE TITLE
Image compression isn't working

### ISSUE THREAD

**Issue by ivanviragine** [AppLozic/Applozic-Android-SDK#235]
Image compression isn't working.
Looking at the code, most of the methods are unused, so it really shouldn't work...

**Comment by RiteshAdulkar** [comment]
@Sunilkumarr Hey, How you guys  doing a video compression. Is there any field which enable or disable compression while sending a recorded video..?

**Comment by Sunilkumarr** [comment]
@RiteshAdulkar Currently settings are not available for video compression, we will think about  adding it

**Comment by Sunilkumarr** [comment]
For image compression you can enable from settings in apploizc-settings.json    
 ``` "enableImageCompression": true ```
