### ISSUE TITLE
Enable Minify 

### ISSUE THREAD

**Issue by ivanviragine** [AppLozic/Applozic-Android-SDK#237]
You should review the minifyEnabled false entries on gradle, since most Android apps should be minified.
When building the latest version (4.83) with minifyEnabled true on my main project, I get a lot of errors keeping me from building.

**Comment by Sunilkumarr** [comment]
@ivanviragine Can you add this in your proguard file let me know if you have any errors ?
```
-dontwarn android.support.v4.**
-keep public class com.google.android.gms.* { public *; }
-dontwarn com.google.android.gms.**

```

**Comment by RiteshAdulkar** [comment]
@Sunilkumarr As mentioned in docs or in above comment, i added proguard rules and make minifyEnabled true in build gradle, but i am getting lots of error.

**Comment by Sunilkumarr** [comment]
@RiteshAdulkar  Can you share the error logs here in text file  ?
