### ISSUE TITLE
Not getting total unread count 

### ISSUE THREAD

**Issue by winpraneeth** [AppLozic/Applozic-Android-SDK#239]

**Comment by Sunilkumarr** [comment]
@winpraneeth  That method need to be used after message list call 

Getting the call back for Initial updating count and updating unread count in real time in your activity you can register the receiver   and update the ui in that receiver 

```

  1)Add this in your activity 
    private BroadcastReceiver unreadCountBroadcastReceiver;

and in onCreate of your activity paste the BroadcastReceiver code 
 
 final MessageDatabaseService messageDatabaseService =  new MessageDatabaseService(this);
        unreadCountBroadcastReceiver = new BroadcastReceiver() {
            @Override
            public void onReceive(Context context, Intent intent) {
                if (MobiComKitConstants.APPLOZIC_UNREAD_COUNT.equals(intent.getAction())) {
                 int unreadCount  =  messageDatabaseService.getTotalUnreadCount();
                    //Update unread count in UI
                }
            }
        };

```

In your activity onResume register Receiver for events 
```
    @Override
    protected void onResume() {
        super.onResume();
        LocalBroadcastManager.getInstance(this).registerReceiver(unreadCountBroadcastReceiver, new IntentFilter(MobiComKitConstants.ACTIVITY_TO_OPEN));
//Here you can get the total unread count and update in ui this is the case after reading the messages in conversation you need to get the current total count  call this and check for count messageDatabaseService.getTotalUnreadCount(); 
    }

```

In your activity onPause unregister Receiver for unread count event 
   ```
@Override
    protected void onPause() {
        if(unreadCountBroadcastReceiver != null){
          LocalBroadcastManager.getInstance(this).unregisterReceiver(unreadCountBroadcastReceiver);
        }
        super.onPause();
    }
```

2)Open the file MobiComConversationService.java in your project and go to the line number 212 in MobiComConversationService.java 

at this line :
 https://github.com/AppLozic/Applozic-Android-SDK/blob/master/mobicomkit/src/main/java/com/applozic/mobicomkit/api/conversation/MobiComConversationService.java#L212

and paste this code there at Line number 212

   ```
      if(channel == null && contact == null){
            Intent intent = new Intent(MobiComKitConstants.APPLOZIC_UNREAD_COUNT);
            LocalBroadcastManager.getInstance(context).sendBroadcast(intent);
        }

```

**Comment by winpraneeth** [comment]
Followed all the steps. But still can't get the unread count. When I debug and see unreadCount=0

**Comment by winpraneeth** [comment]
In my onCreate()

final MessageDatabaseService messageDatabaseService =  new MessageDatabaseService(this);
        unreadCountBroadcastReceiver = new BroadcastReceiver() {
            @Override
            public void onReceive(Context context, Intent intent) {
                if (MobiComKitConstants.APPLOZIC_UNREAD_COUNT.equals(intent.getAction())) {
                    unreadCount  =  messageDatabaseService.getTotalUnreadCount();
                    if(unreadCount != 0) {
                        AppUtils.setMenuCounter(R.id.nav_messages_fragment, unreadCount, navigation_view);
                    }
                }
            }
        };


@Override
    protected void onResume() {
        super.onResume();
        LocalBroadcastManager.getInstance(this).registerReceiver(unreadCountBroadcastReceiver, new IntentFilter(MobiComKitConstants.ACTIVITY_TO_OPEN));
        final MessageDatabaseService messageDatabaseService = new MessageDatabaseService(this);
        int newUnreadCount = messageDatabaseService.getTotalUnreadCount();
        if (newUnreadCount != 0) {
            AppUtils.setMenuCounter(R.id.nav_messages_fragment, newUnreadCount, navigation_view);
        }

//Here you can get the total unread count and update in ui this is the case after reading the messages in conversation you need to get the current total count  call this and check for count messageDatabaseService.getTotalUnreadCount();
    }

**Comment by Sunilkumarr** [comment]
@winpraneeth 
Updated the onResume code check with this 

```
@Override
protected void onResume() {
super.onResume();
LocalBroadcastManager.getInstance(this).registerReceiver(unreadCountBroadcastReceiver, new IntentFilter(MobiComKitConstants.APPLOZIC_UNREAD_COUNT));
final MessageDatabaseService messageDatabaseService = new MessageDatabaseService(this);
int newUnreadCount = messageDatabaseService.getTotalUnreadCount();
if (newUnreadCount != 0) {
AppUtils.setMenuCounter(R.id.nav_messages_fragment, newUnreadCount, navigation_view);
}
```

**Comment by winpraneeth** [comment]
Getting the unread count, but does not update after I read the messages in a conversation.

**Comment by Sunilkumarr** [comment]
@winpraneeth 
In **ConversationReadService.java** file at this below link line number 

https://github.com/AppLozic/Applozic-Android-SDK/blob/master/mobicomkit/src/main/java/com/applozic/mobicomkit/api/conversation/ConversationReadService.java#L34

paste  this below code there in your project it will send the broadcast once user read the conversation if unread count is there   :

```
 if(unreadCount != 0){
    Intent readIntent = new Intent(MobiComKitConstants.APPLOZIC_UNREAD_COUNT);
    LocalBroadcastManager.getInstance(getApplicationContext()).sendBroadcast(readIntent);
   }
```
