### ISSUE TITLE
I'm using context based chat in my android app. When I start a chat I see the context,  but when I close the app and come back and click on a chat I don't see the context

### ISSUE THREAD

**Issue by winpraneeth** [AppLozic/Applozic-Android-SDK#240]
## Code Sample

Applozic Android SDK version: ?

Android device: ?

Android OS version: ?

Dependencies used with version: ?

**Comment by Sunilkumarr** [comment]
@winpraneeth Can you check is this settings is addd  in UserLoginTask onSuccess method
```
1) ApplozicClient.getInstance(context).setContextBasedChat(true);
```

2)When Starting ConversationActivity add CONTEXT_BASED_CHAT flag in intent:

```
Intent intent = new Intent(this, ConversationActivity.class);
intent.putExtra(ConversationUIService.CONTEXT_BASED_CHAT,true);
startActivity(intent);
```

Context based chat doc link : 
https://www.applozic.com/docs/android-chat-sdk.html#context-based-chat

**Comment by winpraneeth** [comment]
Yeah i'm doing both of these in my code

**Comment by Sunilkumarr** [comment]
@winpraneeth can you paste that code how your starting the activity on click of chat

**Comment by winpraneeth** [comment]
Intent intent = new Intent(context, ConversationActivity.class);
                intent.putExtra("takeOrder", true);
                intent.putExtra(ConversationUIService.USER_ID, String.valueOf(property.getUserId()));//RECEIVER USERID
                intent.putExtra(ConversationUIService.DEFAULT_TEXT, "Hey i like your house");
                intent.putExtra(ConversationUIService.CONTEXT_BASED_CHAT, true);
                intent.putExtra(ConversationUIService.CONVERSATION_ID, conversationId);
                intent.putExtra("property_id", property.getId());
                intent.putExtra("userType", 2);
                startActivity(intent);

**Comment by winpraneeth** [comment]
As I said I see the context when I start the chat. Only when I close the app and come back and click on a chat I don't see it.

**Comment by Sunilkumarr** [comment]
@winpraneeth when you close back and come what is the code your using for opening the chat is it same ?

**Comment by winpraneeth** [comment]
case R.id.nav_messages_fragment:
                intent = new Intent(this, ConversationActivity.class);
                intent.putExtra("userType", 2);
                startActivity(intent);
                break;

This was what I was doing earlier.

Added this       intent.putExtra(ConversationUIService.CONTEXT_BASED_CHAT, true);  to the intent. Working fine now.

Thanks for pointing out!
