### ISSUE TITLE
i want to add some new button applozics toolbar how can add this button in android

### ISSUE THREAD

**Issue by gooddayashok** [AppLozic/Applozic-Android-SDK#241]
## Code Sample

Applozic Android SDK version: ?

Android device: ?

Android OS version: ?

Dependencies used with version: ?

**Comment by Sunilkumarr** [comment]
@gooddayashok 
For adding an menu you need to import the chat modules from github link https://github.com/AppLozic/Applozic-Android-SDK
in your build.gradle file in dependencies
 you need to add `compile project(':mobicomkitui')`

1)XML file where you need to add the menu item : 
XML file name : **mobicom_basic_menu_for_normal_message.xml**
github link for that xml file :
https://github.com/AppLozic/Applozic-Android-SDK/blob/master/mobicomkitui/src/main/res/menu/mobicom_basic_menu_for_normal_message.xml

2)**ConversationActivity.java** file which is in module **mobicomkitui-->com.applozic.mobicomkit.uiwidgets.conversation.activity**

You need to access that menu item in  onOptionsItemSelected(MenuItem item) 
Github link for line of that method :
https://github.com/AppLozic/Applozic-Android-SDK/blob/master/mobicomkitui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/activity/ConversationActivity.java#L648
