### ISSUE TITLE
Cannot get Contact List in Contacts

### ISSUE THREAD

**Issue by mynameisjimmy91123** [AppLozic/Applozic-Android-SDK#242]
## Goals

I am using Applozic SDK from gradle and then it doesn't gives any contact list though it is showing in iPhone.

## Expected Results

I want to get Contact List when I click the + button or add member in the group in the actionbar
## Code Sample

This is the code that after login into Applozic process
  Applozic.getInstance(getActivity()).init(getActivity(), "bearandfox2b20872217c93185b1fdd51ebeb9eee2e");
        User user = new User();
        user.setUserId(AppData.UserID); //userId it can be any unique user identifier
        user.setDisplayName(AppData.UserName); 
        user.setPassword(AppData.UserToken); //optional, leave it blank for testing purpose, read this if you want to add additional security by verifying password from your server https://www.applozic.com/docs/configuration.html#access-token-url
        user.setImageLink(AppData.UserAvatar);//optional,pass your image link
        new UserLoginTask(user, taskListener, getActivity()).execute((Void) null);

This is the code that goes to the Conversation page from my app.
Intent mIntent = new Intent(getActivity(), ConversationActivity.class);
startActivity(mIntent);

Applozic Android SDK version: ?

Android device: ? Google Nexus 4

Android OS version: ? 5.0.0

Dependencies used with version: ? yes

**Comment by Sunilkumarr** [comment]
@mynameisjimmy91123 You need to add json file in your project for adding json file you can check this  link https://www.applozic.com/docs/android-chat-sdk.html#customization after adding applozic-settings.json file in your project find the  **registeredUserContactListCall**   in  applozic-settings.json file and make that to true i.e   **"registeredUserContactListCall": true**
