### ISSUE TITLE
Getting the position of recent conversation in the conversation list of context based chat

### ISSUE THREAD

**Issue by winpraneeth** [AppLozic/Applozic-Android-SDK#245]
Say I have a Conversation with context based chat enabled and it's conversationList contains 'n' conversations. And the recent conversation that I had is position 3 in the list.  How to get this position value in MobiComConversationFragment.java?

**Comment by winpraneeth** [comment]
Got the answer

**Comment by poojabokdia** [comment]
how did you do that ?
