### ISSUE TITLE
Unable to change FAB button color.

### ISSUE THREAD

**Issue by jeelanb** [AppLozic/Applozic-Android-SDK#246]
## Goals
Unable to change FAB button color from provided Json file.

## Expected Results
FAB button color should be changed to any color and it should pick from provided Json file.

## Actual Results
FAB button color is not changed.

## Steps to Reproduce
1. In applozic-Settings.json file change the below key[startNewFloatingButton] value to "true". 
ex :"startNewFloatingButton": true
2.Start Applozic screen.
3.FAB button at right bottom is not displayed in expected color.

We tried to fix this but unable to figure out the exact value of key which need to be update.

## Code Sample
"startNewFloatingButton": false
 

Applozic Android SDK version: ?4.78

Android device: ?Samsung Galaxy S4

Android OS version: ?5.1.0

Dependencies used with version: ?

**Comment by devashishmamgain** [comment]
@jeelanb have you tried fresh install after changing the values?

**Comment by jeelanb** [comment]
@devashishmamgain . i was't sure which key value has to modify to change the color of Add FAB button i read the document and tried by changing few values of keys.For every change i have installed new apk on device to test. But color of FAB button didn't change.
So can please let us know exact key which has to modify to change the color.

Please find the screen shot for reference. 
![screenshot_2017-05-15-13-27-43](https://cloud.githubusercontent.com/assets/21078855/26400354/34257a3c-409e-11e7-94bf-2287205b2fc7.png)

**Comment by Sunilkumarr** [comment]
@jeelanb  startNewFloatingButton  the color settings is not available now if your using  compile 'com.applozic.communication.uiwidget:mobicomkitui:4.78' ,for this you need to import the chat modules from github sample project 

In this file circle.xml
At this line below link  in your project  change the color of that fab startNewFloatingButton
 
https://github.com/AppLozic/Applozic-Android-SDK/blob/master/mobicomkitui/src/main/res/drawable/circle.xml#L6-L7

and xml file for the startNewFloatingButton is mobicom_message_list.xml

https://github.com/AppLozic/Applozic-Android-SDK/blob/master/mobicomkitui/src/main/res/layout/mobicom_message_list.xml#L58

**Comment by jeelanb** [comment]
Thanks for your response. Will look into it.
