### ISSUE TITLE
Is something missing in  ProGuard Setup ?

### ISSUE THREAD

**Issue by ayaz-health** [AppLozic/Applozic-Android-SDK#247]
Debug APK was working fine In Release  Apk I found below issue 
 java.lang.ClassNotFoundException: Didn't find class "org.webrtc.AudioTrack" on path: DexPathList[[zip file "/data/app/com.hs.userportal-1/base.apk"],nativeLibraryDirectories=[/data/app/com.hs.userportal-1/lib/arm64, /data/app/com.hs.userportal-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]

I solved this adding this line -keep class org.webrtc.** { *; }

after that I found next proguard  issue which is solved by adding this line -keep class com.twilio.** { *; }
[crashLogOnTappingAudioCallButton.txt](https://github.com/AppLozic/Applozic-Android-SDK/files/1028323/crashLogOnTappingAudioCallButton.txt)

**Comment by Sunilkumarr** [comment]
@ayaz-health Thank you for  that proguard  config rules and  added some other rules for audio video sdk you can check this if its added in your proGuard config  file 

 
```
 #keep json classes                
 -keepclassmembernames class * extends com.applozic.mobicommons.json.JsonMarker {
 	!static !transient <fields>;
 }

 -keepclassmembernames class * extends com.applozic.mobicommons.json.JsonParcelableMarker {
 	!static !transient <fields>;
 }
#GSON Config
-keepattributes Signature
-keep class sun.misc.Unsafe { *; }
-keep class com.google.gson.examples.android.model.** { *; }
-keep class org.eclipse.paho.client.mqttv3.logging.JSR47Logger { *; }
-keep class android.support.** { *; }
-keep interface android.support.** { *; }
-keep class org.webrtc.** { *; }
-keep class com.twilio.video.** { *; }
-keep class com.twilio.common.** { *; }
-dontwarn android.support.v4.**
-keep public class com.google.android.gms.* { public *; }
-dontwarn com.google.android.gms.**
-keep class com.google.gson.** { *; }
-kepp class com.applozic.audiovideo.authentication.** { *; }
 ```
