### ISSUE TITLE
Only members of particular event has to display in registered user contact list page.

### ISSUE THREAD

**Issue by jeelanb** [AppLozic/Applozic-Android-SDK#248]
## Goals
In single app we have many events in which all registered members may not be part of that event

## Expected Results
Only memebers of particular event has to display in registered user contact list page.

## Actual Results
All applozic chat app registered members are displayed in list who are not part that event.
Current implementation is app level not event level.

## Steps to Reproduce
1. Launch Moozup application app.
2. From Side/Navigation Menu select "Directory".
3. List of members will be displayed who are part of that event.
4. Launch applozic chat screen -> launch registered contact list screen.
   only members who are in "Directory" has to display.
5. Now go to All Events from Side/Navigation Menu --> choose any other event from the list.
6. Again go to "Directory" from Side/Navigation Menu.
7. List of members will be displayed who are part of that selected event.
8. Now launch applozic chat screen -> launch registered contact list screen.
Defective Scenario :
9. Members who are not part of this event also displayed in chat contact list.
   But expected behaviour is members who are part of the selected event has to display.

## Code Sample
NA

## Proposed Solution :
We will pass one unique id i.e "event id" on applozic registration process which 
helps you to differentiate contacts who are part of the selected event are not.
Please let us know how to proceed further.

## Other Details :
Applozic Android SDK version: ?4.78
Android device: ?Samsung Galaxy S4
Android OS version: ?5.1.0
Dependencies used with version:

**Comment by devashishmamgain** [comment]
@jeelanb using the contact methods you can populate your own contact list.
https://www.applozic.com/docs/android-chat-sdk.html#contacts

Can you try with the following approach:
On change of event:
- Delete all old contacts
- Add all members of the selected Event using https://www.applozic.com/docs/android-chat-sdk.html#contacts

**Comment by jeelanb** [comment]
Hi Team,
    We tried above solution as mentioned in the document we were able to add and populate contacts of particular event.

Facing Issues : 
1. There was delay while adding contacts to local DB 
2. On switching of event we need to delete all contacts and need add again on selection of other event.

Expectation : 
1. In particular event only registered members of that event has to display in chat contacts page.
2. To differentiate the member of particular event can be achieved using "EventId" but primary key i.e 
   UserId/PersonId we can't use to differentiate because one person may part of multiple events.
3. We need a field i.e "EventId" in your DB which has to be added on registration process.

Please let us know if anything is unclear and let us know how to proceed further.

BR,
Jeelan

**Comment by jeelanb** [comment]
Hi Team,
    Gentle remainder.
please let us know any if anything is unclear or if you have solutions please share the respective data  to proceed further.

BR,
Jeelan
