### ISSUE TITLE
can i allow my users to choose custom ring tones when they are called via my app ie. the ring

### ISSUE THREAD

**Issue by ecoachlabs** [AppLozic/Applozic-Android-SDK#249]
## Code Sample

Applozic Android SDK version: ?

Android device: ?

Android OS version: ?

Dependencies used with version: ?

**Comment by Sunilkumarr** [comment]
@ecoachlabs  Yes you can at this line once user selects  the custom ringtone from your app then store that URI in shared preferences  and access that URI at line number 71 

Parse URI  : `Uri notification = Uri.parse("your ringtone uri");`

Code link for to change and pass the custom ringtone : https://github.com/AppLozic/Applozic-Android-Chat-Sample/blob/master/Applozic-Android-AV-Sample/audiovideo/src/main/java/com/applozic/audiovideo/activity/CallActivity.java#L71
