### ISSUE TITLE
App is getting crash when we logout from app and messages coming from other app or web plugin.

### ISSUE THREAD

**Issue by priyadarshi** [AppLozic/Applozic-Android-SDK#25]
App is getting crash when we logout from app and messages coming from other app or web plugin.

Step to reproduce:
1)Login to app
2)Send message from other user
3)logout from the app while receiving the notification
4)click on notification then app is getting crash

**Comment by adarshmishra** [comment]
@priyadarshi 
please test and close with the new build.

**Comment by priyadarshi** [comment]
If we send multiple messages simultaneously then we are notification even afterlogout .

**Comment by priyadarshi** [comment]
Verified. Now it is working fine.
