### ISSUE TITLE
Memory leak with ConversationActivity

### ISSUE THREAD

**Issue by Amagi82** [AppLozic/Applozic-Android-SDK#250]
I just finished setting up the SDK as specified in your docs, and I'm running into the following memory leak. I haven't found a specific way to reliably trigger it; it seems to happen randomly, but I'll keep you posted if I do. 

? D/LeakCanary: * com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity has leaked:
? D/LeakCanary: * GC ROOT thread java.lang.Thread.<Java Local> (named 'Thread-13')
? D/LeakCanary: * references com.applozic.mobicomkit.uiwidgets.conversation.fragment.MobiComQuickConversationFragment$1.this$0 (anonymous implementation of java.lang.Runnable)
? D/LeakCanary: * references com.applozic.mobicomkit.uiwidgets.conversation.fragment.MobiComQuickConversationFragment.conversationAdapter
? D/LeakCanary: * references com.applozic.mobicomkit.uiwidgets.conversation.adapter.QuickConversationAdapter.context
? D/LeakCanary: * leaks com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity instance
? D/LeakCanary: * Retaining: 9.2 KB.
? D/LeakCanary: * Reference Key: 43f7df39-1b23-4246-8bab-63fdf893e467
? D/LeakCanary: * Device: motorola google Nexus 6 shamu
? D/LeakCanary: * Android Version: 7.1.1 API: 25 LeakCanary: 1.5.1 1be44b3
? D/LeakCanary: * Durations: watch=5015ms, gc=149ms, heap dump=6942ms, analysis=95470ms
? D/LeakCanary: * Details:
? D/LeakCanary: * Instance of java.lang.Thread
? D/LeakCanary: |   static MIN_PRIORITY = 1
? D/LeakCanary: |   static threadSeqNumber = 2615
? D/LeakCanary: |   static SUBCLASS_IMPLEMENTATION_PERMISSION = java.lang.RuntimePermission@1883713552 (0x70473010)
? D/LeakCanary: |   static EMPTY_STACK_TRACE = java.lang.StackTraceElement[0]@1883713536 (0x70473000)
? D/LeakCanary: |   static defaultUncaughtExceptionHandler = com.google.android.gms.internal.zzbnr@315742544 (0x12d1d950)
? D/LeakCanary: |   static MAX_PRIORITY = 10
? D/LeakCanary: |   static NANOS_PER_MILLI = 1000000
? D/LeakCanary: |   static $classOverhead = byte[224]@1883715401 (0x70473749)
? D/LeakCanary: |   static NORM_PRIORITY = 5
? D/LeakCanary: |   static threadInitNumber = 19
? D/LeakCanary: |   blocker = null
? D/LeakCanary: |   blockerLock = java.lang.Object@314893208 (0x12c4e398)
? D/LeakCanary: |   contextClassLoader = dalvik.system.PathClassLoader@314862752 (0x12c46ca0)
? D/LeakCanary: |   daemon = false
? D/LeakCanary: |   eetop = 0
? D/LeakCanary: |   group = java.lang.ThreadGroup@1883713368 (0x70472f58)
? D/LeakCanary: |   inheritableThreadLocals = null
? D/LeakCanary: |   inheritedAccessControlContext = java.security.AccessControlContext@314893184 (0x12c4e380)
? D/LeakCanary: |   lock = java.lang.Object@314893216 (0x12c4e3a0)
? D/LeakCanary: |   name = java.lang.String@321339072 (0x13273ec0)
? D/LeakCanary: |   nativeParkEventPointer = 0
? D/LeakCanary: |   nativePeer = 2251750400
? D/LeakCanary: |   parkBlocker = null
? D/LeakCanary: |   parkState = 1
? D/LeakCanary: |   priority = 10
? D/LeakCanary: |   single_step = false
? D/LeakCanary: |   stackSize = 0
? D/LeakCanary: |   started = true
? D/LeakCanary: |   stillborn = false
? D/LeakCanary: |   target = com.applozic.mobicomkit.uiwidgets.conversation.fragment.MobiComQuickConversationFragment$1@317163264 (0x12e78700)
? D/LeakCanary: |   threadLocalRandomProbe = 0
? D/LeakCanary: |   threadLocalRandomSecondarySeed = 0
? D/LeakCanary: |   threadLocalRandomSeed = 0
? D/LeakCanary: |   threadLocals = java.lang.ThreadLocal$ThreadLocalMap@321433384 (0x1328af28)
? D/LeakCanary: |   threadQ = null
? D/LeakCanary: |   threadStatus = 0
? D/LeakCanary: |   tid = 2589
? D/LeakCanary: |   uncaughtExceptionHandler = null
? D/LeakCanary: |   shadow$_klass_ = java.lang.Thread
? D/LeakCanary: |   shadow$_monitor_ = 0
? D/LeakCanary: * Instance of com.applozic.mobicomkit.uiwidgets.conversation.fragment.MobiComQuickConversationFragment$1
? D/LeakCanary: |   static $classOverhead = byte[56]@321546945 (0x132a6ac1)
? D/LeakCanary: |   this$0 = com.applozic.mobicomkit.uiwidgets.conversation.fragment.MobiComQuickConversationFragment@318033696 (0x12f4cf20)
? D/LeakCanary: |   shadow$_klass_ = com.applozic.mobicomkit.uiwidgets.conversation.fragment.MobiComQuickConversationFragment$1
? D/LeakCanary: |   shadow$_monitor_ = 0
? D/LeakCanary: * Instance of com.applozic.mobicomkit.uiwidgets.conversation.fragment.MobiComQuickConversationFragment
? D/LeakCanary: |   static $classOverhead = byte[688]@319888385 (0x13111c01)
? D/LeakCanary: |   alCustomizationSettings = com.applozic.mobicomkit.uiwidgets.AlCustomizationSettings@318585312 (0x12fd39e0)
? D/LeakCanary: |   baseContactService = com.applozic.mobicomkit.contact.AppContactService@321375368 (0x1327cc88)
? D/LeakCanary: |   conversationAdapter = com.applozic.mobicomkit.uiwidgets.conversation.adapter.QuickConversationAdapter@318540944 (0x12fc8c90)
? D/LeakCanary: |   conversationUIService = com.applozic.mobicomkit.uiwidgets.conversation.ConversationUIService@320417568 (0x13192f20)
? D/LeakCanary: |   currentPage = 1
? D/LeakCanary: |   downloadConversation = com.applozic.mobicomkit.uiwidgets.conversation.fragment.MobiComQuickConversationFragment$DownloadConversation@314723712 (0x12c24d80)
? D/LeakCanary: |   emptyTextView = android.support.v7.widget.AppCompatTextView@320079872 (0x13140800)
? D/LeakCanary: |   fabButton = android.support.v7.widget.AppCompatImageButton@320078848 (0x13140400)
? D/LeakCanary: |   latestMessageForEachContact = java.util.HashMap@321335552 (0x13273100)
? D/LeakCanary: |   listIndex = 0
? D/LeakCanary: |   listView = com.applozic.mobicomkit.uiwidgets.conversation.ConversationListView@317843456 (0x12f1e800)
? D/LeakCanary: |   loadMore = false
? D/LeakCanary: |   loading = true
? D/LeakCanary: |   messageDatabaseService = com.applozic.mobicomkit.api.conversation.database.MessageDatabaseService@321375320 (0x1327cc58)
? D/LeakCanary: |   messageList = java.util.ArrayList@318713208 (0x12ff2d78)
? D/LeakCanary: |   minCreatedAtTime = null
? D/LeakCanary: |   previousTotalItemCount = 1
? D/LeakCanary: |   progressBar = android.widget.ProgressBar@319990784 (0x1312ac00)
? D/LeakCanary: |   searchString = null
? D/LeakCanary: |   startingPageIndex = 0
? D/LeakCanary: |   swipeLayout = android.support.v4.widget.SwipeRefreshLayout@320044032 (0x13137c00)
? D/LeakCanary: |   syncCallService = com.applozic.mobicomkit.api.conversation.SyncCallService@321336672 (0x13273560)
? D/LeakCanary: |   toolbar = android.support.v7.widget.Toolbar@318170112 (0x12f6e400)
? D/LeakCanary: |   visibleThreshold = 5
? D/LeakCanary: |   mAdded = false
? D/LeakCanary: |   mAnimationInfo = null
? D/LeakCanary: |   mArguments = null
? D/LeakCanary: |   mBackStackNesting = 0
? D/LeakCanary: |   mCalled = true
? D/LeakCanary: |   mCheckedForLoaderManager = false
? D/LeakCanary: |   mChildFragmentManager = null
? D/LeakCanary: |   mChildNonConfig = null
? D/LeakCanary: |   mContainer = null
? D/LeakCanary: |   mContainerId = 0
? D/LeakCanary: |   mDeferStart = false
? D/LeakCanary: |   mDetached = false
? D/LeakCanary: |   mFragmentId = 0
? D/LeakCanary: |   mFragmentManager = null
? D/LeakCanary: |   mFromLayout = false
? D/LeakCanary: |   mHasMenu = true
? D/LeakCanary: |   mHidden = false
? D/LeakCanary: |   mHiddenChanged = false
? D/LeakCanary: |   mHost = null
? D/LeakCanary: |   mInLayout = false
? D/LeakCanary: |   mIndex = -1
? D/LeakCanary: |   mInnerView = null
? D/LeakCanary: |   mIsNewlyAdded = false
? D/LeakCanary: |   mLoaderManager = null
? D/LeakCanary: |   mLoadersStarted = false
? D/LeakCanary: |   mMenuVisible = true
? D/LeakCanary: |   mParentFragment = null
? D/LeakCanary: |   mPostponedAlpha = 0.0
? D/LeakCanary: |   mRemoving = false
? D/LeakCanary: |   mRestored = false
? D/LeakCanary: |   mRetainInstance = false
? D/LeakCanary: |   mRetaining = false
? D/LeakCanary: |   mSavedFragmentState = null
? D/LeakCanary: |   mSavedViewState = null
? D/LeakCanary: |   mState = 0
? D/LeakCanary: |   mTag = null
? D/LeakCanary: |   mTarget = null
? D/LeakCanary: |   mTargetIndex = -1
? D/LeakCanary: |   mTargetRequestCode = 0
? D/LeakCanary: |   mUserVisibleHint = true
? D/LeakCanary: |   mView = null
? D/LeakCanary: |   mWho = null
? D/LeakCanary: |   shadow$_klass_ = com.applozic.mobicomkit.uiwidgets.conversation.fragment.MobiComQuickConversationFragment
? D/LeakCanary: |   shadow$_monitor_ = 0
? D/LeakCanary: * Instance of com.applozic.mobicomkit.uiwidgets.conversation.adapter.QuickConversationAdapter
? D/LeakCanary: |   static messageTypeColorMap = java.util.HashMap@321337032 (0x132736c8)
? D/LeakCanary: |   static $classOverhead = byte[132]@315058865 (0x12c76ab1)
? D/LeakCanary: |   alCustomizationSettings = com.applozic.mobicomkit.uiwidgets.AlCustomizationSettings@318585312 (0x12fd39e0)
? D/LeakCanary: |   alphabeticTextView = null
? D/LeakCanary: |   attachmentIcon = null
? D/LeakCanary: |   channelImageLoader = com.applozic.mobicomkit.uiwidgets.conversation.adapter.QuickConversationAdapter$2@321337152 (0x13273740)
? D/LeakCanary: |   contactImage = null
? D/LeakCanary: |   contactImageLoader = com.applozic.mobicomkit.uiwidgets.conversation.adapter.QuickConversationAdapter$1@321337072 (0x132736f0)
? D/LeakCanary: |   contactService = com.applozic.mobicomkit.contact.AppContactService@320697584 (0x131d74f0)
? D/LeakCanary: |   context = com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity@319841664 (0x13106580)
? D/LeakCanary: |   deviceTimeOffset = 0
? D/LeakCanary: |   emojiconHandler = null
? D/LeakCanary: |   highlightTextSpan = android.text.style.TextAppearanceSpan@320417600 (0x13192f40)
? D/LeakCanary: |   mAlphabetIndexer = android.widget.AlphabetIndexer@321337192 (0x13273768)
? D/LeakCanary: |   messageDatabaseService = com.applozic.mobicomkit.api.conversation.database.MessageDatabaseService@320697704 (0x131d7568)
? D/LeakCanary: |   messageList = java.util.ArrayList@318713208 (0x12ff2d78)
? D/LeakCanary: |   messageTextView = null
? D/LeakCanary: |   originalList = null
? D/LeakCanary: |   searchString = null
? D/LeakCanary: |   mDataSetObservable = android.database.DataSetObservable@316270464 (0x12d9e780)
? D/LeakCanary: |   shadow$_klass_ = com.applozic.mobicomkit.uiwidgets.conversation.adapter.QuickConversationAdapter
? D/LeakCanary: |   shadow$_monitor_ = 0
? D/LeakCanary: * Instance of com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity
? D/LeakCanary: |   static $classOverhead = byte[2152]@321462273 (0x13292001)
? D/LeakCanary: |   static retry = 0
? D/LeakCanary: |   static inviteMessage = null
? D/LeakCanary: |   static capturedImageUri = null
? D/LeakCanary: |   accountStatusAsyncTask = null
? D/LeakCanary: |   activityToOpenOnClickOfCallButton = null
? D/LeakCanary: |   alCustomizationSettings = com.applozic.mobicomkit.uiwidgets.AlCustomizationSettings@318030784 (0x12f4c3c0)
? D/LeakCanary: |   applozicPermission = com.applozic.mobicomkit.uiwidgets.instruction.ApplozicPermissions@316192720 (0x12d8b7d0)
? D/LeakCanary: |   baseContactService = com.applozic.mobicomkit.contact.AppContactService@318712680 (0x12ff2b68)
? D/LeakCanary: |   channel = null
? D/LeakCanary: |   childFragmentLayout = android.widget.RelativeLayout@319699968 (0x130e3c00)
? D/LeakCanary: |   connectivityReceiver = com.applozic.mobicomkit.broadcast.ConnectivityReceiver@318713232 (0x12ff2d90)
? D/LeakCanary: |   contact = null
? D/LeakCanary: |   conversation = null
? D/LeakCanary: |   conversationUIService = com.applozic.mobicomkit.uiwidgets.conversation.ConversationUIService@320288192 (0x131735c0)
? D/LeakCanary: |   currentConversationId = null
? D/LeakCanary: |   geoApiKey = java.lang.String@317054112 (0x12e5dca0)
? D/LeakCanary: |   googleApiClient = com.google.android.gms.internal.zzaat@317471760 (0x12ec3c10)
? D/LeakCanary: |   imageUri = null
? D/LeakCanary: |   isAttachment = false
? D/LeakCanary: |   isTakePhoto = false
? D/LeakCanary: |   layout = android.widget.LinearLayout@319697920 (0x130e3400)
? D/LeakCanary: |   locationRequest = null
? D/LeakCanary: |   mActionBar = android.support.v7.app.ToolbarActionBar@321291096 (0x13268358)
? D/LeakCanary: |   mediaFile = null
? D/LeakCanary: |   mobiComKitBroadcastReceiver = com.applozic.mobicomkit.uiwidgets.conversation.MobiComKitBroadcastReceiver@321375080 (0x1327cb68)
? D/LeakCanary: |   mobiComMessageService = com.applozic.mobicomkit.api.conversation.MobiComMessageService@321326704 (0x13270e70)
? D/LeakCanary: |   profilePhotoFile = null
? D/LeakCanary: |   profilefragment = com.applozic.mobicomkit.uiwidgets.people.fragment.ProfileFragment@315233184 (0x12ca13a0)
? D/LeakCanary: |   quickConversationFragment = com.applozic.mobicomkit.uiwidgets.conversation.fragment.MobiComQuickConversationFragment@318033696 (0x12f4cf20)
? D/LeakCanary: |   resourceId = 0
? D/LeakCanary: |   searchListFragment = com.applozic.mobicomkit.uiwidgets.conversation.fragment.MobiComQuickConversationFragment@318033696 (0x12f4cf20)
? D/LeakCanary: |   searchTerm = null
? D/LeakCanary: |   searchView = android.support.v7.widget.SearchView@320168960 (0x13156400)
? D/LeakCanary: |   snackbar = null
? D/LeakCanary: |   videoFileUri = null
? D/LeakCanary: |   mDelegate = android.support.v7.app.AppCompatDelegateImplN@315116560 (0x12c84c10)
? D/LeakCanary: |   mEatKeyUpEvent = false
? D/LeakCanary: |   mResources = null
? D/LeakCanary: |   mThemeId = 2131427330
? D/LeakCanary: |   mCreated = true
? D/LeakCanary: |   mFragments = android.support.v4.app.FragmentController@315247568 (0x12ca4bd0)
? D/LeakCanary: |   mHandler = android.support.v4.app.FragmentActivity$1@318692832 (0x12fedde0)
? D/LeakCanary: |   mNextCandidateRequestIndex = 0
? D/LeakCanary: |   mOptionsMenuInvalidated = false
? D/LeakCanary: |   mPendingFragmentActivityResults = android.support.v4.util.SparseArrayCompat@318493576 (0x12fbd388)
? D/LeakCanary: |   mReallyStopped = true
? D/LeakCanary: |   mRequestedPermissionsFromFragment = false
? D/LeakCanary: |   mResumed = false
? D/LeakCanary: |   mRetaining = false
? D/LeakCanary: |   mStopped = true
? D/LeakCanary: |   mStartedActivityFromFragment = false
? D/LeakCanary: |   mStartedIntentSenderFromFragment = false
? D/LeakCanary: |   mExtraDataMap = android.support.v4.util.SimpleArrayMap@317427664 (0x12eb8fd0)
? D/LeakCanary: |   mActionBar = null
? D/LeakCanary: |   mActionModeTypeStarting = 0
? D/LeakCanary: |   mActivityInfo = android.content.pm.ActivityInfo@315043552 (0x12c72ee0)
? D/LeakCanary: |   mActivityTransitionState = android.app.ActivityTransitionState@316133152 (0x12d7cf20)
? D/LeakCanary: |   mApplication = <Package name>.App@314932128 (0x12c57ba0)
? D/LeakCanary: |   mCalled = true
? D/LeakCanary: |   mChangeCanvasToTranslucent = false
? D/LeakCanary: |   mChangingConfigurations = false
? D/LeakCanary: |   mComponent = android.content.ComponentName@315777008 (0x12d25ff0)
? D/LeakCanary: |   mConfigChangeFlags = 0
? D/LeakCanary: |   mCurrentConfig = android.content.res.Configuration@315131040 (0x12c884a0)
? D/LeakCanary: |   mDecor = null
? D/LeakCanary: |   mDefaultKeyMode = 0
? D/LeakCanary: |   mDefaultKeySsb = null
? D/LeakCanary: |   mDestroyed = true
? D/LeakCanary: |   mDoReportFullyDrawn = false
? D/LeakCanary: |   mEatKeyUpEvent = false
? D/LeakCanary: |   mEmbeddedID = null
? D/LeakCanary: |   mEnableDefaultActionBarUp = true
? D/LeakCanary: |   mEnterTransitionListener = android.app.SharedElementCallback$1@1887798472 (0x708584c8)
? D/LeakCanary: |   mExitTransitionListener = android.app.SharedElementCallback$1@1887798472 (0x708584c8)
? D/LeakCanary: |   mFinished = true
? D/LeakCanary: |   mFragments = android.app.FragmentController@315247696 (0x12ca4c50)
? D/LeakCanary: |   mHandler = android.os.Handler@318692448 (0x12fedc60)
? D/LeakCanary: |   mHasCurrentPermissionsRequest = false
? D/LeakCanary: |   mIdent = 148925151
? D/LeakCanary: |   mInstanceTracker = android.os.StrictMode$InstanceTracker@315247664 (0x12ca4c30)
? D/LeakCanary: |   mInstrumentation = android.app.Instrumentation@314918512 (0x12c54670)
? D/LeakCanary: |   mIntent = android.content.Intent@316440016 (0x12dc7dd0)
? D/LeakCanary: |   mLastNonConfigurationInstances = null
? D/LeakCanary: |   mMainThread = android.app.ActivityThread@314925312 (0x12c56100)
? D/LeakCanary: |   mManagedCursors = java.util.ArrayList@317427616 (0x12eb8fa0)
? D/LeakCanary: |   mManagedDialogs = null
? D/LeakCanary: |   mMenuInflater = null
? D/LeakCanary: |   mParent = null
? D/LeakCanary: |   mReferrer = java.lang.String@314716976 (0x12c23330)
? D/LeakCanary: |   mResultCode = 0
? D/LeakCanary: |   mResultData = null
? D/LeakCanary: |   mResumed = false
? D/LeakCanary: |   mSearchEvent = null
? D/LeakCanary: |   mSearchManager = null
? D/LeakCanary: |   mStartedActivity = false
? D/LeakCanary: |   mStopped = true
? D/LeakCanary: |   mTaskDescription = android.app.ActivityManager$TaskDescription@318692544 (0x12fedcc0)
? D/LeakCanary: |   mTemporaryPause = false
? D/LeakCanary: |   mTitle = java.lang.String@315244264 (0x12ca3ee8)
? D/LeakCanary: |   mTitleColor = 0
? D/LeakCanary: |   mTitleReady = true
? D/LeakCanary: |   mToken = android.os.BinderProxy@318659072 (0x12fe5a00)
? D/LeakCanary: |   mTranslucentCallback = null
? D/LeakCanary: |   mUiThread = java.lang.Thread@1957320208 (0x74aa5610)
? D/LeakCanary: |   mVisibleBehind = false
? D/LeakCanary: |   mVisibleFromClient = true
? D/LeakCanary: |   mVisibleFromServer = true
? D/LeakCanary: |   mVoiceInteractor = null
? D/LeakCanary: |   mWindow = com.android.internal.policy.PhoneWindow@315065952 (0x12c78660)
? D/LeakCanary: |   mWindowAdded = true
? D/LeakCanary: |   mWindowManager = android.view.WindowManagerImpl@318493120 (0x12fbd1c0)
? D/LeakCanary: |   mInflater = com.android.internal.policy.PhoneLayoutInflater@317104624 (0x12e6a1f0)
? D/LeakCanary: |   mOverrideConfiguration = null
? D/LeakCanary: |   mResources = android.content.res.Resources@317275400 (0x12e93d08)
? D/LeakCanary: |   mTheme = android.content.res.Resources$Theme@316102688 (0x12d75820)
? D/LeakCanary: |   mThemeResource = 2131427330
? D/LeakCanary: |   mBase = android.app.ContextImpl@316562896 (0x12de5dd0)
? D/LeakCanary: |   shadow$_klass_ = com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity
? D/LeakCanary: |   shadow$_monitor_ = 1246740817
? D/LeakCanary: * Excluded Refs:
? D/LeakCanary: | Field: android.view.textservice.SpellCheckerSession$1.this$0
? D/LeakCanary: | Field: android.view.Choreographer$FrameDisplayEventReceiver.mMessageQueue (always)
? D/LeakCanary: | Thread:FinalizerWatchdogDaemon (always)
? D/LeakCanary: | Thread:main (always)
? D/LeakCanary: | Thread:LeakCanary-Heap-Dump (always)
? D/LeakCanary: | Class:java.lang.ref.WeakReference (always)
? D/LeakCanary: | Class:java.lang.ref.SoftReference (always)
? D/LeakCanary: | Class:java.lang.ref.PhantomReference (always)
? D/LeakCanary: | Class:java.lang.ref.Finalizer (always)
? D/LeakCanary: | Class:java.lang.ref.FinalizerReference (always)

**Comment by Sunilkumarr** [comment]
@Amagi82 Thanks for the logs we will check and add the fix in next releases
