### ISSUE TITLE
Getting Sender user id

### ISSUE THREAD

**Issue by winpraneeth** [AppLozic/Applozic-Android-SDK#253]
How to get the sender userID of a conversation in MobiComConversationFragment.java class?

**Comment by Sunilkumarr** [comment]
@winpraneeth Can i know do you want the logged in userId where he will be sending a message to receiver ?

**Comment by winpraneeth** [comment]
Not the logged in userID.

**Comment by Sunilkumarr** [comment]
@winpraneeth  This code will give who sent the latest message of that user  userId 

In MobiComConversationFragment.java in      **public void addMessage(final Message message)** method at line 709

https://github.com/AppLozic/Applozic-Android-SDK/blob/master/mobicomkitui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java#L709

paste this below code to get the userId of who sent latest message 

      
   ```
   String latestMessageSentByUserId;
                    if (message.getGroupId() != null) {
                        if (message.isTypeOutbox()) {
                            latestMessageSentByUserId = MobiComUserPreference.getInstance(getActivity()).getUserId();
                        } else {
                            latestMessageSentByUserId = message.getContactIds();
                        }
                    } else {
                        if(message.isTypeOutbox()){
                            latestMessageSentByUserId = MobiComUserPreference.getInstance(getActivity()).getUserId();
                        }else {
                            latestMessageSentByUserId = message.getContactIds();
                        }
                    }

                    Log.i("Latest  message :","Sent by userId is : "+latestMessageSentByUserId);

```
let me know if your looking for something else here

**Comment by winpraneeth** [comment]
This is not what I want. My scenario is I have a context based chat and when I click on a conversation I need to get the sender userId of that respective conversation

**Comment by Sunilkumarr** [comment]
@winpraneeth ok that is not the sender userId its receiver userId to whom you will  start the conversation 
 
At this  below link  the contact object of the receiver will be set once you launch the chat with other receiver user .

https://github.com/AppLozic/Applozic-Android-SDK/blob/master/mobicomkitui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java#L148




```
          if(contact != null){
            String userId = contact.getContactIds(); //userId 
         }
```

**Comment by winpraneeth** [comment]
I'm not sure if I made myself clear. Say I'm the receiver and I click on a chat sent to me, here the receiver needs to get the sender .

if(contact != null){
            String userId = contact.getContactIds(); //userId 
         }

Does this do that?

**Comment by Sunilkumarr** [comment]
@winpraneeth yes this will do that you will get the userId
