### ISSUE TITLE
How to get opponent user online status in boolean tipe

### ISSUE THREAD

**Issue by jaymahfudy** [AppLozic/Applozic-Android-SDK#254]
## Goals

my system need to check if a user online or not to execute a command
## Expected Results

by knowing the user status i can make a condition base on the user online status
## Code Sample

Applozic Android SDK version: ?

latest version
Android device: ? yes android

Android OS version: ?

Dependencies used with version: ? i import the uiwidget toolkit from github example

**Comment by Sunilkumarr** [comment]
@jaymahfudy You can copy paste this method and call this in async task  and pass the userid to get the current details of user in logs added for this in that you can check the  **userDetail.isConnected()** is true or false 

```
  public void processUserDetails(String userId) {
        if(TextUtils.isEmpty(userId)){
            return;
        }
        UserClientService userClientService = new UserClientService(context);
        Set<String> userIds = new HashSet<>();
        userIds.add(userId);
        String response = userClientService.getUserDetails(userIds);
        if (!TextUtils.isEmpty(response)) {
            UserDetail[] userDetails = (UserDetail[]) GsonUtils.getObjectFromJson(response, UserDetail[].class);
            if(userDetails != null ){
                UserDetail userDetail = userDetails[0];
                if(userDetail != null){

                    if(userDetail.isConnected()){
                        Log.i("User","Is Online");
                    }else {
                        Log.i("User","last seen at: "+userDetail.getLastSeenAtTime());
                    }
                    Log.i("User","UserId:"+userDetail.getUserId());

                    Log.i("User","image link :"+userDetail.getImageLink());

                    Log.i("User","display name:"+userDetail.getDisplayName());
                }
            }
        }
    }

```

**Comment by jaymahfudy** [comment]
dsds

**Comment by jaymahfudy** [comment]
I try to use the code and include it in the card adapter but it didn't working

**Comment by jaymahfudy** [comment]
i al

**Comment by jaymahfudy** [comment]
i already call it use the asynctask
but it still not working

**Comment by Sunilkumarr** [comment]
@jaymahfudy the method code which i have added here it will give the current status once you call that api method in async task .Can i know where you want to use this online status  ?

**Comment by jaymahfudy** [comment]
@Sunilkumarr i try to add it on my RecycleView Adapter and you can see the code below.
thanks in advance
https://gist.github.com/jaymahfudy/9065fcd07fa8d2b949ebf81fb2fc8294

**Comment by Sunilkumarr** [comment]
Inside your Adapter get the status and show at starting  
  1)
```
AppContactService appContactService = new AppContactService(context);
                Contact contact =  appContactService.getContactById("userId");//  pass userId in ur case  pass the email id
                contact.setFullName("display Name here");

               if(contact.isConnected()){
                   Log.i("User is ","online");
               }else{
                   Log.i("User is ","offline");
               }

```
2)Call this  platfrom api  https://www.applozic.com/docs/platform-api-chat.html#user-details to get the details of the users then once after getting response from the user details api call the contacts insert api upsert  method by building a contact object  
check this doc for the api 
https://www.applozic.com/docs/android-chat-sdk.html#contacts  after  bundling and inserting inserting the details send the broadcast   to update  your adapter or refresh the view   or you can update single view in  RecycleView Adapter
