### ISSUE TITLE
Message with html content needed

### ISSUE THREAD

**Issue by MobileKunst** [AppLozic/Applozic-Android-SDK#256]
## Goals

 Is it possible to force demo application to interpret message as html code ? I'd like to put some user friendly looking links <a href="http://google.com">description</a>.

Maybe Should I add some meta-data to message ?

I noticed that Message object at android have contentType field which can accept value TEXT_HTML

## Expected Results
In mobile android aplication message with html code looks like in browser

## Actual Results
Html code is presented

## Steps to Reproduce
Send message with html code

## Code Sample
POST
https://apps.applozic.com/rest/ws/message/dispatch
{
  "senderName":"xxx",
  "to":"8496007c16814b568c96d6c3e20d0456",
  "message":"Hi focz2, visit: <a href='http://www.google.com'>google</a>"
}
Applozic Android SDK version: ?

Android device: ?

Android OS version: ?

Dependencies used with version: ?

**Comment by Sunilkumarr** [comment]
@MobileKunst  only some tags are supported for message **contentType** = "3" you can try sending a message with contentType  TEXT_HTML  i.e contentType  value is 3   and for   link clickable you have to do some changes for that this are the changes

1) You need to download github sample project from  https://github.com/AppLozic/Applozic-Android-SDK and  import the **mobicomkitui** module or folder  into your project  and add 
`compile project(':mobicomkitui')  ` in your app build.gradle file 

2) Open **mobicom_received_message_list_view.xml** file and find the textview with android:id="@+id/message" and go to this  [link line number](https://github.com/AppLozic/Applozic-Android-SDK/blob/master/mobicomkitui/src/main/res/layout/mobicom_received_message_list_view.xml#L114
)  and remove the   android:autoLink="all" from the file in your project  and do the same for this **mobicom_sent_message_list_view.xml** file remove android:autoLink="all" at 
[link line number](https://github.com/AppLozic/Applozic-Android-SDK/blob/master/mobicomkitui/src/main/res/layout/mobicom_sent_message_list_view.xml#L62
)

3) Open **DetailedConversationAdapter.java** file in your project and go to this [ link ](https://github.com/AppLozic/Applozic-Android-SDK/blob/master/mobicomkitui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java#L765) and remove that selected link and paste this below code at same line 
```

               if (Utils.hasNougat()) {  
    messageTextView.setText(Html.fromHtml(message.getMessage(),Html.FROM_HTML_MODE_LEGACY));
                    }else {
                        messageTextView.setText(Html.fromHtml(message.getMessage()));
                    }
                    messageTextView.setMovementMethod(LinkMovementMethod.getInstance());
                    Linkify.addLinks(messageTextView, 0);
```

 In same file **DetailedConversationAdapter.java**  go to this
 [link ](https://github.com/AppLozic/Applozic-Android-SDK/blob/master/mobicomkitui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/adapter/DetailedConversationAdapter.java#L767) below that line paste this line
          ` Linkify.addLinks(messageTextView,Linkify.ALL);
`
