### ISSUE TITLE
Cannot implement applozic Context Based function

### ISSUE THREAD

**Issue by jerrycho** [AppLozic/Applozic-Android-SDK#257]
## Goals

implement applozic  Context Based  function [https://www.applozic.com/docs/android-chat-sdk.html#context-based-chat] in our company app

## Expected Results

Step 1: 
Sender[A] send context base with tile "TITLE1" to Receiver[B]  - Display Content fine
Step 2: 
Sender[A] send context base with tile "TITLE2" to Receiver[B]  - Display Content with title "TITLE2"

## Actual Results

Step 1: 
Sender[A] send context base with tile "TITLE1" to Receiver[B]  - Display Content fine
Step 2: 
Sender[A] send context base with tile "TITLE2" to Receiver[B]  - BUT Display Content with title STILL "TITLE1"

## Steps to Reproduce

Step 1: 
Sender[A] send context base with tile "TITLE1" to Receiver[B]  - Display Content fine
Step 2: 
Sender[A] send context base with tile "TITLE2" to Receiver[B]  - BUT Display Content with title STILL "TITLE1"

## Code Sample

https://www.applozic.com/docs/android-chat-sdk.html#context-based-chat

Applozic Android SDK version: ?

com.applozic.communication.uiwidget:audiovideo:1.2

Android device: ?--

Android OS version: ?--

Dependencies used with version: ?--

**Comment by Sunilkumarr** [comment]
@jerrycho if you want to update the context based chat with new details like title, subTitle, image link  you need to change the setTopicId with new topic id then it will change 

        Conversation conversation = new Conversation();
        conversation.setTopicId("Your Topic Id //unique "); //change this topic id with different  one
        conversation.setUserId("RECEIVER USERID");
        conversation.setTopicDetail(topic.getJson());

**Comment by jerrycho** [comment]
Hi,
It was now. Thanks for support
