### ISSUE TITLE
GCM is not work

### ISSUE THREAD

**Issue by jerrycho** [AppLozic/Applozic-Android-SDK#260]
## Goals
1. Can Received message via from GCM when app is not open
2. Do not have to open ConversationActivity once time, also received message

## Expected Results
1. Can Received message via from GCM when app is not open
2. Do not have to open ConversationActivity once time, also received message

## Actual Results

1. Can not Received message via from GCM when app is not open
2. Have to open ConversationActivity once time to received message

## Steps to Reproduce
---

## Code Sample
https://www.applozic.com/docs/android-chat-sdk.html#gcm-is-already-enabled-in-my-app

Applozic Android SDK version: ?
com.applozic.communication.uiwidget:audiovideo:1.2

Android device: ? --

Android OS version: ?--

Dependencies used with version: ?--

**Comment by Sunilkumarr** [comment]
Can you check in push notification testing tool by entering application Key and userId https://www.applozic.com/docs/push-notification-test.html what is the response your getting Status and Registration Id column

**Comment by jerrycho** [comment]
HTTP Status Code: 401()

**Comment by Sunilkumarr** [comment]
1)Can you check have you updated the correct GCM  server key in this link ***[Applozic Dashboard](https://dashboard.applozic.com/views/applozic/page/admin/dashboard.jsp) under Edit Application -> Push Notification -> Android -> GCM/FCM Server Key.***

2)Is there any Key restriction is added for   ip restriction  in https://console.developers.google.com for your GCM server key ?

**Comment by jerrycho** [comment]
1)Can you check have you updated the correct GCM server key in this link Applozic Dashboard under Edit Application -> Push Notification -> Android -> GCM/FCM Server Key.
Checked. it is our GCM key

2)Is there any Key restriction is added for ip restriction in https://console.developers.google.com for your GCM server key ?
No

**Comment by Sunilkumarr** [comment]
Can you send the applozic applicationKey, GCM server key, your app android manifest file  and if possible debug apk  to support@applozic.com

**Comment by jerrycho** [comment]
sent, please check email.

**Comment by Sunilkumarr** [comment]
this was an issue with sender id updated in [applozic.com](applozic.com) dashboard in place of gcm or fcm server key
