### ISSUE TITLE
Unread count doesn't change after sending a message

### ISSUE THREAD

**Issue by rrychlewski** [AppLozic/Applozic-Android-SDK#261]
## Goals
I'd like to read a total unread message count for particular user by API.

## Expected Results
A number of total unread message for particular user.

## Actual Results
Total unread count doesn't change after sending a message.

## Steps to Reproduce

1. Read user details which contains unreadCount
2. Send Message to this user
3. Read user details which contains unreadCount

## Code Sample

https://apps.applozic.com/rest/ws/user/v2/detail
POST
{
  "userIdList" : ["d120ac16ba8f4249bd488bf91e3b723a"]
}

Response 200 OK :
{
"status": "success",
"generatedAt": 1498463829407,
"response": [
  {
"userId": "d120ac16ba8f4249bd488bf91e3b723a",
"userName": "focz2",
"connected": false,
"status": 0,
"lastSeenAtTime": 1498249936000,
"createdAtTime": 1497964776864,
"unreadCount": 0,
"displayName": "focz2",
"email": "sfg@dfg.pl",
"deactivated": false,
"connectedClientCount": 0,
"active": true,
"lastLoggedInAtTime": 1498249930802,
"lastMessageAtTime": 1498212163941
}
],
}

https://apps.applozic.com/rest/ws/message/dispatch
POST 
{
  "senderName":"FishApp",
  "to":"d120ac16ba8f4249bd488bf91e3b723a",
  "message":"Hi focz2"
}

Response 200 OK:
{
"messageKey": "5-a6b2d89d-3456-40ed-8eb0-420ab14db89c-1498463875230",
"createdAt": 1498463875233
}

https://apps.applozic.com/rest/ws/user/v2/detail
POST
{
  "userIdList" : ["d120ac16ba8f4249bd488bf91e3b723a"]
}

Response 200 OK
{
"status": "success",
"generatedAt": 1498463905761,
"response": [
  {
"userId": "d120ac16ba8f4249bd488bf91e3b723a",
"userName": "focz2",
"connected": false,
"status": 0,
"lastSeenAtTime": 1498249936000,
"createdAtTime": 1497964776864,
"unreadCount": 0,
"displayName": "focz2",
"email": "sfg@dfg.pl",
"deactivated": false,
"connectedClientCount": 0,
"active": true,
"lastLoggedInAtTime": 1498249930802,
"lastMessageAtTime": 1498463875512
}
],
}

**Comment by Sunilkumarr** [comment]
Can you please explain where you want to use this API is in android or in different platform?
