### ISSUE TITLE
Reduce Chat message rectangle height

### ISSUE THREAD

**Issue by shiv4390** [AppLozic/Applozic-Android-SDK#262]
How can i reduce the background height of chat message ? As It is looking very unprofessional and ugly to me .

**Comment by Sunilkumarr** [comment]
For changing the Width  and  Height  you need to download the project from github link  https://github.com/AppLozic/Applozic-Android-SDK  and import the module **mobicomkitui**  and add `compile project(':mobicomkitui') `in your app build.gradle file 
1)Open **mobicom_received_message_list_view.xml** and at this line change the  android:minHeight 
        android:minWidth 
https://github.com/AppLozic/Applozic-Android-SDK/blob/master/mobicomkitui/src/main/res/layout/mobicom_received_message_list_view.xml#L46-L47
2)Open **mobicom_sent_message_list_view.xml** and  at this line change the  android:minHeight 
        android:minWidth  
https://github.com/AppLozic/Applozic-Android-SDK/blob/master/mobicomkitui/src/main/res/layout/mobicom_sent_message_list_view.xml#L21-L22
