### ISSUE TITLE
Cannot add call and video call library

### ISSUE THREAD

**Issue by baokk** [AppLozic/Applozic-Android-SDK#263]
## Goals

I'm trying to add com.applozic.communication.uiwidget:audiovideo:1.2 to SDK
but I face with this issue
## Actual Results

Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK org/eclipse/paho/client/mqttv3/internal/nls/messages_fr.properties
  	File1: /Users/baokk/.android/build-cache/6edce2db3a33d38d185e2f38211cf3c40022bd2d/output/jars/classes.jar
  	File2: /Users/baokk/Documents/AndroidStudioProject/Applozic-Android-SDK/mobicomkit/build/intermediates/bundles/default/classes.jar
## Code Sample

My gradle

apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
repositories {
    maven { url 'https://maven.fabric.io/public' }
}
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    defaultConfig {
        applicationId "com.eps.biztalks"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {

        abortOnError false

    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/ECLIPSE_.SF'
        exclude 'META-INF/ECLIPSE_.RSA'
    }
}

dependencies {
    //compile fileTree(dir: 'libs', include: ['*.jar'])
    compile project(':mobicomkitui') //Note: use this for customization
    compile 'com.applozic.communication.uiwidget:audiovideo:1.2'
   //compile 'com.applozic.communication.uiwidget:mobicomkitui:4.87' //Note:use this in case customization is not required
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.android.support:appcompat-v7:25.3.1'
    //compile 'com.facebook.android:facebook-android-sdk:4.1.0'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support:multidex:1.0.1'
    //compile 'com.android.support:cardview-v7:22.0'
    //compile 'com.android.support:recyclerview-v7:22.0'
    compile('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
        transitive = true;
    }
    compile 'net.rimoto:intlphoneinput:1.0.1'
}
apply plugin: 'com.google.gms.google-services'

**Comment by Sunilkumarr** [comment]
Inside dependencies  { 
you have added both 
1)compile project(':mobicomkitui')
2)compile 'com.applozic.communication.uiwidget:audiovideo:1.2'
at a time you cant use both  

comment  this line --> `compile project(':mobicomkitui') //Note: use this for customization  
`

**Comment by baokk** [comment]
@Sunilkumarr : If does like that way. How about custom UI

**Comment by Sunilkumarr** [comment]
For audio video sample project you can check this link for downloading the sample project https://github.com/AppLozic/Applozic-Android-Chat-Sample/tree/master/Applozic-Android-AV-Sample

After downloading you need to import the audiovideo module into your project  for customization and in your build.gradle file you need add
 compile project(':audiovideo')

**Comment by baokk** [comment]
@Sunilkumarr That means I cannot using 
> compile project(':mobicomkitui') //Note: use this for customization
in my SDK project right?. Let me download the audiovideo module and try to import
Thanks

**Comment by Sunilkumarr** [comment]
Yes for customization you don't need to add this 

compile 'com.applozic.communication.uiwidget:audiovideo:1.2'  this only in case if you don't have customization

**Comment by baokk** [comment]
@Sunilkumarr  I can add and using now. Thank you
