### ISSUE TITLE
Add Applozic to Tabbed Activity

### ISSUE THREAD

**Issue by baokk** [AppLozic/Applozic-Android-SDK#265]
## Goals

I want to create main activity with three tabs 
Tab1 : List Conversations (ConversationFragment)
Tab2 : List Group Conversations (ConversationFragment filtered by group only)
Tab3 : List Contacts

![q5cem](https://user-images.githubusercontent.com/2900549/27926422-9654dc62-62b2-11e7-8d4a-18a71e9b40f0.png)
## Expected Results

How I call the fragment of Applozic in this case
[](url)
## Code Sample

Applozic Android SDK version: ?

Android device:

**Comment by Sunilkumarr** [comment]
Can you send with a details for this at support@applozic.com  some customisation is needed to do this to achieve

**Comment by baokk** [comment]
@Sunilkumarr I have sent an email with details screen already .
Please help to check 

1. List conversation (1:1 only)
![image](https://user-images.githubusercontent.com/2900549/27954322-af3f9938-6339-11e7-8734-61fa52e608da.png)
2. List conversation (broadcast message)
![image](https://user-images.githubusercontent.com/2900549/27954362-d352f342-6339-11e7-913d-a7ebbdae7570.png)
3. List conversation (group only)
![image](https://user-images.githubusercontent.com/2900549/27954374-dedf7a6e-6339-11e7-82b4-03acc28c54a7.png)
4. Contacts list
![image](https://user-images.githubusercontent.com/2900549/27954383-e41d7878-6339-11e7-8801-e102e206fc16.png)

**Comment by baokk** [comment]
@Sunilkumarr Please help me !!
