### ISSUE TITLE
Question about creating broadcast group

### ISSUE THREAD

**Issue by baokk** [AppLozic/Applozic-Android-SDK#271]
Hi Team,

I'm trying to create Broadcast group 
There are two kinds of the broadcast.
1. BROADCAST_ONE_BY_ONE(106)
2. BROADCAST(5)

When creating type (5) there is no notification send to member of group like ((My name) created group Test group)

But in type(106) after creating group all members were get notified: (My name) created group Test group) and create the group on receiver's devices

I don't want to send notification to member and create room on receiver's devices like type(5) for type(106)

Could you please help me or show me which files need to be edited in this case

**Comment by Sunilkumarr** [comment]
Only in receiver side you cant disable you can disable for that whole group both sides 
   
This is the code to disable for group 

Build Channel  meta data        
  ```
           ChannelMetadata channelMetadata = new ChannelMetadata();
            channelMetadata.setCreateGroupMessage("");
            channelMetadata.setAddMemberMessage("");
            channelMetadata.setRemoveMemberMessage("");
            channelMetadata.setGroupNameChangeMessage("");
            channelMetadata.setJoinMemberMessage("");
            channelMetadata.setGroupLeftMessage("");
            channelMetadata.setGroupIconChangeMessage("");
            channelMetadata.setDeletedGroupMessage("");
            channelMetadata.setHideMetaDataNotification(true);
                        
```
 Check this link for group create method call this in async task :      
[https://www.applozic.com/docs/android-chat-sdk.html#1-create-group](       https://www.applozic.com/docs/android-chat-sdk.html#1-create-group
)
        While creating a group set the above channel meta data:

        
`        channelInfo.setChannelMetadata(channelMetadata);
`

**Comment by baokk** [comment]
@Sunilkumarr How about the edit in current SDK source code?
I'm using this source code now.
And add new group call like this: 

 Intent intent = new Intent(this, ContactSelectionActivity.class);     
 intent.putExtra(ContactSelectionActivity.BROADCAST_ONE_BY_ONE,Channel.GroupType.BROADCAST.getValue().intValue());
 startActivity(intent);

And I want to hide create the message for this type of group.
Which file do I need to edit?

**Comment by Sunilkumarr** [comment]
Open **ContactSelectionFragment.java** file and go to the link line number  in that file 

`
`https://github.com/AppLozic/Applozic-Android-SDK/blob/master/mobicomkitui/src/main/java/com/applozic/mobicomkit/uiwidgets/people/contact/ContactSelectionFragment.java#L436`
`

and paste this code below that line in your  ContactSelectionFragment.java
```

                    if(groupType == Channel.GroupType.BROADCAST_ONE_BY_ONE.getValue()){
                        ChannelMetadata channelMetadata = new ChannelMetadata();
                        channelMetadata.setCreateGroupMessage("");
                        channelMetadata.setAddMemberMessage("");
                        channelMetadata.setRemoveMemberMessage("");
                        channelMetadata.setGroupNameChangeMessage("");
                        channelMetadata.setJoinMemberMessage("");
                        channelMetadata.setGroupLeftMessage("");
                        channelMetadata.setGroupIconChangeMessage("");
                        channelMetadata.setDeletedGroupMessage("");
                        channelMetadata.setHideMetaDataNotification(true);
                        channelInfo.setChannelMetadata(channelMetadata);
                    }
```
Thanks

**Comment by baokk** [comment]
@Sunilkumarr  Thanks for the support.

And the last question, with BROADCAST type I didn't saw the setup for ChannelMetadata for this kind of group.
But when creating the group with type BROADCAST there no notification to members but if change type to BROADCAST_ONE_BY_ONE will send the notification to members when creating a group.
For original code. Could you please explain on this.

**Comment by Sunilkumarr** [comment]
It's  handle in server side for the BROADCAST(5) type  not send notifications for create , add , icon change ,remove etc type messages

**Comment by baokk** [comment]
@Sunilkumarr So if I want to turn on send notification for the BROADCAST(5) just config in channelMetadata right?

**Comment by Sunilkumarr** [comment]
You cant set that for BROADCAST(5) server will not send notification to users for add, create , remove type for group  messages
