### ISSUE TITLE
Question about Config notification and Contact , Password

### ISSUE THREAD

**Issue by baokk** [AppLozic/Applozic-Android-SDK#274]
1. Notification setup
 
I have three options for notify : Sound (push as normal), Vibration(only vibration) , Mute(No notify)

Which file I need to config?

2. Contacts

Is there any ways to check I am in contact of other people ?
Ex: I have contact A in my contacts list . How can I know I was added into A user's contacts list?

3. Password

Which command for update password and display name ?

**Comment by Sunilkumarr** [comment]
1.Notification setup

In **NotificationService.java** at  line number 140 add the vibrate code based on shared preference enable to disable the vibrate 
[https://github.com/AppLozic/Applozic-Android-SDK/blob/master/mobicomkit/src/main/java/com/applozic/mobicomkit/api/notification/NotificationService.java#L140](
https://github.com/AppLozic/Applozic-Android-SDK/blob/master/mobicomkit/src/main/java/com/applozic/mobicomkit/api/notification/NotificationService.java#L140
)
 -->Mute(No notify) Do you want for all the chats to mute or only one group mute ?


2.You can use device contacts sdk for that   https://github.com/AppLozic/Applozic-Android-Chat-Sample/tree/master/Applozic-Android-SDK-Device-Conacts
for doc check the readme file in this repo 


3.Password

a)For updating  password call this code in async task 
```

   String response  =   UserService.getInstance(context).processUpdateUserPassword(oldPassword,newPassword);
        if(!TextUtils.isEmpty(response) && MobiComKitConstants.SUCCESS.equals(response)){
            Log.i("Password","Update successfully");
        }else {
            Log.i("Password","Failed to update");

        }

```
b) You can use this method call for updating display name or image url link  note :call this in async task 
`
UserService.getInstance(this).updateDisplayNameORImageLink(displayName,imageUrl,null,null);
`

**Comment by baokk** [comment]
> -->Mute(No notify) Do you want for all the chats to mute or only one group mute ?

Yes, For all chats @Sunilkumarr

**Comment by Sunilkumarr** [comment]
Yeah, for disable the notification this is the documentation link https://www.applozic.com/docs/android-chat-sdk.html#notifications

Thanks
