### ISSUE TITLE
Push Notifications not working on KitKat

### ISSUE THREAD

**Issue by thab90** [AppLozic/Applozic-Android-SDK#275]
**Bugs**: 
Push notifications are not displaying for Kit kat version 4.4.2

## Goals
Push notifications for KitKat

## Expected Results
When you receive a push notification, it should notify the user.

## Actual Results
Quick conversation updates but no notification.

## Steps to Reproduce
Send message to a device running KitKat.

Applozic Android SDK version: 4.84

Android device: Nexus 5

Android OS version: 4.4.2

**Comment by Sunilkumarr** [comment]
@thab90 Can you send the applozic applicationKey, android manifest and if possible send debug apk also to support@applozic.com

**Comment by thab90** [comment]
Thanks will do

**Comment by reytum** [comment]
@thab90 Please check with latest version. Closing the issue.

**Comment by morristech** [comment]
thanks @reytum will do check out the changes and give feedback asap
