### ISSUE TITLE
*BUG* LastSeenAtTime value not updating

### ISSUE THREAD

**Issue by thab90** [AppLozic/Applozic-Android-SDK#278]
## Goals
When making the call for a User the lastSeenAtTime attribute in the object returned should return the last time a user was online.

## Expected Results
The lastSeenAtTime value should update to accurately display their online status

## Actual Results
The lastSeenAtTime value remains the same throughout an extended period of time.

## Steps to Reproduce
When entering a conversation from the quick conversation fragment, a call is made to return the User object. With the following url https://apps.applozic.com/rest/ws/user/detail?userIds=[USER_ID]. 

You'll see the lastSeenAtTime attribute does not update, nor does the connected attribute. This gives the impression that a user is either online or offline when they are the opposite.

## Code Sample
public void processUserStatus(String userId) {
        try {
            String contactNumberParameter = "";
            String response = "";
            try {
                contactNumberParameter = "?userIds=" + URLEncoder.encode(userId);
            } catch (Exception e) {
                contactNumberParameter = "?userIds=" + userId;
                e.printStackTrace();
            }

            response = httpRequestUtils.getResponse(getUserDetailUrl() + contactNumberParameter, "application/json", "application/json");
            Log.i(TAG, "User details response is " + response);
            if (TextUtils.isEmpty(response) || response.contains("<html>")) {
                return;
            }

            UserDetail[] userDetails = (UserDetail[]) GsonUtils.getObjectFromJson(response, UserDetail[].class);

            if (userDetails != null) {
                for (UserDetail userDetail : userDetails) {
                    Contact contact = new Contact();
                    contact.setUserId(userDetail.getUserId());
                    contact.setFullName(userDetail.getDisplayName());
                    contact.setConnected(userDetail.isConnected());
                    contact.setContactNumber(userDetail.getPhoneNumber());
                    contact.setLastSeenAt(userDetail.getLastSeenAtTime());
                    contact.setImageURL(userDetail.getImageLink());
                    contact.setUserTypeId(userDetail.getUserTypeId());
                    contact.setStatus(userDetail.getStatusMessage());
                    contact.setUnreadCount(0);
                    baseContactService.upsert(contact);
                }
                BroadcastService.sendUpdateLastSeenAtTimeBroadcast(context, BroadcastService.INTENT_ACTIONS.UPDATE_LAST_SEEN_AT_TIME.toString(), userId);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

Applozic Android SDK version: 4.94

Android device: All

Android OS version: All

**Comment by Sunilkumarr** [comment]
Can you recheck  it should be working now ?

**Comment by thab90** [comment]
Hi
It's not working on my end, below are 3 responses from the https://apps.applozic.com/rest/ws/user/detail?userIds=3227643.qa, the only thing that changes is the lastMessageAtTime value.

[{
	"userId": "3227643.qa",
	"userName": "Sam UkQa",
	"connected": false,
	"status": 0,
	"lastSeenAtTime": 1501684848000,
	"createdAtTime": 1499952636694,
	"unreadCount": 0,
	"displayName": "Sam UkQa",
	"imageLink": "https://s3-eu-west-1.amazonaws.com/zzqa/ProfilePicture/Customer/00_DEFAULT_350x350.jpg",
	"phoneNumber": "44793338637",
	"deactivated": false,
	"connectedClientCount": 0,
	"userTypeId": 0,
	"active": true,
	"lastLoggedInAtTime": 1501678332567,
	"lastMessageAtTime": 1501663847846
}]

[{
	"userId": "3227643.qa",
	"userName": "Sam UkQa",
	"connected": false,
	"status": 0,
	"lastSeenAtTime": 1501684848000,
	"createdAtTime": 1499952636694,
	"unreadCount": 0,
	"displayName": "Sam UkQa",
	"imageLink": "https://s3-eu-west-1.amazonaws.com/zzqa/ProfilePicture/Customer/00_DEFAULT_350x350.jpg",
	"phoneNumber": "44793338637",
	"deactivated": false,
	"connectedClientCount": 0,
	"userTypeId": 0,
	"active": true,
	"lastLoggedInAtTime": 1501678332567,
	"lastMessageAtTime": 1501742193493
}]

[{
	"userId": "3227643.qa",
	"userName": "Sam UkQa",
	"connected": false,
	"status": 0,
	"lastSeenAtTime": 1501684848000,
	"createdAtTime": 1499952636694,
	"unreadCount": 0,
	"displayName": "Sam UkQa",
	"imageLink": "https://s3-eu-west-1.amazonaws.com/zzqa/ProfilePicture/Customer/00_DEFAULT_350x350.jpg",
	"phoneNumber": "44793338637",
	"deactivated": false,
	"connectedClientCount": 0,
	"userTypeId": 0,
	"active": true,
	"lastLoggedInAtTime": 1501678332567,
	"lastMessageAtTime": 1501742451361
}]

**Comment by Sunilkumarr** [comment]
@thab90 We are looking into this issue

**Comment by Sunilkumarr** [comment]
@thab90 We have done some changes can you recheck  now?

**Comment by thab90** [comment]
I tested on the Applozic sample app and it's working there. Thanks
