### ISSUE TITLE
after combining applozic with my application, the request for another API access is error.

### ISSUE THREAD

**Issue by Widiyanto** [AppLozic/Applozic-Android-SDK#289]
after combining applozic with my application, the request for another API access is error.
I get an error like this:
"javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found."

whereas previously applozic combine with my application, I can access other APIs, for example API that I access:
https://newsapi.org/v1/articles?source=cnbc&sortBy=top&apiKey=140e15f66fb04c46a497da20ac379c77

is there a configuration that I need to fix?
error in OS Kitkat

**Comment by Sunilkumarr** [comment]
@Widiyanto  Can you please mention steps to reproduce issue ? from where your calling that api ?

**Comment by Widiyanto** [comment]
Thanks for response.
Previously not error, I also do not know why it becomes an error.
I do just combine applozic sdk to my project, and applozic works well. But, now I can not access other APIs

on android 5.0 calling API is fine, but in Kitkat it gets error as above.

I call API with okhttp, retrofit

**Comment by Sunilkumarr** [comment]
This is not applozic error !

Check this for retrofit 
https://stackoverflow.com/questions/29273387/certpathvalidatorexception-trust-anchor-for-certificate-path-not-found-retro
Maybe some sites are not accessible 
Check this doc  link  
https://developer.android.com/training/articles/security-ssl.html
