### ISSUE TITLE
ConversationList scrolling lag

### ISSUE THREAD

**Issue by morristech** [AppLozic/Applozic-Android-SDK#291]
## Goals
A smooth scrolling UX on the conversation list

## Expected Results
Scrolling through messages in the conversation should be seamless

## Actual Results
While scrolling through messages in a conversation with large message count the UX is jittery and seems to suffer from render lag 

## Steps to Reproduce
Select a conversation with a message count of a 100+ messages.
Try and scrolling from top to bottom of the conversation a couple of times, notice the lag when flinging the list.
This occurs in both directions. 

## Code Sample

Applozic Android SDK version: 5.0

Android device: Any

Android OS version: 4.4.2+

Dependencies used with version: none

**Comment by Sunilkumarr** [comment]
We are working on this issue i will update on this

**Comment by morristech** [comment]
No resolution to this issue yet?

**Comment by Sunilkumarr** [comment]
We have done with changes one or two issues we have in that it will be released in coming  next week release

**Comment by morristech** [comment]
thanks, appreciate it!

**Comment by Sunilkumarr** [comment]
@morristech  we have released Recycler view  with fix you can use the latest SDK https://github.com/AppLozic/Applozic-Android-SDK/releases/tag/5.6.4
