### ISSUE TITLE
Null pointer exception at LocalBroadcastManager.java:297 (mobicomkitui:5.1.2)

### ISSUE THREAD

**Issue by virendragupta30** [AppLozic/Applozic-Android-SDK#295]
## Goals

want to customize applozic UI for our project.
## Expected Results

Click on group or user chat, chat screen should be opened.

## Actual Results

 Null pointer exception.
10-30 19:04:49.376 21198-21237/com.truweight.controllers D/SettingsInterface:  from settings cache , name = android_id , value = eb01299db90455fd
10-30 19:04:49.403 21198-21198/com.truweight.controllers E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.truweight.controllers, PID: 21198
                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.BroadcastReceiver.onReceive(android.content.Context, android.content.Intent)' on a null object reference
                                                                               at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
                                                                               at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
                                                                               at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                               at android.os.Looper.loop(Looper.java:207)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5776)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
## Steps to Reproduce

Customoze applozic fragment as per doc https://docs.google.com/document/d/1qH1razXLCg_aCWgdhVp4ATCAZqU3APugWiUbSEJm0-A/edit.
First screen working properly ConversationActivity.java but when we click on Group chat or individual chat app is crashed. getting null pointer exception at 
android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
## Code Sample

In ConversationActivity.java after onResume method crashed. 

        super.onResume();
        LocalBroadcastManager.getInstance(this).registerReceiver(mobiComKitBroadcastReceiver, BroadcastService.getIntentFilter());
        Intent subscribeIntent = new Intent(this, ApplozicMqttIntentService.class);
        subscribeIntent.putExtra(ApplozicMqttIntentService.SUBSCRIBE, true);
        startService(subscribeIntent);

        if (!Utils.isInternetAvailable(getApplicationContext())) {
            String errorMessage = getResources().getString(R.string.internet_connection_not_available);
            showErrorMessageView(errorMessage);
        }
We already initialize mobiComKitBroadcastReceiver as per doc.
Applozic Android SDK version: ?

   // compile 'com.applozic.communication.uiwidget:mobicomkitui:5.1.2'
    compile project(':mobicomkitui')
Android device: ?
Lenovo k4 note
Android OS version: ?
Android 6.01
Dependencies used with version: ? No

**Comment by Sunilkumarr** [comment]
@virendragupta30 can you share your here  activity file where you added the fragment? . 
looks like mobiComKitBroadcastReceiver is null can you verify the step 3 ?

**Comment by virendragupta30** [comment]
As per your doc, we added mobiComKitBroadcastReceiver = new MobiComKitBroadcastReceiver(this, conversationUIService); onCreate() of on our HomeActivity.java
then we added in ConversationActivity.java mobiComKitBroadcastReceiver = new MobiComKitBroadcastReceiver(this); onCreate() method.
I checked in debug mode mobiComKitBroadcastReceiver is not coming null.

Please check and resolve issue as soon as possible.

**Comment by Sunilkumarr** [comment]
Can you please share this files to support@applozic.com ?
1)The activity where you added the applozic fragment 
2)ConversationUiService.java
3)MobiComKitBroadcastReceiver.java
4)MobicomConversationFragment.java

**Comment by virendragupta30** [comment]
yes sure.

**Comment by virendragupta30** [comment]
Required file shared at  support@applozic.com.

**Comment by virendragupta30** [comment]
Now problem resolve.
We are initializing below code onCreate() of HomeActivity.java
        mobiComQuickConversationFragment = new MobiComQuickConversationFragment();
        conversationUIService = new ConversationUIService(this, mobiComQuickConversationFragment);
        mobiComKitBroadcastReceiver = new MobiComKitBroadcastReceiver(this, conversationUIService);

        Intent lastSeenStatusIntent = new Intent(this, UserIntentService.class);
        lastSeenStatusIntent.putExtra(UserIntentService.USER_LAST_SEEN_AT_STATUS, true);
        startService(lastSeenStatusIntent);

and calling fragment whenever required.
