### ISSUE TITLE
How to get all the group chat list

### ISSUE THREAD

**Issue by bharatguptacgt** [AppLozic/Applozic-Android-SDK#297]
## Goals
Want to show all the group chats in a single page

## Expected Results
i want to fetch all the groups to which i belong of my app. As you are showing in your people kit activity. 

Android device: Yes

**Comment by Sunilkumarr** [comment]
Can i know do you want to show latest message also  or just a group list ?
 
if its only group list this is code :

 Call this method  it will return the groups which you have been added  and this below code will give from local db  :

 ```
  List<Channel> channelList =    ChannelService.getInstance(context).getChannelList();

        for(Channel channel:channelList){
            Log.i("Channel","Name : "+channel.getName());
            Log.i("Channel","GroupId : "+channel.getKey());
            Log.i("Channel","Client group id : "+channel.getClientGroupId());
            Log.i("Channel"," Image url  : "+channel.getUnreadCount());
            Log.i("Channel","Group type  : "+channel.getType());
        }

```
Right now we dont have method for getting from server 
If your looking for fetching the groups from server this is code you need to add in sdk :  

https://docs.google.com/document/d/1ZvnWznL4A8nYGdczgQWb5DkeQO1K9DBIXF2ZXxCa28I/edit?usp=sharing
