### ISSUE TITLE
in conversation activity not get from all datas for a particular person chat ?how i get from all the data 

### ISSUE THREAD

**Issue by BhavaniBaskaran** [AppLozic/Applozic-Android-SDK#298]
## Code Sample

Applozic Android SDK version: ?

Android device: ?

Android OS version: ?

Dependencies used with version: ?

**Comment by Sunilkumarr** [comment]
Can you share  some logs from Android studio once you go to Conversation Activity?

**Comment by BhavaniBaskaran** [comment]
in conversation activity list is came if we click list means (last chat with person datas are came ) but once we click plus button list is came overall datas are came

**Comment by Sunilkumarr** [comment]
HI,
Can you record the screen of that  and share the video here ?

**Comment by BhavaniBaskaran** [comment]
​​Hi,
    Below i have attached the screenshots,once u check it, so please help
for me in this concept. in the conversation activity chat list is came if
we click a list data's are came that data comes under based on the
conversation id once top of the conversation activity "plus" button is
there when we click a plus button chat based on the list is came but in
that data's are overall chat data's comes under the user id .For example :
same name of chat is created (nandhini) one of the chat (nandhini) is "Hi"
(data) another one of the chat (nandhini) is "Hello" (data)...in this
conversation chat list showing a nandhini list,when we click nandhini chat
list open the conversation but last conversation of chat data is showing
for ex is "Hello" once we click a plus button showing same chat list of
nandhini click a chat list open the conversation but showing previous
conversation also for ex is "Hi" & "Hello".....in that format i want to
show the chat list also. once i send the screenshots u check it after that
u give the idea.

​
 chat
<https://drive.google.com/drive/folders/1WoSdh2BGksfXaH1oId5_BPh6H1v85rY9>
​

**Comment by Sunilkumarr** [comment]
Here the first screen is for showing the chat history of individual one to one chat or group chat   and once you click on  (+ ) plus button that are contacts it will load and show all the users which are registered in your app or  the inserted contacts by you,

 Do you mean you want to add / individual screen in some activity or tab view  where the first screen will not be showing and directly you will see the individual screen  of user ex:    (nandhini)  ?  if you have any mocks up pls share at support@applozic.com

**Comment by BhavaniBaskaran** [comment]
Hi Sunil,
              u said i understood but i need a example because (Do you mean
you want to add / individual screen in some activity or tab view where the
first screen will not be showing and directly you will see the individual
screen of user ???) in this chat list so many members is there ? how can i
send the user id for a particular members of this chat conversation ??
please explain briefly. i need a example.
                   Once u said by not showing the first page, directly show
the + plus button screen correct ah ? sunil .

**Comment by Sunilkumarr** [comment]
@BhavaniBaskaran  Checked with your applicationKey and userId you have created both normal chat and context based chat for user nandhini either you can create a normal one to one  chat or  context based  one to one chat but both cant be at a time  

1)For normal one to one chat   with out context based chat check this doc link 
https://docs.applozic.com/docs/android-1-1-user-chat-and-group-chat#section-initiate-chat

2)For context based chat check this link 
 https://docs.applozic.com/docs/android-1-1-user-chat-and-group-chat#section-context-based-chat

**Comment by BhavaniBaskaran** [comment]
Hi,
      I am BhavaniBaskaran , i have one doubt from Applozic Chat
Notification concept if we kill the app Chat Notification is not coming for
android any device.As of now Android App from Google Play store,before
uploading the apk from google play store "Chat notification is working"
when we "kill app is also working" but still we upload Current apk from
Google play store means if we kill the app *"Applozic Chat Notification is
not working". *so please give some idea's from this scenario & how it's
overcome this scenario.



Thanks,
BhavaniBaskaran

**Comment by Sunilkumarr** [comment]
Hi Bhavani,

Can you share us below details to support@applozic.com 
1)Applozic applicationKey and one current logged in userId in your app
2)Main app build.gradle file 
3)App Android manifest file
