### ISSUE TITLE
Blocked Contact list outside Applozic UI

### ISSUE THREAD

**Issue by pravingaikwad07** [AppLozic/Applozic-Android-SDK#301]
I want to show list of all Blocked Users from AppLozic outisde Applozic Current UI. Currently Applozic SDK's Blocked List API is returning  list of blocked users with "email id" key only but not all user details and it will be too much network work if we tried to fetch individual user details from the list of email ids fetched. 

Is there a way to get blocked users list with atleast their fullName , emailId, id, profileImage etc.

**Comment by Sunilkumarr** [comment]
@pravingaikwad123   Currently we don't have api for block where it will give all the details of that blocked or unblocked users  image url, name  etc     

You can check first if that user already in local db if its there then you can get the details from contact name,  userId,  profile image etc

code: 
 ```
ContactDatabase contactDatabase =   new ContactDatabase(context);
Contact contact = contactDatabase.getContactById(userId);
you can get the details like below :

if(contact != null){
//contact.getDisplayName();
//contact.getImageURL();
//contact.getEmailId();
}

````

if the above contact is null then get the list of users where contact details are null then call the server to get the details 

Check this method call this in async task 

Code:
```
public Set<Contact> getListOfUsers(Set<String> userIds,Context context ){
    UserClientService userClient = new UserClientService(context);
    String response = userClient.getUserDetails(userIds);
    Set<Contact> userContactSet = new HashSet<>();
    if (!TextUtils.isEmpty(response)) {
        UserDetail[] userDetails = (UserDetail[]) GsonUtils.getObjectFromJson(response, UserDetail[].class);
        for (UserDetail userDetail : userDetails) {
            Contact userContact = new Contact();
            userContact.setUserId(userDetail.getUserId());
            userContact.setFullName(userDetail.getDisplayName());
            userContact.setImageURL(userDetail.getImageLink());
            userContactSet.add(userContact);
        }
    }
    return userContactSet;
}
```
