### ISSUE TITLE
whatsapp design

### ISSUE THREAD

**Issue by byRulox** [AppLozic/Applozic-Android-SDK#304]
Can you customize the whatsapp application? This mean ugly like that. Pliss

**Comment by Sunilkumarr** [comment]
@byRulox Yes you can customize the WhatsApp like design 
you can try out sample app from github 

[https://github.com/AppLozic/Applozic-Android-SDK]( https://github.com/AppLozic/Applozic-Android-SDK)

You can check this below doc for adding chat list to tab activity 

https://docs.applozic.com/docs/android-chat-theme-and-customization#section-fragment-support


You can check this doc for changing colors and other settings

[https://docs.applozic.com/docs/android-chat-theme-and-customization](https://docs.applozic.com/docs/android-chat-theme-and-customization
)

**Comment by byRulox** [comment]
you did not understand me, I want to add menus tabs like whatsapp

**Comment by Sunilkumarr** [comment]
First you need to create tabs for that using tab layout and view pager once your done with that then next  you need to add our  chat list fragment into your Tab layout activity for this  you can check this doc for adding chat list screen into tab activity it has steps for adding it

https://docs.google.com/a/applozic.com/document/d/1-TbJWCUEIzwWGD8mBkV6y2PLrNAIWTmTI6jJuzgC7c4/edit?usp=drivesdk

Let us know if you face any issue in adding it to tab layout activity

**Comment by byRulox** [comment]
If you have time and it's not a problem, can you add it?

**Comment by Sunilkumarr** [comment]
@byRulox  you can check above doc which has some steps for adding it into your tab activity, if you want use to do the customization you can send the requirements to support@applozic.com
