### ISSUE TITLE
Push Notifications not working on CORDOVA

### ISSUE THREAD

**Issue by fiveandroid** [AppLozic/Applozic-Android-SDK#305]
Using the plugin the notifications work very well, but when the GUI changes color from blue to red, making the changes in the SDK and creating the new plugin, the notifications stop working

HELP ME

**Comment by Sunilkumarr** [comment]
was the issue with updating to latest chat modules  which had a support for android 8 
he was not migrated android manifest changes from this link https://github.com/AppLozic/Applozic-Android-SDK/releases/tag/5.2
