### ISSUE TITLE
how to change login method

### ISSUE THREAD

**Issue by dlaravindhan** [AppLozic/Applozic-Android-SDK#306]
## Expected Results
i want login activity based on phone number authentication . and chat also based on phone number only.

Android device: yes

**Comment by Sunilkumarr** [comment]
@dlaravindhan  for phone number OTP authentication feature can you send a request at support@apploizc.com 

and chat based on the device contacts phone number  this is the repo for the  [sample sdk link ](https://github.com/AppLozic/Applozic-Android-Chat-Sample/tree/master/Applozic-Android-SDK-Device-Conacts) and it has the readme in the sample you need to follow that readme for integrating chat
