### ISSUE TITLE
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'. > More than one file was found with OS independent path 'bundle.properties'

### ISSUE THREAD

**Issue by NarendraKr** [AppLozic/Applozic-Android-SDK#310]
I am getting this error after import module mobicomkitui
and compile project(':mobicomkitui') in in project.I research lot but i din't get solution.Please help my Why such type of error is coming after integrated apploZic sdk in my project?Whitout this i can not modify UI.So please help me.I wasted 2 days solve the problem.I tried multiple times to reintegrate after this is showing same error.

**Comment by Sunilkumarr** [comment]
Can you share the sample project where this error is coming to support@applozic.com?

**Comment by NarendraKr** [comment]
yes..sir

**Comment by NarendraKr** [comment]
the problem was using messaging sdk and audio video sdk at a time..Thanks For solve issue.
