### ISSUE TITLE
How To Block Notification Pop Up?

### ISSUE THREAD

**Issue by Widiyanto** [AppLozic/Applozic-Android-SDK#313]

**Comment by Sunilkumarr** [comment]
@Widiyanto Hi, you mean do you want to disable all the notification to show/pop up in notification tray? if yes this is the link for settings to enable and disable notification https://docs.applozic.com/docs/android-chat-theme-and-customization#section-notifications

**Comment by Widiyanto** [comment]
Yes, thank sir.
`ApplozicClient.getInstance(context).disableNotification();
ApplozicClient.getInstance(context).enableNotification();`
