### ISSUE TITLE
how to skip chat list for showing on back press after notification click ??

### ISSUE THREAD

**Issue by MichelB** [AppLozic/Applozic-Android-SDK#315]
// Also if you intend on generating your own notifications as a result of a received FCM
        // message, here is where that should be initiated. See sendNotification method below.

        Log.e(TAG, "MobiComPushReceiver = " + MobiComPushReceiver.isMobiComPushNotification(remoteMessage.getData()));
        if (MobiComPushReceiver.isMobiComPushNotification(remoteMessage.getData())) {
            MobiComPushReceiver.processMessageAsync(this, remoteMessage.getData());
            return;
        }

??????

**Comment by Sunilkumarr** [comment]
@MichelB Add this setting in applozic login callback success in UserLoginTask code  then uninstall app and install again for changes to take 
 
       ApplozicClient.getInstance(context).hideChatListOnNotification();
