### ISSUE TITLE
I have designed a new modern logo for Applozic. I hope you like it.

### ISSUE THREAD

**Issue by sametceylan** [AppLozic/Applozic-Android-SDK#324]
I have studied your application and have designed a beautiful and creative logo that is appropriate for your application. I hope you like my production entirely. I also add color variants. Your comment is very important to me I hope you text as soon as possible. I sent a mail to support@applozic.com you can check it.
![asset 11](https://user-images.githubusercontent.com/34095452/39492709-275439b6-4d99-11e8-8af3-13ac164a0d70.png)
![asset 12](https://user-images.githubusercontent.com/34095452/39492710-277845c2-4d99-11e8-9265-cbacbd0a0f2d.png)
![asset 13](https://user-images.githubusercontent.com/34095452/39492711-279f3826-4d99-11e8-8177-94754247b0c8.png)
![asset 14](https://user-images.githubusercontent.com/34095452/39492712-27d19406-4d99-11e8-9422-fd041f9e2a6d.png)
![asset 22](https://user-images.githubusercontent.com/34095452/39492713-27f8a438-4d99-11e8-84c3-5b12347dcae9.png)
![bandicam 2018-04-29 21-19-03-530](https://user-images.githubusercontent.com/34095452/39492730-33e51ede-4d99-11e8-9112-07888430d0ed.png)
![asset 24](https://user-images.githubusercontent.com/34095452/39492742-3c193cb6-4d99-11e8-80b5-407d8f7f8af9.png)
![asset 25](https://user-images.githubusercontent.com/34095452/39492743-3c3e4fd8-4d99-11e8-8ae7-fd8657978385.png)

**Comment by reytum** [comment]
@sametceylan Thanks. We have shared with the design team. They will get back to you soon.
