### ISSUE TITLE
Need help on purchasing paid plan.

### ISSUE THREAD

**Issue by tobbysembiring** [AppLozic/Applozic-Android-SDK#325]
Hi, we are about to subscribe to your paid services on text chat, voice call and video call.
Could you let us know about the pricing.
I've tried to contact the support through web chat.
Please help.

Thank you.

**Comment by priyadarshi** [comment]
Can you please contact us on support@applozic.com.

**Comment by tobbysembiring** [comment]
Hi @priyadarshi Thank you. I've sent the email. :)
