### ISSUE TITLE
How to delete a user from Applozic using the SDK?

### ISSUE THREAD

**Issue by ambujaacool** [AppLozic/Applozic-Android-SDK#326]

**Comment by ambujaacool** [comment]
@Sunilkumarr The use case is that when a user is being deleted from my application, I want the same user to be deleted from the Applozic's server.

**Comment by Sunilkumarr** [comment]
This api you need to call from your backend server to delete the user from applozic server  doc [link ](https://docs.applozic.com/docs/platform-api-admin#section-delete-user)
