### ISSUE TITLE
Contacts not working everywhere

### ISSUE THREAD

**Issue by kherlopian1** [AppLozic/Applozic-Android-SDK#327]
https://postimg.cc/gallery/2w78z3oni/

Everyplace, the loading is stuck.When I click + icon on top loading is stuck, when a try new broadcast its stuck on contacts. wherever i go, loading is stuck in contacts.

Android google pixel 8.1 am using.

**Comment by kherlopian1** [comment]
using this library compile 'com.applozic.communication.uiwidget:mobicomkitui:5.8.6'

**Comment by kherlopian1** [comment]
Note. I deleted users from backend.

**Comment by kherlopian1** [comment]
please if u want the applozic key, send me email i send it for you to try it.

**Comment by reytum** [comment]
@kherlopian1 Please disable the registeredUserContactListCall , this setting is used to display all the registered users in your app.

**Comment by kherlopian1** [comment]
if i disable, the loader disappears.but i get no contact found. i need the feature to see all registered users in app. its working on ios.

**Comment by kherlopian1** [comment]
how can i email you , the applozic key so u check the bug on android. whenever i want to get contacts, do broadcast get contacts loader appears and doesnt go away.

**Comment by kherlopian1** [comment]
Ok. Just detected, loader waiting for images to download alot long. This should be solved hopefully, because imagine 200 users.why should i wait loader for 200 images to download ???
