### ISSUE TITLE
Android Firebase version 16 17 with errors

### ISSUE THREAD

**Issue by juanpicuervo** [AppLozic/Applozic-Android-SDK#328]
Gradle has errors when compiling 
    implementation 'com.applozic.communication.uiwidget:mobicomkitui:5.8.4'
with
    implementation 'com.google.firebase:firebase-core:16.0.1'
    implementation 'com.google.firebase:firebase-messaging:17.0.0'

You can test with this implementations.

Thanks

**Comment by Sunilkumarr** [comment]
@juanpicuervo We are doing a release for this today, you can use v 15.0.0 for google play service or  firebase  as we intenally use v15.0.0  
                                                                                                                                             
             implementation 'com.google.firebase:firebase-messaging:15.0.0'
             implementation 'com.google.android.gms:play-services-maps:15.0.0'
             implementation 'com.google.android.gms:play-services-location:15.0.0'

**Comment by Sunilkumarr** [comment]
Use the latest version its updated the play services and firebase 

          implementation 'com.applozic.communication.uiwidget:mobicomkitui:5.8.8'
