### ISSUE TITLE
Token authentication not working after token is refreshed on server side

### ISSUE THREAD

**Issue by apurcaroiu** [AppLozic/Applozic-Android-SDK#330]
## Goals
Authenticate users based on token.

## Expected Results
After user is signed in to our server, a new token is generated. At this step we also want to login the user against applozic server using the new token.

## Actual Results
Since the login was successful on our side and the new token was generated successfully, we would expect the login to also work on applozic server using the new token.
Instead we get a client server verification error.

The login however, works with the old token and it seems that the token is not getting invalidated in applozic.

## Steps to Reproduce
1. Create API which accepts userId and token as parameters.
2. Sign up user to our server and applozic successfully.
3. Clear application data and try to log in.
4. Login is successfully on our server and a new token is generated.
5. Applozic login fails with the new token because of  client server verification error.
6. Applozic login does work with old token.

Android device:  All devices

Android OS version: All OS Versions

Does applozic support token to be invalidated?

Thanks!

**Comment by Sunilkumarr** [comment]
@apurcaroiu we will check and update tomorrow  on this

**Comment by Sunilkumarr** [comment]
@apurcaroiu  Can you please share us your applicationKey and userId, password to support@applozic.com

**Comment by apurcaroiu** [comment]
@Sunilkumarr I have sent the details. As described, the issue appears only after a token refresh on our server.

Thanks!

**Comment by Sunilkumarr** [comment]
@apurcaroiu one of our team member as be replyed  did that solved or your still your facing same issue  let us know ?

**Comment by apurcaroiu** [comment]
@Sunilkumarr 
I am when invoking the follwoing code:
The user object has user id and password and the result is client verification failed.
If I invoke the API I do get the correct result from Postman.

For token based authentication, what would be the procedure to login the user and download the profile using the sdk you provide? Should I pass maybe the entire user object in this call?
Thanks!
if (!MobiComUserPreference.getInstance(context).isLoggedIn()){
            Applozic.loginUser(context, user, new AlLoginHandler() {
                @Override
                public void onSuccess(RegistrationResponse registrationResponse, Context context) {
                    attachModuleNavigationCallbacks(context);
                    mApplozicBridgeCallback.onRegistrationCompleted();
                }

                @Override
                public void onFailure(RegistrationResponse registrationResponse, Exception exception) {

                }
            });
        }

**Comment by reytum** [comment]
@apurcaroiu 
Basically applozic provides client side authentication as well as applozic side authentication.
For client side authentication you need to pass the authenticationTypeId as 0 in the user object when logging in. Then you will need to setup your authentication url in applozic dashboard. You do not need to set password to user object in this case as the user will be authenticated from your side.

In the second authentication type ie Applozic type you need to set the authenticationTypeId as 1 when logging in the user to applozic. Then you can set the password to the user(optional).

User user = new User();
user.setUserId(userId);
user.setAuthenticationTypeId(0);  //0 for client side and 1 for applozic side.

Refer to this documentation for more details - https://docs.applozic.com/docs/access-token-url

**Comment by apurcaroiu** [comment]
I am confused, you mentioned that for type 0 we should NOT set a password since it is client side.But in the docs it is saying that for type 0 the password should be the token, which is what we are doing. So we are setting our server token in the password field. 
https://docs.applozic.com/docs/android-chat-session

See below:
User user = new User();
user.setUserId(authToken.getUserId());
user.setEmail(accountModel.getEmail());
user.setPassword(authToken.getAccessToken());
user.setDisplayName(accountModel.getUsername());
user.setAuthenticationTypeId(User.AuthenticationType.CLIENT.getValue());On next step we call below:
new UserLoginTask(user, listener, context).execute((Void) null);
This works perfectly and the user does appear in applozic dashboad.

However when we try to login the user next time (because the application was uninstalled), the login fails and the endpoint configured in our dashboard is not even called:
Applozic.loginUser(context, user, new AlLoginHandler()
How the login should be performed using the sdk and access token authentication?


Thanks!

    On Monday, July 30, 2018, 5:42:41 PM GMT+3, Ashish Kanswal <notifications@github.com> wrote:  
 
 
@apurcaroiu
Basically applozic provides client side authentication as well as applozic side authentication.
For client side authentication you need to pass the authenticationTypeId as 0 in the user object when logging in. Then you will need to setup your authentication url in applozic dashboard. You do not need to set password to user object in this case as the user will be authenticated from your side.

In the second authentication type ie Applozic type you need to set the authenticationTypeId as 1 when logging in the user to applozic. Then you can set the password to the user(optional).

User user = new User();
user.setUserId(userId);
user.setAuthenticationTypeId(0); //0 for client side and 1 for applozic side.

Refer to this documentation for more details - https://docs.applozic.com/docs/access-token-url

**Comment by apurcaroiu** [comment]
@reytum 
Do you have any feedback on this?
As mentioned, I posted our code above where I set the refresh token as the password.

What would be the approach to log in the user on next attempt?
As mentioned, we use refresh tokens from our server and set it as password to the User object.

Thanks

**Comment by Sunilkumarr** [comment]
Hey Purcaroiu,

We checked the response coming from your server for the accessToken authentication call and found it is Json String.
Can you change the response from your end to boolean (true/false) as plain text instead of Json and then verify.

Attaching current response returned from your server.

![screen-shot-2018-08-03-at-20-19-32](https://user-images.githubusercontent.com/11742961/43724945-e030fa08-99b8-11e8-89ab-c7d8607e9949.png)

let us know if your still facing the issue after doing above changes  in your backend

**Comment by apurcaroiu** [comment]
Hey @Sunilkumarr
I did the change and it works now.
Since we perform token refresh on our side, should we update the password with the new token  in applozic each time we refresh our token  ?  Or you only perform checks on login and register against the server url?

Thanks

**Comment by Sunilkumarr** [comment]
You need to do login again with new access token
