### ISSUE TITLE
Call notifications not working when app in sleep mode for Android Oreo

### ISSUE THREAD

**Issue by apurcaroiu** [AppLozic/Applozic-Android-SDK#331]
## Goals
Audio and video notification calls should wake up the device when in sleep mode.

## Expected Results
When putting the device in sleep mode, audio and video calls should unlock the device and be visible to the user.

## Actual Results
Notification calls did not wake up the device.

## Steps to Reproduce
1. Use sample provided in github
2. Set up FCM in firebase console.
3. Test up notifications from applozic notification test page and confirm it is working.
4. Close the application and put the device in sleep mode.
5. Call user and notice the device does not wake up for the call notificaiton
6. This only happens on Oreo devices.

Applozic Android SDK version:  API 27

Android device: Hwaei Mate10, Hwaei P10 Lite

Android OS version: Android Oreo

Dependencies used with version:  Firebase 11.8.0

Thanks

**Comment by apurcaroiu** [comment]
Yes. But the notification does still not get triggered anymore after extensive sleep mode (like 10 minutes).

**Comment by apurcaroiu** [comment]
I am seeing this behavior on some Hwaei devices as mentioned (Mate10 and P10 Lite). It looks to be working fine on others.

**Comment by Sunilkumarr** [comment]
@apurcaroiu Can you share us your  sample project ?
