### ISSUE TITLE
*Feature Request* Enable auto download option for attachment type messages

### ISSUE THREAD

**Issue by apurcaroiu** [AppLozic/Applozic-Android-SDK#334]
Goals
Enable auto download functionality for attachment type messages.

Expected Results
Is there a way to auto download the attachments for the user receiver? Currently all attachments have the download layout screen. If not what would be the option to download it directly?

I see there is a TO DO in the DetailedConversationAdapater.java
  //TODO: 1. get the image Size and decide if we can download directly

**Comment by apurcaroiu** [comment]
@Sunilkumarr Do you guys have any plans of adding this option in next releases or provide a diff with what would take to support this, as all chat applications have auto download  by default enabled.

I tried to do some changes in the DetailedConversationAdapter but I got into other issues.

Thanks

**Comment by Sunilkumarr** [comment]
@apurcaroiu will check to add in our upcoming releases  and let you know  here or if I find some workaround will share the changes

**Comment by apurcaroiu** [comment]
@Sunilkumarr any plans to do this feature this year? We really need the auto download option like whatsapp has and I am having issues doing it by my own as it seems to cause side effects.

Thanks!
