### ISSUE TITLE
Error:(496, 5) String types not allowed (at 'applozic_message_search_text_color' with value '').

### ISSUE THREAD

**Issue by umar5009** [AppLozic/Applozic-Android-SDK#337]
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'kotlin-kapt'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.sprint.krizma"
        minSdkVersion 21
        targetSdkVersion 27

        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        packagingOptions {
            exclude 'META-INF/DEPENDENCIES'
            exclude 'META-INF/NOTICE'
            exclude 'META-INF/LICENSE'
            exclude 'META-INF/LICENSE.txt'
            exclude 'META-INF/NOTICE.txt'
            exclude 'META-INF/ECLIPSE_.SF'
            exclude 'META-INF/ECLIPSE_.RSA'
        }

    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildToolsVersion '27.0.3'
}

repositories {
    maven { url "https://raw.githubusercontent.com/smilefam/SendBird-SDK-Android/master/" }
    google()
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.facebook.android:facebook-android-sdk:[4,5)'
    implementation 'de.hdodenhof:circleimageview:2.2.0'
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'com.github.bumptech.glide:glide:4.7.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    kapt 'com.github.bumptech.glide:compiler:4.7.1'
    compile 'com.google.android.gms:play-services-auth:11.8.0'
    compile 'com.google.android.gms:play-services-location:11.8.0'
    compile 'com.google.android.gms:play-services-maps:11.8.0'
    compile 'com.android.support:design:27.1.1'
    compile 'com.android.support:multidex:1.0.3'
    compile 'com.makeramen:roundedimageview:2.3.0'
    testImplementation 'junit:junit:4.12'
    compile 'com.android.volley:volley:1.1.1'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    compile 'com.android.support:support-annotations:27.1.1'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.hootsuite.android:nachos:1.1.1'
    compile 'com.github.traex.expandablelayout:library:1.2.2'
//    compile 'com.mesibo.api:mesibo:1.0.5'
//    compile 'com.mesibo.api:calls:1.0.3'
//    compile 'com.mesibo.api:ui:1.0.4'
    implementation 'com.sendbird.sdk:sendbird-android-sdk:3.0.72'
    implementation 'com.applozic.communication.uiwidget:mobicomkitui:5.9.3'

**Comment by reytum** [comment]
@umar5009 
We have already fixed the issue and will be available in our upcoming update.

Till then you can do the below steps:

Add the tag to your <resources in your colors.xml file
`xmlns:tools="http://schemas.android.com/tools"`

Then add the below color in your colors.xml file:
`<color name="applozic_message_search_text_color" tools:override="true">#FF4081</color>`

**Comment by reytum** [comment]
Issue has been fixed here:
https://github.com/AppLozic/Applozic-Android-SDK/releases/tag/5.9.4
