### ISSUE TITLE
[Skylab] "No Internet connection" error displays briefly

### ISSUE THREAD

**Issue by barbinkh** [AppLozic/Applozic-Android-SDK#339]
Received “no internet connection” notification when uploading a video that was previously recorded as an attachment.

**Comment by ShivamPokhriyal** [comment]
@barbinkh Is this happening every time?
Is there any pattern to reproduce it, like recording video for more than some specific time limit?

**Comment by barbinkh** [comment]
This issue reproduces when I have 4g and switch to the Wi-Fi.
