### ISSUE TITLE
[Skylab] Video Camera: Set Default Aspect Ratio

### ISSUE THREAD

**Issue by barbinkh** [AppLozic/Applozic-Android-SDK#340]
When you go to the default camera app and record horizontal video it is a full screen on the phone, then when you upload that video in chat it is also full screen. When you go to record Video from the chat, the video is cropped.

**Comment by reytum** [comment]
Can send the device and OS version on which this is happening.
Also the SDK version you are using.

**Comment by barbinkh** [comment]
I use Samsung Note8, Android 8.0 and SDK 5.9.1. 
STR:
1. Record video by android camera app
2. Record video by applozic SDK on the conversation screen.
3. Send video which we recorded by applozic.
4. Send video which we recorded by android camera app.
Aspect Ratio is different.
