### ISSUE TITLE
Custom sound notification not playing on Oreo devices

### ISSUE THREAD

**Issue by apurcaroiu** [AppLozic/Applozic-Android-SDK#342]
Goals
Custom sound notification  for Oreo devices

Expected Results
Applozic SDK provides the option to set a custom sound for notifications, as I can see in the NotificationService class.
When using a custom sound Uri, that sound does not play on Oreo devices, instead the default  sound still plays.

## Steps to Reproduce
1) Set custom sound uri in applozic client
2) Send message to client
3) Default sound notification still playing

**Comment by reytum** [comment]
@apurcaroiu Thanks for reporting the issue, will look into it.

**Comment by apurcaroiu** [comment]
@reytum  Were you able to look into this? I would assume it is because Oreo needs a channel id for notifications?

**Comment by reytum** [comment]
@apurcaroiu We have done the changes regarding this issue.
It will be available in our upcoming release scheduled for next week.

**Comment by reytum** [comment]
@apurcaroiu We have released this fix. Please refer here : https://github.com/AppLozic/Applozic-Android-SDK/releases/tag/5.10
