### ISSUE TITLE
error in compilation while adding sdk

### ISSUE THREAD

**Issue by ashusaini** [AppLozic/Applozic-Android-SDK#344]
## Goals
I want to integrate your SDK.
## Expected Results
it should compile properly.

## Actual Results
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJavaWithJavac'.

## Steps to Reproduce
just build

## Code Sample

Applozic Android SDK version: ?
5.9.4

Android device: any

Android OS version: any
Dependencies used with version: 
ext.daggerVersion = '2.10'
classpath "io.realm:realm-gradle-plugin:3.5.0"
databindig true
implementation 'com.google.android.gms:play-services-gcm:15.0.1'
ext.androidtoolsVersion = '27.1.1'

**Comment by Sunilkumarr** [comment]
@ashusaini  Hi, Can you share the complete logs and your app build.gradle file?

**Comment by ashusaini** [comment]
Hi, I have resolved the issue, actually its happening due to glide upgraded version in your library.  
it's conflicting with data binding.

**Comment by ashusaini** [comment]
resolution: 
    implementation ('com.applozic.communication.uiwidget:mobicomkitui:5.9.4'){
        exclude group: 'com.github.bumptech.glide'
    }

and use an older version of glide compatible with data binding
