### ISSUE TITLE
AudioVideo Library needs to be updated in Maven

### ISSUE THREAD

**Issue by vtjon** [AppLozic/Applozic-Android-SDK#355]
I am using the AudioVideo library in my app.  I have the following:
compile 'com.applozic.communication.uiwidget:audiovideo:2.1.1'

According to Maven, this has a dependency on Mobicomkitui V5.8.2. I need at least V5.8.5 so that I can unify the Google Play Services version in my app to 15.0. Can somebody update  this?

**Comment by Sunilkumarr** [comment]
@vtjon Hi, We have stoped audio video calling and we have depreciated audio video calling  in our SDK and we will not be updating audio video SDK  in maven either way you can downgrade  to the old verion of play services  or use the dependency resolution  in your build.gradle file and change the libary to 15.0
