### ISSUE TITLE
[Bug] send image/voice file as an attachment，but filepaths is null when i received message

### ISSUE THREAD

**Issue by cxMax** [AppLozic/Applozic-Android-SDK#360]
* my codes as follow ：
`
 MessageBuilder builder = new MessageBuilder(context)
                .setMetadata(messageMetaDataMap)
                .setTo(id);
builder.setContentType(Message.ContentType.ATTACHMENT.getValue());
            builder.setFilePath(path); // file local path
builder.send()
`

**Comment by cxMax** [comment]
fileMeta = {FileMeta@8442} "FileMeta{key='8a97c028-c0e8-40b3-8bb2-2a9adbb08ded', userKey='null', blobKey='AMIfv97vjOcqinZH1PWOfNc6OfjQfh4jcRX0URvy6tX4AvLtuEcyU1kDERHXNMdMUMQfl32yrwFRDgR4d9awJvGduZuv1YpkNEcVZhmvVCLOquDSNp7NzYCbmjrjX47_3wKH0UEAhQ4ujSfG0vllInM0VyAWK_uEvsQVVsHVkXSH4LkOt_vbhIEa5rozOWFql3TENowc0NntQ2su500CvcUU85ad_r0NP4wCVjmBErrQvXB6rjzrWvrkvelJHhJFeoRL6h9rLj3xLms6zz0ULgOWZAkn_Wa43A', thumbnailBlobKey='null', url=null, name='1551325914055.aac', size=1993, contentType='audio/aac', thumbnailUrl='null', createdAtTime=null}"
filePaths = null

**Comment by cxMax** [comment]
how can i set this value in manifest.xml to solve the problem?
"com.applozic.attachment.url"
@see {@link MobiComKitClientService#FILE_BASE_URL_METADATA_KEY}

**Comment by ShivamPokhriyal** [comment]
Hello @cxMax 

filePaths refers to the path of file in device. When you received an attachment(which is not yet downloaded) its filepath will be null. You will first have to download that attachment and then only you will be able to see the filepath in message object.

Please check this [link](https://docs.applozic.com/docs/android-chat-message-api#section-handling-the-attachment-download-progress) to know more about downloading attachments.

I am not sure why you would want to change the attachment url, but if you really want to try it out, then you can  use it like below :: 
`<meta-data
   android:name="com.applozic.attachment.url"
   android:value="YOUR_URL_HERE" />
`
