### ISSUE TITLE
I have received reduplicate group messages by using ApplozicUIListener

### ISSUE THREAD

**Issue by cxMax** [AppLozic/Applozic-Android-SDK#361]
Applozic.connectPublish(context);
Applozic.getInstance(context).registerUIListener(new ApplozicUIListener());

I uses these to deal with groups messages, but i found i received reduplicate group messages.
do you know why?

**Comment by cxMax** [comment]
before call Applozic.getInstance(context).registerUIListener(),
I already have call Applozic.getInstance(app).unregisterUIListener().
that's assurance there is only one instance of ApplozicUIListener in my application

**Comment by cxMax** [comment]
I have printed out the received messages in ApplozicUIListener#onMessageReceived(), the same message will received for twice or thrice times.
That's confused for me.

I have checked the source code of SDK. then find out the logic of messages dispatch.
When I call Applozic.connectPublish(context). the messages will deliver by ApplozicMqttService#messageArrived() -> SyncCallService -> ConversationIntentService#onHandleWork() -> MobiComMessageService#processInstantMessage() -> ApplozicBroadcastReceiver# onReceive() -> finally received messages with ApplozicUIListener#onMessageReceived() which has registered in ApplozicBroadcastReceiver when I call Applozic.getInstance(context).registerUIListener(new ApplozicUIListener());

Is there any way which I can deal messages directly in ApplozicMqttService#messageArrived() ?

**Comment by cxMax** [comment]
my workmate IOS software engineer also meet the same problem when he use Applozic-iOS-SDK .
the solution which he find out is dealing with messages directly in ApplozicMqttService#messageArrived().
that's what he suggest for me.

but I don't know whether it is the best way to solve this problem.
so I need your help. thank you

**Comment by ShivamPokhriyal** [comment]
@cxMax 

> I uses these to deal with groups messages, but i found i received reduplicate group messages.
> do you know why?

It might be possible that you are registering UI listener multiple times. 

> before call Applozic.getInstance(context).registerUIListener(),
I already have call Applozic.getInstance(app).unregisterUIListener().
that's assurance there is only one instance of ApplozicUIListener in my application

This is not the preferred way of registering and unregistering listener. Please refer to this [link](https://docs.applozic.com/docs/android-real-time-update#section-unregister-the-listener) for doing these. 
Although the above should've worked, but since you mentioned that you are receiving multiple callbacks in onMessageReceived, It is evident that more than one instance of this receiver is active in the application.

> Is there any way which I can deal messages directly in ApplozicMqttService#messageArrived() ?

Why would you want to do that? We have already given you a simpler interface to handle message dispatching. I am not sure how you can handle it in ApplozicMqttService.

> my workmate IOS software engineer also meet the same problem when he use Applozic-iOS-SDK .
the solution which he find out is dealing with messages directly in ApplozicMqttService#messageArrived().
that's what he suggest for me.

I'm afraid your iOS developer is going the wrong way. There are lot of processes involved when a message arrives to device. And we have already given a simpler interface which you can implement in your activity or view controller to handle messaging.

**Comment by cxMax** [comment]
OK. i'ill check my code first

**Comment by apurcaroiu** [comment]
@ShivamPokhriyal  @cxMax 
I also faced a similar issue although I was doing the  register/unregister in onResume/onStop.
What happened is that if I used this listener  in two consecutive screens, the next UI listener would get registered before the old one got unregistered.  The situation is quite different.

What I end up doing is to handle the broadcast registering without the Applozic helper class so  I can manage the instances.

The documentation you pointed to says that register should happen in onDestroy and unregister in onCreate. Is this accurate  ?  
**The best place for unregister would be onCreate(), and for register it would be onDestroy()**

thanks!

**Comment by cxMax** [comment]
it‘s s

> @ShivamPokhriyal @cxMax
> I also faced a similar issue although I was doing the register/unregister in onResume/onStop.
> What happened is that if I used this listener in two consecutive screens, the next UI listener would get registered before the old one got unregistered. The situation is quite different.
> 
> What I end up doing is to handle the broadcast registering without the Applozic helper class so I can manage the instances.
> 
> The documentation you pointed to says that register should happen in onDestroy and unregister in onCreate. Is this accurate ?
> **The best place for unregister would be onCreate(), and for register it would be onDestroy()**
> 
> thanks!

i will try , handle the broadcast may be a better solution to solve this.

btw, the guide document point that registerUIListener in onCreate() , unregisterUIListener in onDestroy(), isn't it? on the contrary of what you say

**Comment by ShivamPokhriyal** [comment]
@apurcaroiu 
> The best place for unregister would be onCreate(), and for register it would be onDestroy()

Actually It was a mistake from our side. I have updated the docs. 

> I also faced a similar issue although I was doing the register/unregister in onResume/onStop.

This again is the wrong way of handling register/unregister calls.
You can use onResume/onPause for your case. Register listener in onResume and unregister in onPause.

> What I end up doing is to handle the broadcast registering without the Applozic helper class so I can manage the instances.

I guess it would again create problems if you are using onResume/onStop. 

I would suggest you to register listener in onResume and unregister in onPause, and you can use Applozic helper class only.

**Comment by cxMax** [comment]
> @apurcaroiu
> 
> > The best place for unregister would be onCreate(), and for register it would be onDestroy()
> 
> Actually It was a mistake from our side. I have updated the docs.
> 
> > I also faced a similar issue although I was doing the register/unregister in onResume/onStop.
> 
> This again is the wrong way of handling register/unregister calls.
> You can use onResume/onPause for your case. Register listener in onResume and unregister in onPause.
> 
> > What I end up doing is to handle the broadcast registering without the Applozic helper class so I can manage the instances.
> 
> I guess it would again create problems if you are using onResume/onStop.
> I would suggest you to register listener in onResume and unregister in onPause, and you can use Applozic helper class only.
> 
> @cxMax I have updated docs. Please check again and ensure that you are registering once not multiple times.

Thank you for your professional suggestion. it's maybe our incorrect usage to causes this problem.

but I want to find out the real reason why I receive reduplicate group messages ,except register multi ApplozicUIListeners in my application lifecycle (include multi processes register multi listeners ).

is there any possibility which create chatting group with incorrect or missing necessary parameters may causes this problem?

thank you

**Comment by ShivamPokhriyal** [comment]
@cxMax 
>but I want to find out the real reason why I receive reduplicate group messages ,except register multi ApplozicUIListeners in my application lifecycle (include multi processes register multi listeners ).

I couldn't think of other reasons that would cause onMessageReceived to trigger multiple times. I am quite certain this issue is happening due to multiple registration of listener.
