### ISSUE TITLE
No interface to get the unread messages for Contextual Conversation

### ISSUE THREAD

**Issue by acpnayak** [AppLozic/Applozic-Android-SDK#365]
Hi, We have implemented the Contextual Conversation in one of our application. But we facing some issues with Contextual Conversations highlighted below

#1. We can't find any interface to get unread message count for Contextual conversation
#2. When user A is not in the Contextual Conversation window, and other user B send some messages in Conversation (say user B sent 3 new messages), and now user A launch the Contextual conversation window, user A is not shown new messages (received when he was not in window). And now if user B send new messages with user A in chat window, he will receive other 3 messages as well.

Please look into the above issues and let us know if you need more information.

Thanks.

**Comment by Sunilkumarr** [comment]
We have replied here for doc link for android in this issue https://github.com/AppLozic/Applozic-Chat-iOS-Framework/issues/89 

Adding it here as well You can refer this doc link for creating a context-based chat in a group of two  [link](https://docs.applozic.com/v1.0/docs/android-group-chat-sdk#section-context-based-chat-in-a-group-of-two)

Feel free to reopen if you need any help in this .
