### ISSUE TITLE
Attachment options

### ISSUE THREAD

**Issue by nozhaa** [AppLozic/Applozic-Android-SDK#368]
How can I add another attachment options ?

**Comment by reytum** [comment]
@nozhaa Currently we support limited attachment options in our prebuilt UI. What is the type of attachment you would like to add ? Since we do not have restrictions on the attachment type you can send, you can create the option by using custom UI or customising the prebuilt UI.

**Comment by nozhaa** [comment]
I want to add another icon in attachment options  allows to send message with attachment.
I did not find the average to add this icon.

**Comment by reytum** [comment]
@nozhaa 
We are using fontAwsome to display the icons.
To change the existing attachment options icons follow the below steps:
Add the below array in your string.xml file:

```
<string-array name="multimediaOptionIcons_without_price">
        <item>&#xf041;</item>
        <item>&#xf030;</item>
        <item>&#xf0c6;</item>
        <item>&#xf130;</item>
        <item>&#xf03d;</item>
        <item>&#xf007;</item>
    </string-array>
```

Then change the values for these icons. Refer to [this](https://fontawesome.com/cheatsheet) sheet for icons and their string value.
