### ISSUE TITLE
Custom background audio button

### ISSUE THREAD

**Issue by hsmedinar** [AppLozic/Applozic-Android-SDK#377]
## Code Sample

Applozic Android SDK version: ?

Android device: ?

Android OS version: ?

Dependencies used with version: ?

**Comment by Sunilkumarr** [comment]
You can check this [doc](https://docs.applozic.com/docs/android-chat-theme-and-customization) and add **applozic-settings.json** file then you can find the need to  **sendButtonBackgroundColor** 
and change the color for it is used for both audio  button  and send message button
