### ISSUE TITLE
getMessageListForContact

### ISSUE THREAD

**Issue by hsmedinar** [AppLozic/Applozic-Android-SDK#378]
I have to problemas whe try to get a list of message, the total fo message is 15 sms, however the method is return 16 sms.

I try to get info about the phanton message, the id is null and type is 100.

Anybody have the same problema? 

## Code Sample

Applozic Android SDK version: ?

Android device: ?

Android OS version: ?

Dependencies used with version: ?

**Comment by Sunilkumarr** [comment]
@hsmedinar Message type 100 is date message you can use  that type to show the date in between of messages by getting the     message.getCreatedAtTime(); for the type 100
