### ISSUE TITLE
Android SDK not working with targetSdkVersion 29

### ISSUE THREAD

**Issue by nantoka69** [AppLozic/Applozic-Android-SDK#382]
## Goals
I want to run the the Applozic Android SDK with the latest Android SDK (Version 29)

## Expected Results
File Up- and Download in chat screen does work

## Actual Results
Files can be selected, but don't get uploaded. The retry button produces a "File not found" toast.

## Steps to Reproduce
Set "targetSdkVersion 29" in the default config of the build.gradle file 

## Code Sample
android {
    compileSdkVersion 29
    defaultConfig {
        applicationId "com.yourapp"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 30
        versionName "1.0"
...

Applozic Android SDK version: 
5.61

Android device: Google Pixel 2XL

Android OS version: 10

The problem lies in com.applozic.mobicomkit.api.attachment.FileClientService.java:
...
dir = new File(Environment.getExternalStorageDirectory().getAbsolutePath() + folder);
            if (!dir.exists()) {
                dir.mkdirs();
            }
...
This does not work anymore from Android Q on, except you set android:requestLegacyExternalStorage="true". And this is really an ugly workaround and not a solution as it is more than unclear whether this will be supported by Android R next year.

Question: Is there a way (without recompiling the code) to force the Applozic SDK to use the scoped storage sytem like when the Applozic SDK detects an unmounted SD card?

**Comment by reytum** [comment]
@nantoka69 Thanks for reporting the issue. We are looking into it.

**Comment by reytum** [comment]
This is fixed in version 5.73
