### ISSUE TITLE
Proguard rules are incomplete, login fails

### ISSUE THREAD

**Issue by nantoka69** [AppLozic/Applozic-Android-SDK#384]
## Goals
Run the app with minifyEnabled and shrinkResources in release build type turned on

## Expected Results
Login to the Applozic server works

## Actual Results
Applozic server answers with a HTTP 401:
Response: {"message":"INVALID_PARAMETER","currentTimeStamp":1569936521407,"deactivate":false,"totalUnreadCount":0,"metadata":{},"newUser":false}

## Steps to Reproduce
Use the Proguard rules from this repo and turn minifyEnabled and shrinkResources on

## Bug fix
Add this to the proguard file:

-keepclassmembers class * extends com.applozic.mobicommons.json.JsonMarker {
	!static !transient <fields>;
}

-keepclassmembers class * extends com.applozic.mobicommons.json.JsonParcelableMarker {
	!static !transient <fields>;
}

This prevents Proguard from removing the class members that are only read by Gson and nowhere else, for example applicationId in the User class.

**Comment by Sunilkumarr** [comment]
@nantoka69 I tried with adding proguard rules I'm able to login successfully.

 Can you please share us below details to support@applozic.com 
 1)Complete Device logs once you login to applozic in a text file 
 2) Proguard file

**Comment by reytum** [comment]
@nantoka69 You can try the new proguard rules mentioned in the docs.
