### ISSUE TITLE
disable group info page android

### ISSUE THREAD

**Issue by lekhrajtiwari** [AppLozic/Applozic-Android-SDK#385]
please help.
i have been trying to implement applozic chat in my app. the issue am facing is i want to disable the on_click fn  on group title which  redirects to group info page page. i want to open my ui page for this screen
i have implemented this but still is opening the default applozic screen
 <meta-data
    android:name="com.applozic.mobicomkit.uiwidgets.toolbar.tap.activity"
    android:value="PUT_ACTIVITY_CLASS_HERE" />

also i want to know will the settings json file will be implemented by its self by placing it in my assets folder?

am using
implementation 'com.applozic.communication.uiwidget:mobicomkitui:5.51'
implementation 'com.android.support:appcompat-v7:28.0.0'
implementation 'com.android.support:support-v4:28.0.0'

**Comment by reytum** [comment]
@lekhrajtiwari You can set `"groupInfoScreenVisible": false` in `applozic-settings.json` file.
