### ISSUE TITLE
Dialogflow chatbot integration using applozic sdk

### ISSUE THREAD

**Issue by Devmobilesutra** [AppLozic/Applozic-Android-SDK#386]
I want to integrate dialogflow chatbot in applozic android sdk. I have done all setting of bot integration from https://console.applozic.com/bots/bot-integrations .And start chatting with bot id but my message not delivered to bot and not getting any message from bot.
I am using trial version of appLozic account.

**Comment by reytum** [comment]
@Devmobilesutra The bot doesn't work in one to one chat. You need to create a support group between the bot and the user and then it should work. Here is the doc for creating a support group: https://docs.applozic.com/docs/android-group-chat-sdk#section-creating-a-support-group
