### ISSUE TITLE
Crossplatform sending attachments not working properly. File not found issue.

### ISSUE THREAD

**Issue by mparag31** [AppLozic/Applozic-Android-SDK#388]
## Goals
Crossplatform communication should work proper in terms of Media. 

## Expected Results
Attachment name should not consists of folder paths. It should only be fileName with extension.

## Actual Results
File name consists of folders + file name at the end with extension.
Eg:  /storage/emulated/0/{app_folder_name}/image/AUD-5-/var/mobile/Containers/Data/Application/30442950-2E47-4A8F-B045-02AE35C435ED/Documents/IMG-1575466803473.5021971575466825847.jpeg
This is recieved on android when an image is sent from iOS. 
In actual it should be like this: 
 /storage/emulated/0/{app_folder_name}/image/IMG-1575466803473.5021971575466825847.jpeg

## Code Sample

Applozic Android SDK version: ?

Android device: ?

Android OS version: ?

Dependencies used with version: ?

**Comment by reytum** [comment]
@mparag31 Could you please provide the versions of the android and iOS SDKs in which you have faced this issue?
