### ISSUE TITLE
Not working "Open your Activity on tap of toolbar in Chat Screen"

### ISSUE THREAD

**Issue by iamjitendrasinh** [AppLozic/Applozic-Android-SDK#396]
## Goals
Open My Activity when user tap on toolbar

## Expected Results
open activity on tap of toolbar

## Actual Results
nothing happens

## Steps to Reproduce
follow doc
https://docs.applozic.com/docs/android-chat-theme-and-customization#open-your-activity-on-tap-of-toolbar-in-chat-screen

## Code Sample
<meta-data
    android:name="com.applozic.mobicomkit.uiwidgets.toolbar.tap.activity"
    android:value=".MainActivity" />

Applozic Android SDK version: 
Latest

Also I have noticed you have something called ALProfileClickListener, but there is no documentation how to use that

**Comment by Sunilkumarr** [comment]
@iamjitendrasinh We have added the new callbacks for this using ALProfileClickListener and removed the manifest entry callback.  You can refer to this [link](https://docs.applozic.com/docs/android-chat-theme-and-customization#open-your-screen-on-the-tap-toolbar)

**Comment by iamjitendrasinh** [comment]
Okay Thanks, but kindly update documentation
