### ISSUE TITLE
App crash when trying to read mimetype from the Uri.

### ISSUE THREAD

**Issue by vishalnaikawadi** [AppLozic/Applozic-Android-SDK#398]
## Goals
I'm trying to get mime type with the help of `com.applozic.mobicommons.file.FileUtils.getMimeType(ctx, uri)`

## Expected Results
it must return the mime type of the file URI provided.

## Actual Results

It is crashing on OnePlus 5 running android 7.1.1

`Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{1b565db 5919:com.leadschool.parentapp/u0a57} (pid=5919, uid=10057) that is not exported from uid 10036`

`android.content.ContentResolver.query (ContentResolver.java:474)
com.applozic.mobicommons.file.FileUtils.calculateInSampleSize (FileUtils.java)
com.applozic.mobicommons.file.FileUtils.getName (FileUtils.java)
com.applozic.mobicommons.file.FileUtils.getLastModifiedFile (FileUtils.java)
com.leadschool.parentapp.Chat.Presenter.AttachmentPresenter.access$getActivity$p (AttachmentPresenter.java)
com.leadschool.parentapp.application.ParentsApplication.getAppContext (ParentsApplication.java)
com.applozic.mobicomkit.uiwidgets.conversation.activity.MobiComAttachmentSelectorActivity.onActivityResult (MobiComAttachmentSelectorActivity.java)`

## Steps to Reproduce
`AttachmentFilteringListener` implement this listener in the application class. 
override `onAttachmentSelected(Activity activity, Uri selectedFileUri, AlCallback callback)`
attach an image from conversation activity. so you'll get the call back in the above method.

## Code Sample
fileUri is selectedFileUri, context is an instance of activity returned by the callback.
`fileUri?.let { uri ->
            context?.let { ctx ->
                when (com.applozic.mobicommons.file.FileUtils.getMimeType(ctx, uri)) {
                    MimeType.JPG.type, MimeType.JPEG.type, MimeType.PNG.type -> doSomething()
                    else -> doSomethingElse()
                }
            }
        }`

Applozic Android SDK version: ?
'com.applozic.communication.uiwidget:mobicomkitui:5.77'

Android device: OnePlus

Android OS version: 7.1.1

**Comment by Sunilkumarr** [comment]
@vishalnaikawadi We are not able to replicate that issue in our sample project: https://github.com/AppLozic/Applozic-Android-SDK 

Can you share any sample or the app build.gradle file and android manifest file.

And also can you check if the context which is activity.getBaseContext() or applicationContext?

The application class looks like below where I have implemented the `AttachmentFilteringListener`  : 

    public class ApplozicSampleApplication extends MultiDexApplication  implements AttachmentFilteringListener {

    @Override
    public void onCreate() {
        super.onCreate();
        try {
            Fabric.with(this, new Crashlytics());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }

    @Override
    public void onAttachmentSelected(Activity activity, Uri selectedFileUri, AlCallback callback) {
       String mimType = FileUtils.getMimeType(activity.getBaseContext(),selectedFileUri);

       Log.i("ApplozicSample", "mimType: "+mimType);


    } } 

Logs where I can get the mime type as below 

``` 2020-08-07 14:59:10.816 12175-12175/com.mobicomkit.sample I/ApplozicSample: mimType: image/jpeg```

**Comment by vishalnaikawadi** [comment]
Hi,
The issue I've mentioned is from our crashlytics reports. we also not able to reproduce the issue. It might be a device-specific. also, we haven't encountered this issue in the last two releases.
