### ISSUE TITLE
App crashes when selecting file from downloads public directory

### ISSUE THREAD

**Issue by vishalnaikawadi** [AppLozic/Applozic-Android-SDK#400]
## Goals
Trying to attach an image file from the attachment screen.

## Expected Results
image file must be selected and it must be visible in the attachment screen.

## Actual Results
when selecting an image file with file chooser from downloads directory, app crashes with IllegalArgumentException.
`java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=10, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/15138 flg=0x1 }} to activity {com.leadschool.parentapp/com.applozic.mobicomkit.uiwidgets.conversation.activity.MobiComAttachmentSelectorActivity}: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/15138`

## Steps to Reproduce

1. Open the conversation module and open any chat.
2. Click on the attachment icon.
3. File chooser will be open. Click on the Hamburger button to open the navigation drawer.
4. Select Downloads
5. Select an image file from the downloads directory

## Code Sample
Not applicable as issue is with `MobiComAttachmentSelectorActivity`

Applozic Android SDK version: ?
'com.applozic.communication.uiwidget:mobicomkitui:5.80'

Android device: ?
Oneplus 6 A6000 (running android 10)
Moto G(5th gen) (running android 8.1)

**Comment by Sunilkumarr** [comment]
@vishalnaikawadi Hi I have tried the above steps in by going and selecting image or  file from download folder in  Oneplus 6 A6000 (running android 10) 

In  sample project repo https://github.com/AppLozic/Applozic-Android-SDK with gradle  dependency '  
  ``api 'com.applozic.communication.uiwidget:mobicomkitui:5.80'`` 
It works fine

Could you please help us by share with us any sample project where this is happening ?

**Comment by vishalnaikawadi** [comment]
@Sunilkumarr  Hi, I tried the sample project you mentioned. and it works fine. but the problem occurred when you implement `AttachmentFilteringListener` in your application class. and try to get mimeType as follow:

`  @Override
    public void onAttachmentSelected(Activity activity, Uri selectedFileUri, AlCallback callback) {
        String mimetype = FileUtils.getMimeType(activity.getApplicationContext(), selectedFileUri); //this, getApplicationContext(), activity, activity.getApplicationContext() nothing works
        System.out.println("mimetype==="+mimetype);
        callback.onSuccess(selectedFileUri);
    }`

I have already raised the issue regarding this problem. 
https://github.com/AppLozic/Applozic-Android-SDK/issues/398

above call back works fine with most of the directories(I haven't tested all). although, it crashes when an image selected from downloads directory(in sample app too)

**Comment by Sunilkumarr** [comment]
@vishalnaikawadi Hi 

You can use this method below method in place of `FileUtils.getMimeType` this below method should work fine.

```
  String mimType = FileUtils.getMimeTypeByContentUriOrOther(activity.getBaseContext(), selectedFileUri);
```

**Comment by vishalnaikawadi** [comment]
@Sunilkumarr Hi, thanks for your reply. I tried the method you mentioned, it works fine for me.
closing this issue.
