### ISSUE TITLE
Media Files are not uploading

### ISSUE THREAD

**Issue by Scarecrow94** [AppLozic/Applozic-Android-SDK#401]
## Expected Results

normal full featured chat experience. 

## Actual Results

Media files keep uploading forever. No crash just endless upload. Chat works fine. but attachments dont work at all. The voice note gets broken after 3 seconds.

## Code Sample

No crash or code sample. 

Applozic Android SDK version: ?

version 5.80

Android device: Samsung Note 10+

Android OS version: Android 10

Dependencies used with version: Glide

**Comment by Sunilkumarr** [comment]
@Scarecrow94 Can you share any Sample project where this is happing? I'm not able to replicate in our sample project https://github.com/AppLozic/Applozic-Android-SDK
