### ISSUE TITLE
how can i send forward message to multiple user?

### ISSUE THREAD

**Issue by kanikatandel** [AppLozic/Applozic-Android-SDK#402]
## Code Sample

Applozic Android SDK version: ?

Android device: ?

Android OS version: ?

Dependencies used with version: ?

**Comment by Sunilkumarr** [comment]
Hi @kanikatandel In Pre-build UI we don't have support for forwarding messages to multiple users at a time. 
We only have support for forwarding a single message to a single user/group.

If your build custom UI using our custom UI methods  in your app you can check out this send message API 
https://docs.applozic.com/docs/android-chat-message-api#sending-a-message
