### ISSUE TITLE
error code 403 on SDK version 5.93

### ISSUE THREAD

**Issue by ypbae12** [AppLozic/Applozic-Android-SDK#407]
Hello
I use a Singapore regional server.

I use SDK version 5.80 and recently updated SDK version 5.93.
these issues are happening on all devices and on all versions.

I used it to respond to the progress of the Android API level 29 update.

How can I fix the ‘Access Denied’ error?

Applozic Android SDK version: 5.93

Android device: ?

Android OS version: ?

Dependencies used with version: 5.80

**Comment by Sunilkumarr** [comment]
@ypbae12 Can you connect us at support@applozic.com with the configuration you used on the device side and also link this issue in the mail.

**Comment by Sunilkumarr** [comment]
@ypbae12  You can use 5.95 this has been fixed.
