### ISSUE TITLE
contactImage on click is not functionable 

### ISSUE THREAD

**Issue by williamwong9090** [AppLozic/Applozic-Android-SDK#409]
Why ContactImage onclick is not functionable

**Comment by Sunilkumarr** [comment]
Hi @williamwong9090, You can check this doc [link](https://docs.applozic.com/docs/android-chat-theme-and-customization#open-your-screen-on-the-tap-toolbar-profile-icon-tap) and you will have to implement this callback in your application class if the application class is not there you will have to create one.

**Comment by williamwong9090** [comment]
Hi . may i know applozic got any latest android and ios github source code. my company plan to using ur service but we need to run a demo project .

**Comment by Sunilkumarr** [comment]
Hello @williamwong9090,
We have SDK demos for Android and iOS 

1. **Android demo project:** You can clone this repository 
https://github.com/AppLozic/Applozic-Android-SDK 
and login with any new userId and any password 

2. **For iOS Swift SDK demo project:** : 
You can check out this sample pod project you will have to clone this repo to run https://github.com/AppLozic/ApplozicSwift

**Note:** Make sure to do this before running run  **pod install**  in a terminal inside folder **ApplozicSwift/Demo/**

3. **For iOS Objective c SDK and demo project**  : 
  You will have to clone this git repository 
  https://github.com/AppLozic/Applozic-iOS-SDK

For more documentation on implementing in your app, you can check this link https://www.applozic.com/docs.html
