### ISSUE TITLE
Contact image blank when the user is typing

### ISSUE THREAD

**Issue by khairunsh** [AppLozic/Applozic-Android-SDK#420]
Is it a bug or am I missing something, contact image is blank/shows no image when the user is typing.

![Screenshot from 2021-03-30 10-45-44](https://user-images.githubusercontent.com/25631476/112930959-6e0c4180-9145-11eb-8268-0b8ea3756fe4.png)
![Screenshot from 2021-03-30 10-45-56](https://user-images.githubusercontent.com/25631476/112930964-72385f00-9145-11eb-81a5-4f2e603ae956.png)

Applozic Android SDK version: 5.98

Android device: Pixel 2

Android OS version: Android 11 (R)

Dependencies used with version: 5.98

**Comment by Sunilkumarr** [comment]
@khairunsh Hey,

We will replicate and let you know if we have something on this.

Thanks.

**Comment by Sunilkumarr** [comment]
Hi,
We found the issue and This will be released on the 10th of May.

**Comment by shubham-applozic** [comment]
Hey, 
The issue has been fixed. Please update to v5.99.0.
Refer to the readme for the new installation steps. 
https://github.com/AppLozic/Applozic-Android-SDK/blob/master/README.md

Will be closing this issue.
Thank you.
