### ISSUE TITLE
Applozic.connectUser method not working

### ISSUE THREAD

**Issue by salahhalkhoums** [AppLozic/Applozic-Android-SDK#421]
I have tried to implement the Pre-built chat app to my app but when I launch the conversation activity the app stucks on "Please wait".
I have also tried to test your whole pre built project and it has the same issue (stuck on loading after pressing the Login/Register button)
When I tried to debug both apps, the Applozic.connectUser is never executed ( the onFailure method is also not executed).
I am wondering weather it is a bug or a server related problem.
![Capture](https://user-images.githubusercontent.com/45936385/112999522-ef280080-9166-11eb-8117-626d7269c4e3.PNG)

**Comment by Sunilkumarr** [comment]
@salahhalkhoums Hi,

I have tried in our sample project it works fine.

Have you tried on the real device?

Can you share the complete logs from android studio Logcat starting from the login attach the logs in the text file here?

What is the Android device name and Android OS version?

**Comment by Sunilkumarr** [comment]
@salahhalkhoums 
Can you check the app id is correct check if any extra character is added to it in end or starting when you're pasting it to the android manifest?

And also check in logs for this tag: **Registration json** 

And see if the applicationId is going in this JSON?

**Comment by salahhalkhoums** [comment]
I checked and it has an incorrect id.
It turned out that I was missing the Applozic.init() that takes in the app id as parameter on my MainActivity.
the app is working now thank you for your help.

**Comment by Sunilkumarr** [comment]
@salahhalkhoums Thanks for the update.
