### ISSUE TITLE
Regarding voice chat messages

### ISSUE THREAD

**Issue by hardikJoshi123** [AppLozic/Applozic-Android-SDK#430]
Hello. I am using Applozic for my android app.  How can I identified the other user is heard the voice messages or not similar to WhatsApp. Once the receiver heard the voice message, I want to change colors for heard and unheard. I would happy to hear from Applozic support regarding this feature.

**Comment by Sunilkumarr** [comment]
@hardikJoshi123 Hi,

Currently, this feature we dont have in our SDK will forward this to our product team.
