### ISSUE TITLE
Conversation list page is not showing display name of user

### ISSUE THREAD

**Issue by priyadarshi** [AppLozic/Applozic-Android-SDK#61]
Conversation list page is not showing display name of user.

Steps to reproduce:
1) Login to app with new userid "testuser" and display name "auto user"
2)Login to app using userid "user1" then send message to userid "testuser"
3)Conversation list page is not showing display name "auto user", it shows userid "testuser". After     
relogin it shows display name.

**Comment by devashishmamgain** [comment]
Not in priority, as client app can pass userId and displayName while opening chat.

**Comment by priyadarshi** [comment]
Already fixed. So closing the ticket.
